// AUTO-GENERATED by scripts/bilan.js — 2026-08-30T19:00:00.000Z
// Ne pas éditer : relancer sync.command.
window.BILAN = {
 "generatedAt": "2026-08-30T19:00:00.000Z",
 "mois": [
  {
   "key": "2025-09",
   "label": "sept. 25",
   "h": 38.3,
   "n": 38,
   "jours": 27,
   "re": 741,
   "disc": {
    "nat": {
     "h": 0,
     "km": 0,
     "n": 0
    },
    "velo": {
     "h": 4.2,
     "km": 90,
     "n": 1
    },
    "run": {
     "h": 5.9,
     "km": 52,
     "n": 4
    },
    "autre": {
     "h": 28.1,
     "km": 54,
     "n": 33
    }
   },
   "types": {
    "Pilates": 23,
    "Run": 4,
    "Hike": 2,
    "WeightTraining": 5,
    "EMountainBikeRide": 3,
    "Ride": 1
   }
  },
  {
   "key": "2025-10",
   "label": "oct. 25",
   "h": 33.3,
   "n": 29,
   "jours": 25,
   "re": 827,
   "disc": {
    "nat": {
     "h": 0,
     "km": 0,
     "n": 0
    },
    "velo": {
     "h": 10.5,
     "km": 247,
     "n": 3
    },
    "run": {
     "h": 5.2,
     "km": 34,
     "n": 2
    },
    "autre": {
     "h": 17.6,
     "km": 32,
     "n": 24
    }
   },
   "types": {
    "Pilates": 22,
    "Ride": 3,
    "HighIntensityIntervalTraining": 1,
    "EMountainBikeRide": 1,
    "TrailRun": 1,
    "Run": 1
   }
  },
  {
   "key": "2025-11",
   "label": "nov. 25",
   "h": 30.8,
   "n": 31,
   "jours": 24,
   "re": 821,
   "disc": {
    "nat": {
     "h": 0.1,
     "km": 0,
     "n": 1
    },
    "velo": {
     "h": 0.3,
     "km": 6,
     "n": 1
    },
    "run": {
     "h": 9.8,
     "km": 91,
     "n": 8
    },
    "autre": {
     "h": 20.6,
     "km": 104,
     "n": 21
    }
   },
   "types": {
    "Pilates": 15,
    "Run": 8,
    "Hike": 1,
    "EMountainBikeRide": 3,
    "HighIntensityIntervalTraining": 2,
    "Ride": 1,
    "Swim": 1
   }
  },
  {
   "key": "2025-12",
   "label": "déc. 25",
   "h": 23.4,
   "n": 24,
   "jours": 22,
   "re": 504,
   "disc": {
    "nat": {
     "h": 0.6,
     "km": 1,
     "n": 2
    },
    "velo": {
     "h": 2.8,
     "km": 58,
     "n": 2
    },
    "run": {
     "h": 9.5,
     "km": 91,
     "n": 8
    },
    "autre": {
     "h": 10.5,
     "km": 18,
     "n": 12
    }
   },
   "types": {
    "Run": 8,
    "Pilates": 11,
    "EMountainBikeRide": 1,
    "Ride": 2,
    "Swim": 2
   }
  },
  {
   "key": "2026-01",
   "label": "janv. 26",
   "h": 29.6,
   "n": 40,
   "jours": 27,
   "re": 917,
   "disc": {
    "nat": {
     "h": 1.3,
     "km": 4,
     "n": 5
    },
    "velo": {
     "h": 0.7,
     "km": 0,
     "n": 1
    },
    "run": {
     "h": 11.3,
     "km": 118,
     "n": 13
    },
    "autre": {
     "h": 16.3,
     "km": 15,
     "n": 21
    }
   },
   "types": {
    "Run": 13,
    "Pilates": 13,
    "Swim": 5,
    "HighIntensityIntervalTraining": 7,
    "EMountainBikeRide": 1,
    "Ride": 1
   }
  },
  {
   "key": "2026-02",
   "label": "févr. 26",
   "h": 30.2,
   "n": 39,
   "jours": 23,
   "re": 1003,
   "disc": {
    "nat": {
     "h": 3,
     "km": 8,
     "n": 8
    },
    "velo": {
     "h": 10.3,
     "km": 224,
     "n": 9
    },
    "run": {
     "h": 5.3,
     "km": 55,
     "n": 8
    },
    "autre": {
     "h": 11.6,
     "km": 15,
     "n": 14
    }
   },
   "types": {
    "Swim": 8,
    "Pilates": 8,
    "EMountainBikeRide": 1,
    "Run": 8,
    "HighIntensityIntervalTraining": 3,
    "Ride": 4,
    "Workout": 2,
    "VirtualRide": 5
   }
  },
  {
   "key": "2026-03",
   "label": "mars 26",
   "h": 33.1,
   "n": 34,
   "jours": 23,
   "re": 920,
   "disc": {
    "nat": {
     "h": 3.1,
     "km": 7,
     "n": 7
    },
    "velo": {
     "h": 13.8,
     "km": 403,
     "n": 14
    },
    "run": {
     "h": 5.3,
     "km": 53,
     "n": 4
    },
    "autre": {
     "h": 11,
     "km": 29,
     "n": 9
    }
   },
   "types": {
    "VirtualRide": 13,
    "Pilates": 7,
    "Run": 4,
    "Swim": 7,
    "Hike": 2,
    "Ride": 1
   }
  },
  {
   "key": "2026-04",
   "label": "avr. 26",
   "h": 20.1,
   "n": 28,
   "jours": 18,
   "re": 788,
   "disc": {
    "nat": {
     "h": 1.4,
     "km": 3,
     "n": 3
    },
    "velo": {
     "h": 9,
     "km": 236,
     "n": 8
    },
    "run": {
     "h": 5.3,
     "km": 57,
     "n": 7
    },
    "autre": {
     "h": 4.4,
     "km": 0,
     "n": 10
    }
   },
   "types": {
    "Run": 7,
    "VirtualRide": 6,
    "Pilates": 8,
    "Swim": 3,
    "Ride": 2,
    "HighIntensityIntervalTraining": 1,
    "Workout": 1
   }
  },
  {
   "key": "2026-05",
   "label": "mai 26",
   "h": 17.2,
   "n": 28,
   "jours": 18,
   "re": 367,
   "disc": {
    "nat": {
     "h": 1.8,
     "km": 4,
     "n": 3
    },
    "velo": {
     "h": 4,
     "km": 106,
     "n": 5
    },
    "run": {
     "h": 2.8,
     "km": 29,
     "n": 5
    },
    "autre": {
     "h": 8.6,
     "km": 15,
     "n": 15
    }
   },
   "types": {
    "VirtualRide": 3,
    "Pilates": 12,
    "Run": 5,
    "Ride": 2,
    "Swim": 3,
    "EMountainBikeRide": 1,
    "Workout": 2
   }
  },
  {
   "key": "2026-06",
   "label": "juin 26",
   "h": 8.4,
   "n": 15,
   "jours": 13,
   "re": 177,
   "disc": {
    "nat": {
     "h": 0.9,
     "km": 2,
     "n": 2
    },
    "velo": {
     "h": 0,
     "km": 0,
     "n": 0
    },
    "run": {
     "h": 3.8,
     "km": 37,
     "n": 5
    },
    "autre": {
     "h": 3.7,
     "km": 0,
     "n": 8
    }
   },
   "types": {
    "Run": 5,
    "Pilates": 8,
    "Swim": 2
   }
  },
  {
   "key": "2026-07",
   "label": "juil. 26",
   "h": 5.3,
   "n": 11,
   "jours": 10,
   "re": 106,
   "disc": {
    "nat": {
     "h": 0,
     "km": 0,
     "n": 0
    },
    "velo": {
     "h": 0,
     "km": 0,
     "n": 0
    },
    "run": {
     "h": 1.4,
     "km": 14,
     "n": 3
    },
    "autre": {
     "h": 3.8,
     "km": 0,
     "n": 8
    }
   },
   "types": {
    "Pilates": 8,
    "Run": 3
   }
  },
  {
   "key": "2026-08",
   "label": "août 26",
   "h": 11.1,
   "n": 15,
   "jours": 10,
   "re": 330,
   "disc": {
    "nat": {
     "h": 0.2,
     "km": 1,
     "n": 1
    },
    "velo": {
     "h": 0.9,
     "km": 27,
     "n": 1
    },
    "run": {
     "h": 4.4,
     "km": 42,
     "n": 6
    },
    "autre": {
     "h": 5.7,
     "km": 0,
     "n": 7
    }
   },
   "types": {
    "Pilates": 3,
    "Run": 6,
    "Workout": 4,
    "VirtualRide": 1,
    "Swim": 1
   }
  }
 ],
 "total": {
  "h": 280.8,
  "n": 332,
  "jours": 240
 },
 "efficacite": {
  "course": [
   {
    "date": "2025-08-31",
    "km": 12.8,
    "pace": "7:35",
    "paceSec": 455,
    "hr": 132,
    "dplus": 63
   },
   {
    "date": "2025-09-05",
    "km": 13.6,
    "pace": "6:14",
    "paceSec": 374,
    "hr": 143,
    "dplus": 116
   },
   {
    "date": "2025-09-13",
    "km": 14.9,
    "pace": "7:51",
    "paceSec": 471,
    "hr": 123,
    "dplus": 120
   },
   {
    "date": "2025-09-21",
    "km": 15.2,
    "pace": "6:58",
    "paceSec": 418,
    "hr": 129,
    "dplus": 136
   },
   {
    "date": "2025-10-25",
    "km": 20.1,
    "pace": "11:28",
    "paceSec": 688,
    "hr": 127,
    "dplus": 920
   },
   {
    "date": "2025-10-28",
    "km": 14.2,
    "pace": "5:44",
    "paceSec": 344,
    "hr": 149,
    "dplus": 139
   },
   {
    "date": "2025-11-09",
    "km": 19.5,
    "pace": "6:59",
    "paceSec": 419,
    "hr": 147,
    "dplus": 555
   },
   {
    "date": "2025-11-17",
    "km": 8.2,
    "pace": "6:02",
    "paceSec": 362,
    "hr": 153,
    "dplus": 105
   },
   {
    "date": "2025-11-18",
    "km": 9.9,
    "pace": "6:00",
    "paceSec": 360,
    "hr": 139,
    "dplus": 106
   },
   {
    "date": "2025-11-19",
    "km": 8.2,
    "pace": "6:08",
    "paceSec": 368,
    "hr": 165,
    "dplus": 111
   },
   {
    "date": "2025-11-21",
    "km": 21,
    "pace": "6:47",
    "paceSec": 407,
    "hr": 128,
    "dplus": 235
   },
   {
    "date": "2025-11-29",
    "km": 14,
    "pace": "5:47",
    "paceSec": 347,
    "hr": 141,
    "dplus": 105
   },
   {
    "date": "2025-12-04",
    "km": 17.9,
    "pace": "6:19",
    "paceSec": 379,
    "hr": 133,
    "dplus": 86
   },
   {
    "date": "2025-12-13",
    "km": 17.9,
    "pace": "6:43",
    "paceSec": 403,
    "hr": 127,
    "dplus": 159
   },
   {
    "date": "2025-12-25",
    "km": 16.6,
    "pace": "6:34",
    "paceSec": 394,
    "hr": 133,
    "dplus": 100
   },
   {
    "date": "2025-12-28",
    "km": 11.7,
    "pace": "5:36",
    "paceSec": 336,
    "hr": 141,
    "dplus": 84
   },
   {
    "date": "2026-01-01",
    "km": 27.6,
    "pace": "5:47",
    "paceSec": 347,
    "hr": 129,
    "dplus": 235
   },
   {
    "date": "2026-01-10",
    "km": 11.6,
    "pace": "5:01",
    "paceSec": 301,
    "hr": 167,
    "dplus": 117
   },
   {
    "date": "2026-01-24",
    "km": 13.1,
    "pace": "5:52",
    "paceSec": 352,
    "hr": 146,
    "dplus": 111
   },
   {
    "date": "2026-01-29",
    "km": 14,
    "pace": "5:49",
    "paceSec": 349,
    "hr": 135,
    "dplus": 95
   },
   {
    "date": "2026-03-06",
    "km": 13.3,
    "pace": "5:13",
    "paceSec": 313,
    "hr": 148,
    "dplus": 92
   },
   {
    "date": "2026-03-07",
    "km": 11.7,
    "pace": "7:42",
    "paceSec": 462,
    "hr": 118,
    "dplus": 81
   },
   {
    "date": "2026-03-23",
    "km": 21.1,
    "pace": "5:48",
    "paceSec": 348,
    "hr": 135,
    "dplus": 144
   },
   {
    "date": "2026-04-01",
    "km": 10.4,
    "pace": "5:53",
    "paceSec": 353,
    "hr": 137,
    "dplus": 130
   },
   {
    "date": "2026-04-10",
    "km": 8.4,
    "pace": "5:09",
    "paceSec": 309,
    "hr": 144,
    "dplus": 87
   },
   {
    "date": "2026-04-12",
    "km": 10,
    "pace": "5:17",
    "paceSec": 317,
    "hr": 153,
    "dplus": 58
   },
   {
    "date": "2026-04-30",
    "km": 10.2,
    "pace": "5:30",
    "paceSec": 330,
    "hr": 144,
    "dplus": 72
   },
   {
    "date": "2026-05-01",
    "km": 11,
    "pace": "5:38",
    "paceSec": 338,
    "hr": 141,
    "dplus": 99
   },
   {
    "date": "2026-06-03",
    "km": 10.1,
    "pace": "5:37",
    "paceSec": 337,
    "hr": 137,
    "dplus": 133
   },
   {
    "date": "2026-06-28",
    "km": 9.9,
    "pace": "5:43",
    "paceSec": 343,
    "hr": 139,
    "dplus": 28
   },
   {
    "date": "2026-06-28",
    "km": 9.8,
    "pace": "7:44",
    "paceSec": 464,
    "hr": 126,
    "dplus": 71
   },
   {
    "date": "2026-08-26",
    "km": 12.2,
    "pace": "6:27",
    "paceSec": 387,
    "hr": 130,
    "dplus": 86
   }
  ],
  "velo": [
   {
    "date": "2025-09-28",
    "min": 252,
    "w": 125,
    "hr": 132,
    "km": 90
   },
   {
    "date": "2025-10-04",
    "min": 112,
    "w": 157,
    "hr": 142,
    "km": 46
   },
   {
    "date": "2025-10-12",
    "min": 410,
    "w": 128,
    "hr": 136,
    "km": 156
   },
   {
    "date": "2025-10-17",
    "min": 108,
    "w": 159,
    "hr": 143,
    "km": 46
   },
   {
    "date": "2025-12-14",
    "min": 152,
    "w": 119,
    "hr": 137,
    "km": 58
   },
   {
    "date": "2026-02-18",
    "min": 124,
    "w": 164,
    "hr": 121,
    "km": 28
   },
   {
    "date": "2026-02-21",
    "min": 119,
    "w": 169,
    "hr": 142,
    "km": 49
   },
   {
    "date": "2026-02-23",
    "min": 63,
    "w": 145,
    "hr": 113,
    "km": 31
   },
   {
    "date": "2026-02-23",
    "min": 81,
    "w": 156,
    "hr": 135,
    "km": 30
   },
   {
    "date": "2026-02-24",
    "min": 64,
    "w": 154,
    "hr": 117,
    "km": 31
   },
   {
    "date": "2026-03-02",
    "min": 76,
    "w": 178,
    "hr": 124,
    "km": 41
   },
   {
    "date": "2026-03-04",
    "min": 62,
    "w": 192,
    "hr": 128,
    "km": 33
   },
   {
    "date": "2026-03-14",
    "min": 63,
    "w": 201,
    "hr": 130,
    "km": 31
   },
   {
    "date": "2026-03-21",
    "min": 225,
    "w": 135,
    "hr": 131,
    "km": 87
   },
   {
    "date": "2026-03-31",
    "min": 62,
    "w": 205,
    "hr": 131,
    "km": 31
   },
   {
    "date": "2026-04-05",
    "min": 160,
    "w": 158,
    "hr": 140,
    "km": 59
   },
   {
    "date": "2026-04-05",
    "min": 80,
    "w": 116,
    "hr": 133,
    "km": 28
   },
   {
    "date": "2026-04-08",
    "min": 60,
    "w": 189,
    "hr": 128,
    "km": 28
   },
   {
    "date": "2026-05-02",
    "min": 71,
    "w": 156,
    "hr": 131,
    "km": 25
   },
   {
    "date": "2026-05-31",
    "min": 73,
    "w": 174,
    "hr": 141,
    "km": 32
   }
  ],
  "courseTrim": [
   {
    "trimestre": "2025-T3",
    "paceA140": "7:40",
    "n": 4
   },
   {
    "trimestre": "2025-T4",
    "paceA140": "6:46",
    "n": 12
   },
   {
    "trimestre": "2026-T1",
    "paceA140": "6:02",
    "n": 7
   },
   {
    "trimestre": "2026-T2",
    "paceA140": "5:52",
    "n": 8
   },
   {
    "trimestre": "2026-T3",
    "paceA140": "6:57",
    "n": 1
   }
  ],
  "veloTrim": [
   {
    "trimestre": "2025-T3",
    "wA140": 133,
    "n": 1
   },
   {
    "trimestre": "2025-T4",
    "wA140": 141,
    "n": 4
   },
   {
    "trimestre": "2026-T1",
    "wA140": 187,
    "n": 10
   },
   {
    "trimestre": "2026-T2",
    "wA140": 165,
    "n": 5
   }
  ]
 },
 "lastActivityId": 19910337185,
 "coach": {
  "verdict": "L'entraînement redevient efficace, mais il repart de très bas : 5,3 h en juillet contre 30 h en mars, et 11 h en août — la remontée est réelle mais la base tendineuse ne l'est pas encore. Le signal encourageant est l'efficacité : 6:27/km à 130 bpm le 26/08 sur 12,2 km, soit une allure normalisée à 140 bpm de 6:57/km contre 5:52/km au printemps — tu as perdu environ 1 min/km d'économie de course, ce qui est exactement ce qu'on attend après 3 mois creux et ce qui revient le plus vite. Côté CrossFit, 30 kg sur hang squat clean/thrusters sur un AMRAP 30' en team, c'est une base honnête pour construire. La récupération est en train de se réparer : le trou du 16→24/08 (HRV LOW, FC repos 55-56, readiness 11-31) est refermé, dernière nuit à 9h15, HRV 39 BALANCED, FC repos 50 — retour dans ta base de 38 ms. Le ratio de charge 7j/28j à 1,43 confirme que tu montes vite : c'est le moment d'être discipliné sur l'intensité, pas ambitieux.",
  "forts": [
   "Économie de course qui remonte déjà : 12,2 km à 130 bpm seulement, avec 86 m D+, une semaine après la reprise.",
   "Sommeil solide : 8h11 de moyenne sur 28 nuits et 9h15 la dernière — c'est ton meilleur atout, la plupart des gens de 39 ans n'ont pas ça.",
   "HRV revenu en base (39 ms vs base 38) et FC repos redescendue de 56 à 50 en 8 jours : le système nerveux encaisse la reprise.",
   "Régularité déjà retrouvée : 5 séances et 3,8 h sur S35 après un juillet à 11 séances au total."
  ],
  "manques": [
   "Aucun cycle de force écrit : la seule séance chiffrée est le back squat 5×5 du 25/08 — il faut deux créneaux force fixes par semaine avec des charges qui montent de 2,5 kg.",
   "Volume trop bas pour l'objectif 10 km sous 55 min : 4,4 h de course en août, il faut viser 2h30-3h de course/semaine d'ici novembre.",
   "Vélo et natation quasi absents (0,9 h et 0,2 h en août) : ce sont tes heures de volume sans impact, indispensables pendant que les tendons se refont.",
   "Aucune donnée de nutrition ni de poids suivi, et aucune mention de douleur — je pars du principe qu'il n'y a rien à signaler, dis-le si c'est faux."
  ],
  "vigilance": "Le risque n°1 cette semaine est tendineux (Achille/genou) : tu passes de 2,8 séances/semaine à 6 jours actifs avec 3 doublés, et le ratio de charge est déjà à 1,43 — la course reste strictement en aisance, aucune intensité, sinon la blessure arrive avant la progression.",
  "semaine": {
   "titre": "Poser la régularité : 6 jours actifs, tout en aisance, 2 forces",
   "volumeCible": "~5 h 30",
   "doubles": "3",
   "jours": [
    {
     "jour": "Lun",
     "matin": {
      "ico": "🏃",
      "titre": "Course en aisance",
      "intention": "aisance",
      "detail": "40 min course très facile, FC < 140, terrain plat. Tu dois pouvoir parler en phrases complètes. Allure attendue autour de 6:30-7:00/km — ne regarde pas l'allure, regarde la FC.",
      "gardefou": "Si la FC dépasse 140 sans que tu accélères, tu marches 1 min et tu repars. Toute douleur au tendon d'Achille = tu rentres à pied."
     },
     "soir": {
      "ico": "🏋️",
      "titre": "Force pure — semaine 1/4 du cycle",
      "intention": "force",
      "detail": "Back squat 5×5 à la charge où les 2 dernières reps sortent propres (repère : ~70-75 % de ton max, tu étais à 5×5 le 25/08 → reprends la même charge, pas plus). Puis développé militaire 4×6, rowing barre 4×8, gainage 3×45 s planche + 3×30 s par côté. Repos 2 min entre séries lourdes.",
      "gardefou": "Si la technique se dégrade (dos qui s'arrondit, genoux qui rentrent), tu enlèves 5 kg et tu finis les séries. La charge se mérite la semaine 2."
     }
    },
    {
     "jour": "Mar",
     "matin": {
      "ico": "🚴",
      "titre": "Vélo facile / home-trainer",
      "intention": "aisance",
      "detail": "45 min à FC 120-135, cadence 85-95 rpm, puissance libre (autour de 140-160 W vu ton Zwift du 22/08). Zéro relance, zéro bosse à fond. Objectif : faire tourner les jambes après le squat.",
      "gardefou": "Jambes lourdes = tu réduis à 30 min, c'est de la récup active, pas une séance."
     },
     "soir": {
      "ico": "—",
      "titre": "Rien",
      "intention": "repos",
      "detail": "",
      "gardefou": ""
     }
    },
    {
     "jour": "Mer",
     "matin": {
      "ico": "🧘",
      "titre": "Pilates / mobilité",
      "intention": "skill",
      "detail": "30-40 min Pilates comme d'habitude, en insistant sur hanches et chevilles (mobilité de cheville = condition du squat propre et de la course sans douleur).",
      "gardefou": "Aucun."
     },
     "soir": {
      "ico": "🏋️",
      "titre": "Box CrossFit ou NST",
      "intention": "filière moyenne",
      "detail": "Séance de la box (WOD au tableau). Tu prends le niveau Int en réduisant la charge : 30 kg maximum sur tout ce qui est barre, comme dimanche 23/08. Skill en début de séance si le coach en propose. Vise un WOD de 8-15 min, pas un AMRAP 30'.",
      "gardefou": "Si le WOD du jour est du squat lourd ou du soulevé de terre lourd, tu fais la version légère : tu as déjà squatté lundi. Si c'est un chipper > 20 min, tu coupes à 20 min."
     }
    },
    {
     "jour": "Jeu",
     "matin": {
      "ico": "🏊",
      "titre": "Natation facile",
      "intention": "aisance",
      "detail": "30 min bassin : 200 m échauffement, puis 8×50 m souple avec 20 s de repos, 200 m avec pull-buoy, 200 m retour au calme. Technique et respiration, pas de chrono.",
      "gardefou": "Si tu n'as pas accès au bassin, remplace par 30 min de vélo facile — surtout pas par de la course."
     },
     "soir": {
      "ico": "—",
      "titre": "Rien",
      "intention": "repos",
      "detail": "",
      "gardefou": ""
     }
    },
    {
     "jour": "Ven",
     "matin": {
      "ico": "🏃",
      "titre": "Course en aisance + éducatifs",
      "intention": "aisance",
      "detail": "35 min FC < 140. Après 20 min, insère 6×20 s de foulées légères en accélération progressive (pas de sprint), 40 s de trot entre chaque, puis termine facile. Objectif : réveiller la fréquence de foulée sans créer de fatigue.",
      "gardefou": "Les foulées se font en aisance mécanique : si tu forces ou si tu sens un tiraillement au mollet, tu les sautes et tu finis en trot."
     },
     "soir": {
      "ico": "🏋️",
      "titre": "Box CrossFit ou NST",
      "intention": "filière courte",
      "detail": "Séance de la box. Cherche un format court et intense (< 8 min type EMOM ou for time court), avec du tirage et de la poussée plutôt que du squat. Ajoute en début de séance, frais : 5×3 strict pull-ups (ou excentriques 5 s si les 3 ne sortent pas propres) — c'est ta cible du test de novembre, on la travaille dès maintenant.",
      "gardefou": "Jamais deux séances dures d'affilée : si tu sors cassé de mercredi ou si le sommeil est descendu sous 6h30, tu remplaces par 30 min de rameur facile."
     }
    },
    {
     "jour": "Sam",
     "matin": {
      "ico": "🏃",
      "titre": "Sortie longue en aisance",
      "intention": "filière longue",
      "detail": "1 h 05 à 1 h 15 de course, FC strictement < 140, allure libre à la sensation (Billat : laisse l'allure varier, ne la fige pas). Terrain roulant, D+ modéré. Vise 10-11 km sans forcer. Emporte de l'eau.",
      "gardefou": "C'est la séance clé de la semaine : si tu dois en sauter une, ce n'est pas celle-là. Mais si la FC dérive au-dessus de 145 sur la deuxième moitié, tu écourtes à 55 min."
     },
     "soir": {
      "ico": "—",
      "titre": "Rien",
      "intention": "repos",
      "detail": "",
      "gardefou": ""
     }
    },
    {
     "jour": "Dim",
     "matin": {
      "ico": "—",
      "titre": "Rien",
      "intention": "repos",
      "detail": "",
      "gardefou": ""
     },
     "soir": {
      "ico": "—",
      "titre": "Repos complet",
      "intention": "repos",
      "detail": "Journée off totale. Marche, famille, batch cooking. C'est ce jour qui rend la semaine 2 possible.",
      "gardefou": "Pas de « petite sortie pour le plaisir ». Le repos est programmé, il se respecte comme une séance."
     }
    }
   ]
  },
  "regle": "Si la semaine déborde, tu sautes en priorité le vélo du mardi matin, puis la natation du jeudi — ce sont du volume de confort. Tu ne sautes jamais la sortie longue du samedi ni la force du lundi soir : ce sont les deux piliers de tout le bloc.",
  "nutrition": {
   "principe": "À 77,5 kg avec deux séances certains jours, vise 130-155 g de protéines par jour, réparties sur 3-4 prises d'environ 35-40 g (une paume de viande/poisson, 3 œufs, 200 g de fromage blanc), plutôt que concentrées le soir — c'est la répartition qui répare les tendons, pas le total. Les glucides se calent sur la séance : dîner copieux en féculents les soirs de force (lundi) et la veille de la sortie longue (vendredi), assiette dominée par les légumes le dimanche off et le jeudi léger. Aucun comptage : tu ajustes la portion de féculents entre 1 poing (jour léger) et 2 poings (jour force ou veille de longue).",
   "batch": [
    "Cuire 1,2 kg de blanc de poulet mariné au four → 6 portions, 4 j au frigo (congeler 2 portions)",
    "Cuire 500 g de riz basmati cru → environ 1,3 kg cuit, 6 portions, 4 j au frigo",
    "Cuire 400 g de lentilles vertes cru → environ 1 kg cuit, 5 portions, 5 j au frigo",
    "Rôtir 1,5 kg de légumes (courgettes, poivrons, patate douce) au four → 6 portions, 4 j au frigo",
    "Cuire 12 œufs durs → collations et boîtes, 7 j au frigo",
    "Préparer 700 ml de sauce yaourt-citron-herbes → assaisonne toutes les boîtes, 5 j au frigo",
    "Portionner 5 boîtes chantier complètes le dimanche soir (poulet + féculent + légumes + sauce à part)"
   ],
   "recettes": [
    {
     "nom": "Poulet mariné au four (base de la semaine)",
     "usage": "batch dimanche",
     "portions": "6 portions",
     "temps": "10 min prépa + 25 min four",
     "ingredients": [
      "1,2 kg de blancs de poulet",
      "4 cuillères à soupe d'huile d'olive",
      "2 cuillères à café de paprika fumé",
      "2 cuillères à café d'ail en poudre",
      "1 cuillère à café de cumin",
      "2 cuillères à café de sel",
      "1 citron (jus)"
     ],
     "etapes": [
      "Préchauffe le four à 200 °C chaleur tournante.",
      "Dans un grand saladier, mélange l'huile, le paprika, l'ail, le cumin, le sel et le jus de citron.",
      "Coupe les blancs de poulet en deux dans l'épaisseur s'ils font plus de 3 cm — ils cuiront plus vite et resteront moelleux.",
      "Mets le poulet dans le saladier et mélange à la main pendant 1 min pour que tout soit enrobé.",
      "Étale sur une plaque avec papier cuisson, sans que les morceaux se touchent.",
      "Enfourne 22 à 25 min. C'est cuit quand le jus qui sort est clair (pas rosé) et que la chair se sépare facilement à la fourchette.",
      "Laisse refroidir 20 min à découvert avant de mettre en boîte, sinon ça transpire et ça se conserve moins bien."
     ],
     "conservation": "4 j au frigo en boîte fermée, se congèle très bien en portions individuelles"
    },
    {
     "nom": "Riz basmati batch",
     "usage": "batch dimanche",
     "portions": "6 portions",
     "temps": "2 min prépa + 12 min cuisson",
     "ingredients": [
      "500 g de riz basmati cru",
      "900 ml d'eau",
      "1 cuillère à café de sel",
      "1 cuillère à soupe d'huile d'olive"
     ],
     "etapes": [
      "Rince le riz sous l'eau froide dans une passoire jusqu'à ce que l'eau sorte à peu près claire (environ 30 s).",
      "Mets le riz, l'eau et le sel dans une casserole. Porte à ébullition à feu vif, sans couvercle.",
      "Dès que ça bout, baisse au minimum, couvre et laisse 11 min sans jamais soulever le couvercle.",
      "Coupe le feu, laisse reposer 5 min couvert.",
      "Ouvre, ajoute l'huile et aère les grains à la fourchette. Les grains doivent être séparés, pas collants.",
      "Étale sur un plat pour refroidir 15 min avant de mettre en boîte."
     ],
     "conservation": "4 j au frigo, à réchauffer ou à manger froid en salade"
    },
    {
     "nom": "Lentilles vertes à la tomate",
     "usage": "batch dimanche / boîte chantier",
     "portions": "5 portions",
     "temps": "5 min prépa + 25 min cuisson",
     "ingredients": [
      "400 g de lentilles vertes crues",
      "1 oignon",
      "2 gousses d'ail",
      "1 boîte de tomates concassées (400 g)",
      "2 cuillères à soupe d'huile d'olive",
      "1 cuillère à café de thym",
      "1 cuillère à café de sel",
      "1,2 L d'eau"
     ],
     "etapes": [
      "Émince l'oignon et écrase les gousses d'ail.",
      "Fais chauffer l'huile dans une grande casserole à feu moyen, ajoute l'oignon et fais-le blondir 5 min en remuant.",
      "Ajoute l'ail, les lentilles rincées, les tomates, le thym et l'eau.",
      "Porte à ébullition puis baisse à petits bouillons et laisse 22 à 25 min sans couvercle.",
      "C'est prêt quand une lentille s'écrase facilement entre deux doigts mais garde sa forme. Sale en fin de cuisson.",
      "S'il reste beaucoup de liquide, laisse 3 min de plus à feu vif pour épaissir."
     ],
     "conservation": "5 j au frigo, se congèle"
    },
    {
     "nom": "Légumes rôtis au four",
     "usage": "batch dimanche",
     "portions": "6 portions",
     "temps": "12 min prépa + 30 min four",
     "ingredients": [
      "500 g de courgettes",
      "500 g de poivrons (2-3 pièces)",
      "500 g de patate douce",
      "4 cuillères à soupe d'huile d'olive",
      "2 cuillères à café d'herbes de Provence",
      "1,5 cuillère à café de sel"
     ],
     "etapes": [
      "Préchauffe le four à 210 °C chaleur tournante.",
      "Coupe la patate douce en cubes de 2 cm, les courgettes en demi-rondelles de 1,5 cm, les poivrons en lanières larges.",
      "Mets tout dans un saladier, verse l'huile, les herbes et le sel, mélange bien à la main.",
      "Étale sur deux plaques — si tu entasses, ça cuit à la vapeur au lieu de rôtir.",
      "Enfourne 30 min, mélange à mi-cuisson.",
      "C'est prêt quand les bords sont dorés et qu'un couteau traverse la patate douce sans résistance.",
      "Laisse tiédir 15 min avant la mise en boîte."
     ],
     "conservation": "4 j au frigo, se mange froid ou tiède"
    },
    {
     "nom": "Sauce yaourt citron-herbes",
     "usage": "batch dimanche — assaisonne les boîtes chantier",
     "portions": "7 portions (700 ml)",
     "temps": "5 min",
     "ingredients": [
      "500 g de yaourt grec nature",
      "1 citron (jus + zeste)",
      "3 cuillères à soupe d'huile d'olive",
      "1 gousse d'ail râpée",
      "1 bouquet de persil ou coriandre ciselé",
      "1 cuillère à café de sel",
      "poivre"
     ],
     "etapes": [
      "Verse le yaourt dans un bol.",
      "Ajoute le jus et le zeste du citron, l'huile, l'ail râpé fin.",
      "Cisèle les herbes et incorpore-les.",
      "Sale, poivre, mélange 30 s. La texture doit napper une cuillère sans couler.",
      "Mets en pot fermé au frigo."
     ],
     "conservation": "5 j au frigo, à transporter dans un petit pot séparé"
    },
    {
     "nom": "Œufs durs batch",
     "usage": "batch dimanche — collation et boîtes",
     "portions": "12 œufs",
     "temps": "12 min",
     "ingredients": [
      "12 œufs"
     ],
     "etapes": [
      "Mets les œufs dans une casserole et couvre d'eau froide à 2 cm au-dessus.",
      "Porte à ébullition à feu vif.",
      "Dès l'ébullition, baisse à frémissement et compte 9 min exactement.",
      "Égoutte et plonge immédiatement dans un saladier d'eau très froide 5 min — c'est ce qui rend l'écalage facile.",
      "Laisse les coquilles jusqu'au moment de manger."
     ],
     "conservation": "7 j au frigo avec la coquille"
    },
    {
     "nom": "Boîte chantier poulet-riz-légumes",
     "usage": "boîte chantier lundi, mardi, mercredi",
     "portions": "1 portion (× 3 dans la semaine)",
     "temps": "5 min d'assemblage",
     "ingredients": [
      "200 g de poulet mariné du batch",
      "200 g de riz cuit du batch",
      "250 g de légumes rôtis du batch",
      "100 ml de sauce yaourt (pot séparé)",
      "1 poignée de noix (30 g)"
     ],
     "etapes": [
      "Dans une boîte hermétique, mets le riz au fond.",
      "Coupe le poulet en lamelles et pose-le sur le riz.",
      "Ajoute les légumes rôtis par-dessus.",
      "Mets la sauce dans un petit pot à part — versée la veille, elle détrempe tout.",
      "Les noix dans un coin ou un sachet séparé pour qu'elles restent croquantes.",
      "Se mange froid tel quel, ou tiède si tu as accès à un micro-ondes."
     ],
     "conservation": "3 j au frigo une fois assemblée — assemble mardi soir celles de la fin de semaine"
    },
    {
     "nom": "Boîte chantier lentilles-œufs-feta",
     "usage": "boîte chantier jeudi et vendredi",
     "portions": "1 portion (× 2)",
     "temps": "5 min d'assemblage",
     "ingredients": [
      "300 g de lentilles à la tomate du batch",
      "2 œufs durs du batch",
      "50 g de feta",
      "150 g de légumes rôtis du batch",
      "1 cuillère à soupe d'huile d'olive"
     ],
     "etapes": [
      "Mets les lentilles froides au fond de la boîte.",
      "Ajoute les légumes rôtis.",
      "Écale les œufs le matin même, coupe-les en deux et pose-les dessus.",
      "Émiette la feta par-dessus, arrose d'un filet d'huile.",
      "Se mange parfaitement froid — c'est la boîte idéale les jours où tu n'as pas de micro-ondes."
     ],
     "conservation": "2 j au frigo assemblée"
    },
    {
     "nom": "Poêlée poulet-patate douce express",
     "usage": "dîner lundi (jour force)",
     "portions": "2 portions",
     "temps": "5 min prépa + 12 min cuisson",
     "ingredients": [
      "300 g de poulet du batch",
      "250 g de légumes rôtis du batch",
      "150 g de riz cuit du batch",
      "1 cuillère à soupe d'huile d'olive",
      "1 cuillère à soupe de sauce soja",
      "1 gousse d'ail",
      "100 g d'épinards frais"
     ],
     "etapes": [
      "Fais chauffer l'huile dans une grande poêle à feu vif.",
      "Ajoute l'ail écrasé et fais-le revenir 20 s, sans le brûler.",
      "Ajoute les légumes rôtis et le riz, remue 3 min pour bien réchauffer.",
      "Ajoute le poulet coupé en morceaux et la sauce soja, remue 2 min.",
      "Jette les épinards par-dessus, couvre 1 min : ils doivent tomber et devenir vert foncé.",
      "Mélange une dernière fois et sers immédiatement."
     ],
     "conservation": "À manger le soir même, la 2e portion tient 2 j au frigo"
    },
    {
     "nom": "Saumon au four et légumes",
     "usage": "dîner mercredi et samedi",
     "portions": "2 portions",
     "temps": "5 min prépa + 15 min four",
     "ingredients": [
      "300 g de pavés de saumon (2 pièces)",
      "300 g de légumes rôtis du batch",
      "1 citron",
      "1 cuillère à soupe d'huile d'olive",
      "sel, poivre",
      "150 g de riz cuit du batch (samedi seulement)"
     ],
     "etapes": [
      "Préchauffe le four à 200 °C.",
      "Pose les pavés de saumon sur du papier cuisson, peau en dessous.",
      "Arrose d'huile, sale, poivre, pose 2 rondelles de citron sur chaque pavé.",
      "Enfourne 13 à 15 min. C'est cuit quand la chair devient opaque rosé clair et se sépare en lamelles sous la fourchette — ne dépasse pas 15 min, ça devient sec.",
      "Pendant ce temps, réchauffe les légumes (et le riz le samedi) 3 min à la poêle ou 2 min au micro-ondes.",
      "Sers avec un trait de jus de citron."
     ],
     "conservation": "À manger le soir même"
    },
    {
     "nom": "Omelette aux légumes et fromage blanc",
     "usage": "dîner jeudi et dimanche (jours légers)",
     "portions": "1 portion",
     "temps": "3 min prépa + 7 min cuisson",
     "ingredients": [
      "4 œufs",
      "150 g de légumes rôtis du batch",
      "30 g de fromage râpé",
      "1 cuillère à café d'huile d'olive",
      "sel, poivre",
      "salade verte + 1 cuillère à soupe de vinaigrette"
     ],
     "etapes": [
      "Bats les 4 œufs à la fourchette avec sel et poivre pendant 20 s.",
      "Chauffe l'huile dans une poêle à feu moyen, ajoute les légumes rôtis et réchauffe-les 2 min.",
      "Verse les œufs par-dessus, laisse prendre 2 min sans toucher.",
      "Ramène les bords vers le centre avec une spatule et incline la poêle pour que l'œuf liquide coule sur les bords.",
      "Parsème le fromage, plie l'omelette en deux et coupe le feu. Le centre doit rester légèrement baveux — il finit de cuire dans l'assiette.",
      "Sers avec la salade."
     ],
     "conservation": "À manger immédiatement"
    },
    {
     "nom": "Pâtes thon-tomate d'avant-longue",
     "usage": "dîner vendredi (veille de sortie longue)",
     "portions": "2 portions",
     "temps": "5 min prépa + 12 min cuisson",
     "ingredients": [
      "200 g de pâtes complètes crues",
      "2 boîtes de thon au naturel (2×140 g)",
      "400 g de tomates concassées (1 boîte)",
      "1 oignon",
      "2 cuillères à soupe d'huile d'olive",
      "1 cuillère à café d'origan",
      "sel, poivre",
      "30 g de parmesan râpé"
     ],
     "etapes": [
      "Fais bouillir une grande casserole d'eau salée et lance les pâtes selon le temps du paquet (environ 10 min).",
      "Pendant ce temps, émince l'oignon et fais-le revenir 4 min dans l'huile à feu moyen jusqu'à ce qu'il devienne translucide.",
      "Ajoute les tomates et l'origan, laisse mijoter 6 min à petits bouillons — la sauce doit épaissir et ne plus être liquide.",
      "Égoutte le thon et ajoute-le à la sauce, remue 1 min sans l'écraser complètement.",
      "Égoutte les pâtes en gardant une louche d'eau de cuisson, mélange-les à la sauce avec un peu de cette eau.",
      "Sers avec le parmesan. Portion généreuse ce soir : c'est le carburant de samedi matin."
     ],
     "conservation": "2 j au frigo, se mange froid en salade de pâtes"
    }
   ],
   "courses": [
    {
     "rayon": "Protéines",
     "items": [
      "1,2 kg de blancs de poulet",
      "2 pavés de saumon (300 g)",
      "2 boîtes de thon au naturel (2×140 g)"
     ]
    },
    {
     "rayon": "Féculents & légumineuses",
     "items": [
      "1 paquet de riz basmati (1 kg)",
      "1 paquet de lentilles vertes (500 g)",
      "1 paquet de pâtes complètes (500 g)",
      "1 sachet de noix (200 g)"
     ]
    },
    {
     "rayon": "Légumes & fruits",
     "items": [
      "500 g de courgettes",
      "3 poivrons (environ 500 g)",
      "500 g de patate douce",
      "2 oignons",
      "1 tête d'ail",
      "2 citrons",
      "1 sachet d'épinards frais (150 g)",
      "1 sachet de salade verte",
      "1 bouquet de persil ou coriandre",
      "6 bananes",
      "1 barquette de fruits rouges ou 4 pommes"
     ]
    },
    {
     "rayon": "Produits laitiers & œufs",
     "items": [
      "24 œufs (2 boîtes de 12) + 12 œufs pour les petits-déjeuners = 3 boîtes de 12",
      "500 g de yaourt grec nature",
      "1 grand pot de fromage blanc (1 kg)",
      "1 bloc de feta (200 g)",
      "1 sachet de fromage râpé (200 g)",
      "1 sachet de parmesan râpé (100 g)"
     ]
    },
    {
     "rayon": "Épicerie",
     "items": [
      "2 boîtes de tomates concassées (2×400 g)",
      "1 bouteille d'huile d'olive (50 cl)",
      "1 petite bouteille de sauce soja",
      "paprika fumé, ail en poudre, cumin, thym, origan, herbes de Provence",
      "1 paquet de flocons d'avoine (500 g)",
      "1 pot de miel"
     ]
    }
   ],
   "jours": [
    {
     "jour": "Lun",
     "type": "jour force (course facile matin + force soir)",
     "petitDej": "Habituel + 1 banane (tu cours avant 6 h, la banane évite de partir complètement à vide sur 40 min)",
     "dejeuner": "Boîte chantier poulet-riz-légumes : 200 g poulet, 200 g riz, 250 g légumes rôtis, sauce yaourt à part, 30 g de noix",
     "collation": "Après la force : 200 g de fromage blanc + 1 cuillère à soupe de miel + 1 banane, dans l'heure qui suit",
     "diner": "Poêlée poulet-patate douce express (300 g poulet, 250 g légumes, 150 g riz, épinards) — portion généreuse, c'est le soir qui répare le squat"
    },
    {
     "jour": "Mar",
     "type": "jour léger (vélo facile matin)",
     "petitDej": "Habituel",
     "dejeuner": "Boîte chantier poulet-riz-légumes (2e boîte)",
     "collation": "1 pomme + 2 œufs durs du batch en milieu d'après-midi",
     "diner": "Grande assiette de lentilles à la tomate (300 g) + 150 g de légumes rôtis + salade verte. Peu de féculents supplémentaires, le vélo était facile"
    },
    {
     "jour": "Mer",
     "type": "jour box (Pilates matin + CrossFit soir)",
     "petitDej": "Habituel",
     "dejeuner": "Boîte chantier poulet-riz-légumes (3e boîte)",
     "collation": "Avant la box (vers 17 h) : 1 banane + une poignée de noix. Après : 200 g de fromage blanc",
     "diner": "Saumon au four (150 g) + 300 g de légumes rôtis + salade. Rapide et digeste après un WOD tardif"
    },
    {
     "jour": "Jeu",
     "type": "jour léger (natation matin)",
     "petitDej": "Habituel",
     "dejeuner": "Boîte chantier lentilles-œufs-feta (froide, parfaite sans micro-ondes)",
     "collation": "—",
     "diner": "Omelette 4 œufs aux légumes rôtis + fromage râpé + salade verte. Assiette légère, journée calme"
    },
    {
     "jour": "Ven",
     "type": "veille de sortie longue (course matin + box soir)",
     "petitDej": "Habituel + 1 banane",
     "dejeuner": "Boîte chantier lentilles-œufs-feta (2e boîte)",
     "collation": "Avant la box : 1 banane. Après : 200 g de fromage blanc + miel",
     "diner": "Pâtes thon-tomate, grosse assiette (100 g de pâtes crues pour toi) + parmesan. C'est le repas qui remplit les réserves pour samedi"
    },
    {
     "jour": "Sam",
     "type": "sortie longue (1 h 05 à 1 h 15 le matin)",
     "petitDej": "Habituel + 60 g de flocons d'avoine avec un peu de miel, 1 h avant de partir (sur 1 h 15 de course, tu as besoin d'un peu plus que 3 œufs)",
     "dejeuner": "Au retour : reste de pâtes thon-tomate froid + 2 œufs durs + fruits rouges",
     "collation": "Dans les 30 min après la sortie : 1 banane + 200 g de fromage blanc",
     "diner": "Saumon au four (150 g) + 300 g de légumes rôtis + 150 g de riz du batch"
    },
    {
     "jour": "Dim",
     "type": "repos complet + batch cooking",
     "petitDej": "Habituel",
     "dejeuner": "Ce que tu goûtes pendant le batch : poulet du four + légumes rôtis tièdes + salade",
     "collation": "—",
     "diner": "Omelette 4 œufs aux légumes + grande salade verte. Assiette légère, légumes dominants, journée sans séance"
    }
   ]
  },
  "generatedAt": "2026-08-30T19:00:00.000Z",
  "programme": {
   "programme": "Hybride Automne 2026",
   "objectif": "Devenir hybride : tenir une heure de course en aisance ET des charges propres en CrossFit, sans blessure.",
   "cible": {
    "date": "2026-11-21",
    "libelle": "Test hybride maison (samedi 21/11) : 10 km en aisance sous 55 min (FC moyenne < 155) le matin, puis l'après-midi 5 tractions strictes enchaînées + back squat 5 reps à 1× poids de corps + 500 m rameur."
   },
   "semaineDansCycle": 1,
   "totalSemaines": 12,
   "bloc": {
    "id": 1,
    "nom": "Fondation",
    "semaines": 4,
    "debut": "2026-08-31",
    "but": "Reposer la régularité et la tolérance tendineuse. Aucune intensité en course.",
    "doubles": [
     3,
     3,
     4,
     2
    ],
    "priorites": [
     "Bi-quotidien progressif : 3 doublés en semaine 1 et 2, 4 en semaine 3, 2 en semaine de décharge (matin aérobie facile, soir qualité)",
     "6 jours actifs par semaine, volume 5 h → 7 h, progression max +15 %/semaine",
     "Toute la course en aisance stricte (FC < 140), sortie longue jusqu'à 1 h 15",
     "2 séances de force par semaine (dont la box NST), charges modérées, technique avant charge",
     "Réintroduire vélo (1×/sem) et natation (1×/sem) comme volume sans impact",
     "Aucune séance de fractionné course — le corps encaisse encore la reprise"
    ],
    "test": "Semaine 4 (décharge) : demi-Cooper (3 min à fond après échauffement) pour mesurer vVO2max, si HRV en base."
   },
   "semaineDansBloc": 1,
   "decharge": false,
   "avantDebut": false,
   "debut": "2026-08-31",
   "termine": false
  },
  "semaineLabel": "2026-S36",
  "semaineDebut": "2026-08-31",
  "semaineFin": "2026-09-06"
 }
};
