// AUTO-GENERATED by scripts/bilan.js — 2026-08-22T13:35:14.372Z
// Ne pas éditer : relancer sync.command.
window.BILAN = {
 "generatedAt": "2026-08-22T13:35:14.372Z",
 "mois": [
  {
   "key": "2025-09",
   "label": "sept. 25",
   "h": 38.3,
   "n": 38,
   "jours": 27,
   "re": 741,
   "disc": {
    "nat": {
     "h": 0,
     "km": 0,
     "n": 0
    },
    "velo": {
     "h": 4.2,
     "km": 90,
     "n": 1
    },
    "run": {
     "h": 5.9,
     "km": 52,
     "n": 4
    },
    "autre": {
     "h": 28.1,
     "km": 54,
     "n": 33
    }
   },
   "types": {
    "Pilates": 23,
    "Run": 4,
    "Hike": 2,
    "WeightTraining": 5,
    "EMountainBikeRide": 3,
    "Ride": 1
   }
  },
  {
   "key": "2025-10",
   "label": "oct. 25",
   "h": 33.3,
   "n": 29,
   "jours": 25,
   "re": 827,
   "disc": {
    "nat": {
     "h": 0,
     "km": 0,
     "n": 0
    },
    "velo": {
     "h": 10.5,
     "km": 247,
     "n": 3
    },
    "run": {
     "h": 5.2,
     "km": 34,
     "n": 2
    },
    "autre": {
     "h": 17.6,
     "km": 32,
     "n": 24
    }
   },
   "types": {
    "Pilates": 22,
    "Ride": 3,
    "HighIntensityIntervalTraining": 1,
    "EMountainBikeRide": 1,
    "TrailRun": 1,
    "Run": 1
   }
  },
  {
   "key": "2025-11",
   "label": "nov. 25",
   "h": 30.8,
   "n": 31,
   "jours": 24,
   "re": 821,
   "disc": {
    "nat": {
     "h": 0.1,
     "km": 0,
     "n": 1
    },
    "velo": {
     "h": 0.3,
     "km": 6,
     "n": 1
    },
    "run": {
     "h": 9.8,
     "km": 91,
     "n": 8
    },
    "autre": {
     "h": 20.6,
     "km": 104,
     "n": 21
    }
   },
   "types": {
    "Pilates": 15,
    "Run": 8,
    "Hike": 1,
    "EMountainBikeRide": 3,
    "HighIntensityIntervalTraining": 2,
    "Ride": 1,
    "Swim": 1
   }
  },
  {
   "key": "2025-12",
   "label": "déc. 25",
   "h": 23.4,
   "n": 24,
   "jours": 22,
   "re": 504,
   "disc": {
    "nat": {
     "h": 0.6,
     "km": 1,
     "n": 2
    },
    "velo": {
     "h": 2.8,
     "km": 58,
     "n": 2
    },
    "run": {
     "h": 9.5,
     "km": 91,
     "n": 8
    },
    "autre": {
     "h": 10.5,
     "km": 18,
     "n": 12
    }
   },
   "types": {
    "Run": 8,
    "Pilates": 11,
    "EMountainBikeRide": 1,
    "Ride": 2,
    "Swim": 2
   }
  },
  {
   "key": "2026-01",
   "label": "janv. 26",
   "h": 29.6,
   "n": 40,
   "jours": 27,
   "re": 917,
   "disc": {
    "nat": {
     "h": 1.3,
     "km": 4,
     "n": 5
    },
    "velo": {
     "h": 0.7,
     "km": 0,
     "n": 1
    },
    "run": {
     "h": 11.3,
     "km": 118,
     "n": 13
    },
    "autre": {
     "h": 16.3,
     "km": 15,
     "n": 21
    }
   },
   "types": {
    "Run": 13,
    "Pilates": 13,
    "Swim": 5,
    "HighIntensityIntervalTraining": 7,
    "EMountainBikeRide": 1,
    "Ride": 1
   }
  },
  {
   "key": "2026-02",
   "label": "févr. 26",
   "h": 30.2,
   "n": 39,
   "jours": 23,
   "re": 1003,
   "disc": {
    "nat": {
     "h": 3,
     "km": 8,
     "n": 8
    },
    "velo": {
     "h": 10.3,
     "km": 224,
     "n": 9
    },
    "run": {
     "h": 5.3,
     "km": 55,
     "n": 8
    },
    "autre": {
     "h": 11.6,
     "km": 15,
     "n": 14
    }
   },
   "types": {
    "Swim": 8,
    "Pilates": 8,
    "EMountainBikeRide": 1,
    "Run": 8,
    "HighIntensityIntervalTraining": 3,
    "Ride": 4,
    "Workout": 2,
    "VirtualRide": 5
   }
  },
  {
   "key": "2026-03",
   "label": "mars 26",
   "h": 33.1,
   "n": 34,
   "jours": 23,
   "re": 920,
   "disc": {
    "nat": {
     "h": 3.1,
     "km": 7,
     "n": 7
    },
    "velo": {
     "h": 13.8,
     "km": 403,
     "n": 14
    },
    "run": {
     "h": 5.3,
     "km": 53,
     "n": 4
    },
    "autre": {
     "h": 11,
     "km": 29,
     "n": 9
    }
   },
   "types": {
    "VirtualRide": 13,
    "Pilates": 7,
    "Run": 4,
    "Swim": 7,
    "Hike": 2,
    "Ride": 1
   }
  },
  {
   "key": "2026-04",
   "label": "avr. 26",
   "h": 20.1,
   "n": 28,
   "jours": 18,
   "re": 788,
   "disc": {
    "nat": {
     "h": 1.4,
     "km": 3,
     "n": 3
    },
    "velo": {
     "h": 9,
     "km": 236,
     "n": 8
    },
    "run": {
     "h": 5.3,
     "km": 57,
     "n": 7
    },
    "autre": {
     "h": 4.4,
     "km": 0,
     "n": 10
    }
   },
   "types": {
    "Run": 7,
    "VirtualRide": 6,
    "Pilates": 8,
    "Swim": 3,
    "Ride": 2,
    "HighIntensityIntervalTraining": 1,
    "Workout": 1
   }
  },
  {
   "key": "2026-05",
   "label": "mai 26",
   "h": 17.2,
   "n": 28,
   "jours": 18,
   "re": 367,
   "disc": {
    "nat": {
     "h": 1.8,
     "km": 4,
     "n": 3
    },
    "velo": {
     "h": 4,
     "km": 106,
     "n": 5
    },
    "run": {
     "h": 2.8,
     "km": 29,
     "n": 5
    },
    "autre": {
     "h": 8.6,
     "km": 15,
     "n": 15
    }
   },
   "types": {
    "VirtualRide": 3,
    "Pilates": 12,
    "Run": 5,
    "Ride": 2,
    "Swim": 3,
    "EMountainBikeRide": 1,
    "Workout": 2
   }
  },
  {
   "key": "2026-06",
   "label": "juin 26",
   "h": 8.4,
   "n": 15,
   "jours": 13,
   "re": 177,
   "disc": {
    "nat": {
     "h": 0.9,
     "km": 2,
     "n": 2
    },
    "velo": {
     "h": 0,
     "km": 0,
     "n": 0
    },
    "run": {
     "h": 3.8,
     "km": 37,
     "n": 5
    },
    "autre": {
     "h": 3.7,
     "km": 0,
     "n": 8
    }
   },
   "types": {
    "Run": 5,
    "Pilates": 8,
    "Swim": 2
   }
  },
  {
   "key": "2026-07",
   "label": "juil. 26",
   "h": 5.3,
   "n": 11,
   "jours": 10,
   "re": 106,
   "disc": {
    "nat": {
     "h": 0,
     "km": 0,
     "n": 0
    },
    "velo": {
     "h": 0,
     "km": 0,
     "n": 0
    },
    "run": {
     "h": 1.4,
     "km": 14,
     "n": 3
    },
    "autre": {
     "h": 3.8,
     "km": 0,
     "n": 8
    }
   },
   "types": {
    "Pilates": 8,
    "Run": 3
   }
  },
  {
   "key": "2026-08",
   "label": "août 26",
   "h": 4.5,
   "n": 7,
   "jours": 6,
   "re": 175,
   "disc": {
    "nat": {
     "h": 0,
     "km": 0,
     "n": 0
    },
    "velo": {
     "h": 0,
     "km": 0,
     "n": 0
    },
    "run": {
     "h": 2.3,
     "km": 23,
     "n": 4
    },
    "autre": {
     "h": 2.2,
     "km": 0,
     "n": 3
    }
   },
   "types": {
    "Pilates": 2,
    "Run": 4,
    "Workout": 1
   }
  }
 ],
 "total": {
  "h": 274.2,
  "n": 324,
  "jours": 236
 },
 "efficacite": {
  "course": [
   {
    "date": "2025-08-31",
    "km": 12.8,
    "pace": "7:35",
    "paceSec": 455,
    "hr": 132,
    "dplus": 63
   },
   {
    "date": "2025-09-05",
    "km": 13.6,
    "pace": "6:14",
    "paceSec": 374,
    "hr": 143,
    "dplus": 116
   },
   {
    "date": "2025-09-13",
    "km": 14.9,
    "pace": "7:51",
    "paceSec": 471,
    "hr": 123,
    "dplus": 120
   },
   {
    "date": "2025-09-21",
    "km": 15.2,
    "pace": "6:58",
    "paceSec": 418,
    "hr": 129,
    "dplus": 136
   },
   {
    "date": "2025-10-25",
    "km": 20.1,
    "pace": "11:28",
    "paceSec": 688,
    "hr": 127,
    "dplus": 920
   },
   {
    "date": "2025-10-28",
    "km": 14.2,
    "pace": "5:44",
    "paceSec": 344,
    "hr": 149,
    "dplus": 139
   },
   {
    "date": "2025-11-09",
    "km": 19.5,
    "pace": "6:59",
    "paceSec": 419,
    "hr": 147,
    "dplus": 555
   },
   {
    "date": "2025-11-17",
    "km": 8.2,
    "pace": "6:02",
    "paceSec": 362,
    "hr": 153,
    "dplus": 105
   },
   {
    "date": "2025-11-18",
    "km": 9.9,
    "pace": "6:00",
    "paceSec": 360,
    "hr": 139,
    "dplus": 106
   },
   {
    "date": "2025-11-19",
    "km": 8.2,
    "pace": "6:08",
    "paceSec": 368,
    "hr": 165,
    "dplus": 111
   },
   {
    "date": "2025-11-21",
    "km": 21,
    "pace": "6:47",
    "paceSec": 407,
    "hr": 128,
    "dplus": 235
   },
   {
    "date": "2025-11-29",
    "km": 14,
    "pace": "5:47",
    "paceSec": 347,
    "hr": 141,
    "dplus": 105
   },
   {
    "date": "2025-12-04",
    "km": 17.9,
    "pace": "6:19",
    "paceSec": 379,
    "hr": 133,
    "dplus": 86
   },
   {
    "date": "2025-12-13",
    "km": 17.9,
    "pace": "6:43",
    "paceSec": 403,
    "hr": 127,
    "dplus": 159
   },
   {
    "date": "2025-12-25",
    "km": 16.6,
    "pace": "6:34",
    "paceSec": 394,
    "hr": 133,
    "dplus": 100
   },
   {
    "date": "2025-12-28",
    "km": 11.7,
    "pace": "5:36",
    "paceSec": 336,
    "hr": 141,
    "dplus": 84
   },
   {
    "date": "2026-01-01",
    "km": 27.6,
    "pace": "5:47",
    "paceSec": 347,
    "hr": 129,
    "dplus": 235
   },
   {
    "date": "2026-01-10",
    "km": 11.6,
    "pace": "5:01",
    "paceSec": 301,
    "hr": 167,
    "dplus": 117
   },
   {
    "date": "2026-01-24",
    "km": 13.1,
    "pace": "5:52",
    "paceSec": 352,
    "hr": 146,
    "dplus": 111
   },
   {
    "date": "2026-01-29",
    "km": 14,
    "pace": "5:49",
    "paceSec": 349,
    "hr": 135,
    "dplus": 95
   },
   {
    "date": "2026-03-06",
    "km": 13.3,
    "pace": "5:13",
    "paceSec": 313,
    "hr": 148,
    "dplus": 92
   },
   {
    "date": "2026-03-07",
    "km": 11.7,
    "pace": "7:42",
    "paceSec": 462,
    "hr": 118,
    "dplus": 81
   },
   {
    "date": "2026-03-23",
    "km": 21.1,
    "pace": "5:48",
    "paceSec": 348,
    "hr": 135,
    "dplus": 144
   },
   {
    "date": "2026-04-01",
    "km": 10.4,
    "pace": "5:53",
    "paceSec": 353,
    "hr": 137,
    "dplus": 130
   },
   {
    "date": "2026-04-10",
    "km": 8.4,
    "pace": "5:09",
    "paceSec": 309,
    "hr": 144,
    "dplus": 87
   },
   {
    "date": "2026-04-12",
    "km": 10,
    "pace": "5:17",
    "paceSec": 317,
    "hr": 153,
    "dplus": 58
   },
   {
    "date": "2026-04-30",
    "km": 10.2,
    "pace": "5:30",
    "paceSec": 330,
    "hr": 144,
    "dplus": 72
   },
   {
    "date": "2026-05-01",
    "km": 11,
    "pace": "5:38",
    "paceSec": 338,
    "hr": 141,
    "dplus": 99
   },
   {
    "date": "2026-06-03",
    "km": 10.1,
    "pace": "5:37",
    "paceSec": 337,
    "hr": 137,
    "dplus": 133
   },
   {
    "date": "2026-06-28",
    "km": 9.9,
    "pace": "5:43",
    "paceSec": 343,
    "hr": 139,
    "dplus": 28
   },
   {
    "date": "2026-06-28",
    "km": 9.8,
    "pace": "7:44",
    "paceSec": 464,
    "hr": 126,
    "dplus": 71
   }
  ],
  "velo": [
   {
    "date": "2025-08-30",
    "min": 104,
    "w": 143,
    "hr": 154,
    "km": 42
   },
   {
    "date": "2025-09-28",
    "min": 252,
    "w": 125,
    "hr": 132,
    "km": 90
   },
   {
    "date": "2025-10-04",
    "min": 112,
    "w": 157,
    "hr": 142,
    "km": 46
   },
   {
    "date": "2025-10-12",
    "min": 410,
    "w": 128,
    "hr": 136,
    "km": 156
   },
   {
    "date": "2025-10-17",
    "min": 108,
    "w": 159,
    "hr": 143,
    "km": 46
   },
   {
    "date": "2025-12-14",
    "min": 152,
    "w": 119,
    "hr": 137,
    "km": 58
   },
   {
    "date": "2026-02-18",
    "min": 124,
    "w": 164,
    "hr": 121,
    "km": 28
   },
   {
    "date": "2026-02-21",
    "min": 119,
    "w": 169,
    "hr": 142,
    "km": 49
   },
   {
    "date": "2026-02-23",
    "min": 63,
    "w": 145,
    "hr": 113,
    "km": 31
   },
   {
    "date": "2026-02-23",
    "min": 81,
    "w": 156,
    "hr": 135,
    "km": 30
   },
   {
    "date": "2026-02-24",
    "min": 64,
    "w": 154,
    "hr": 117,
    "km": 31
   },
   {
    "date": "2026-03-02",
    "min": 76,
    "w": 178,
    "hr": 124,
    "km": 41
   },
   {
    "date": "2026-03-04",
    "min": 62,
    "w": 192,
    "hr": 128,
    "km": 33
   },
   {
    "date": "2026-03-14",
    "min": 63,
    "w": 201,
    "hr": 130,
    "km": 31
   },
   {
    "date": "2026-03-21",
    "min": 225,
    "w": 135,
    "hr": 131,
    "km": 87
   },
   {
    "date": "2026-03-31",
    "min": 62,
    "w": 205,
    "hr": 131,
    "km": 31
   },
   {
    "date": "2026-04-05",
    "min": 160,
    "w": 158,
    "hr": 140,
    "km": 59
   },
   {
    "date": "2026-04-05",
    "min": 80,
    "w": 116,
    "hr": 133,
    "km": 28
   },
   {
    "date": "2026-04-08",
    "min": 60,
    "w": 189,
    "hr": 128,
    "km": 28
   },
   {
    "date": "2026-05-02",
    "min": 71,
    "w": 156,
    "hr": 131,
    "km": 25
   },
   {
    "date": "2026-05-31",
    "min": 73,
    "w": 174,
    "hr": 141,
    "km": 32
   }
  ],
  "courseTrim": [
   {
    "trimestre": "2025-T3",
    "paceA140": "7:40",
    "n": 4
   },
   {
    "trimestre": "2025-T4",
    "paceA140": "6:46",
    "n": 12
   },
   {
    "trimestre": "2026-T1",
    "paceA140": "6:02",
    "n": 7
   },
   {
    "trimestre": "2026-T2",
    "paceA140": "5:52",
    "n": 8
   }
  ],
  "veloTrim": [
   {
    "trimestre": "2025-T3",
    "wA140": 131,
    "n": 2
   },
   {
    "trimestre": "2025-T4",
    "wA140": 141,
    "n": 4
   },
   {
    "trimestre": "2026-T1",
    "wA140": 187,
    "n": 10
   },
   {
    "trimestre": "2026-T2",
    "wA140": 165,
    "n": 5
   }
  ]
 },
 "lastActivityId": 19845461484,
 "coach": {
  "verdict": "Sur le fond, ton moteur est bon : l'allure normalisée à 140 bpm est passée de 7:40/km (T3 2025) à 5:52/km (T2 2026), et la puissance vélo à 140 bpm de 131 W à 165-187 W — ça, c'est du gain réel, pas du hasard. Le problème n'est pas l'efficacité, c'est la quantité : tu es passé de 33 h/mois en mars à 4,5 h en août, avec 20 jours off sur les 28 derniers. Ta reprise est engagée (4 séances cette semaine, ratio de charge 1,66) mais elle arrive sur un terrain fatigué : HRV à 34-40 avec statut LOW depuis le 18/08, FC de repos remontée à 53 contre 49-50 début août, readiness à 1, 12 et 25 sur les trois derniers jours. Bref : la machine sait rouler, elle est juste en train de se réveiller et il ne faut pas lui coller un coup de fouet tout de suite. La semaine à venir doit reconstruire le volume, pas chercher le chrono.",
  "forts": [
   "Efficacité course en nette progression : 5:52/km à 140 bpm au T2 2026 contre 7:40/km neuf mois plus tôt.",
   "Puissance vélo normalisée passée de 131 W à 165-187 W à FC égale sur un an.",
   "Le sommeil est solide : 8 h 17 la dernière nuit, moyenne 7 h 50 sur 7 nuits — c'est ton meilleur levier de récup et il est déjà en place.",
   "Tu as remis du CrossFit (65 min, RE 23 le 21/08) et du Pilates régulier : la base force/mobilité n'a jamais totalement disparu."
  ],
  "manques": [
   "Zéro vélo et zéro natation depuis juin : il faut réintroduire une sortie vélo par semaine dès maintenant, ne serait-ce qu'1 h facile.",
   "Pas de travail de force lourde tracé (squat/soulevé de terre/presse) — le CrossFit métabolique ne remplace pas 2 séances de charges lourdes pour un profil hybride.",
   "Régularité : 1,3 séance/semaine sur 4 semaines. L'objectif immédiat est 5 jours actifs/semaine, même courts, avant d'augmenter les durées.",
   "Aucune sortie longue depuis fin juin : il faut rebâtir une base aérobie de 60-75 min continue avant de reparler d'intensité."
  ],
  "vigilance": "HRV en statut LOW depuis 5 jours avec FC de repos +4 bpm et un ratio de charge à 1,66 : le risque n°1 des 10 prochains jours, c'est de forcer sur un corps désentraîné et de déclencher une tendinopathie d'Achille ou de genou — la progression doit se faire en fréquence, pas en intensité.",
  "semaine": {
   "titre": "Reconstruire la fréquence en aérobie facile, réintroduire vélo et force lourde légère",
   "volumeCible": "~4 h 15",
   "jours": [
    {
     "jour": "Lun",
     "ico": "🏃",
     "seance": "Course facile",
     "detail": "35 min en continu, FC 125-138 bpm max. Si l'allure dépasse 6:15/km, ralentis — c'est un jour de volume, pas de vitesse. Terrain plat, pas de D+.",
     "gardefou": "Si la FC dérive au-dessus de 145 sans accélérer, coupe à 25 min et rentre en marchant."
    },
    {
     "jour": "Mar",
     "ico": "🏋️",
     "seance": "Force — charges modérées",
     "detail": "Échauffement 10 min vélo/rameur. Puis 4×6 goblet squat ou back squat à ~60 % de ton max ressenti (tu dois pouvoir en faire 4 de plus), 4×8 soulevé de terre roumain léger, 3×8 tractions assistées ou ring rows, 3×10 gainage planche 40 s. Repos 2 min entre séries. 50 min au total.",
     "gardefou": "Aucune série à l'échec cette semaine. Si la technique se dégrade, la série s'arrête là."
    },
    {
     "jour": "Mer",
     "ico": "🧘",
     "seance": "Pilates + marche",
     "detail": "25 min Pilates (ta routine habituelle) + 20 min de marche rapide dehors. Objectif : circulation et mobilité hanches/chevilles après le squat.",
     "gardefou": "Si les jambes sont très raides, remplace la marche par 10 min d'étirements chaîne postérieure."
    },
    {
     "jour": "Jeu",
     "ico": "🚴",
     "seance": "Vélo facile — réintroduction",
     "detail": "50 min, FC 120-135 bpm, cadence 85-95 rpm. Home-trainer ou route plate. Objectif : réhabituer les jambes au geste, pas produire des watts. Vise 130-150 W max.",
     "gardefou": "Zéro effort en côte ou en danseuse. Si tu n'as pas de vélo dispo, remplace par 40 min de marche rapide en côte."
    },
    {
     "jour": "Ven",
     "ico": "🏋️",
     "seance": "CrossFit en box",
     "detail": "Séance normale du vendredi. Une seule consigne : sur le WOD, vise 75-80 % de ton allure de compétition et garde 2 répétitions en réserve sur les mouvements lourds. Tes 65 min du 21/08 à RE 23 sont un bon calibrage — reste dans cette zone.",
     "gardefou": "Si le WOD contient des mouvements à haut impact répétés (double-unders volume, box jumps > 50), scale en step-ups — tes tendons n'ont pas revu de volume depuis juin."
    },
    {
     "jour": "Sam",
     "ico": "🏃",
     "seance": "Sortie longue facile",
     "detail": "55 min de course très facile, FC < 140 bpm, allure libre autour de 6:00-6:30/km. Si ça devient dur après 40 min, passe en course/marche 5 min / 1 min. C'est la séance la plus importante de la semaine.",
     "gardefou": "Douleur au tendon d'Achille ou au genou qui monte au-dessus de 3/10 : tu t'arrêtes, point."
    },
    {
     "jour": "Dim",
     "ico": "😴",
     "seance": "Repos complet",
     "detail": "Rien. Batch cooking et marche tranquille si tu veux bouger, pas plus.",
     "gardefou": "Repos réel — pas de « petite séance » improvisée."
    }
   ]
  },
  "regle": "Si la semaine déborde, tu sautes le Pilates du mercredi en premier, puis le vélo du jeudi ; tu ne sautes jamais la sortie longue facile du samedi — c'est elle qui reconstruit la base que tu as perdue.",
  "nutrition": {
   "principe": "Objectif : 125-140 g de protéines par jour (1,6-1,8 g/kg pour tes 77,5 kg), réparties en 4 prises d'environ 30-35 g — c'est la répartition qui compte pour reconstruire du muscle, pas le total avalé le soir. Les glucides se concentrent sur les jours force (mardi, vendredi) et la veille de la sortie longue (vendredi soir) : une grosse portion de riz ou de patate douce au dîner, environ 2 poings. Les jours repos et Pilates, tu réduis les féculents à 1 poing et tu remplis l'assiette de légumes — sans jamais toucher aux protéines. Pas de comptage : tu te cales sur les portions (1 paume de protéine, 1 à 2 poings de féculent, la moitié de l'assiette en légumes).",
   "batch": [
    "Cuire 1 kg de filets de poulet marinés au four → 5 portions de 200 g, 4 jours au frigo (congeler 2 portions dès dimanche soir).",
    "Cuire 500 g de riz basmati cru → environ 1,5 kg cuit, 6 portions, 4 jours au frigo en boîte hermétique.",
    "Cuire 300 g de lentilles vertes crues → environ 750 g cuites, 4 portions, 5 jours au frigo.",
    "Rôtir 1,5 kg de légumes au four (courgettes, poivrons, patate douce, oignon rouge) → 6 portions, 4 jours au frigo.",
    "Cuire 12 œufs durs → 4 jours au frigo, non écalés.",
    "Préparer 500 g de sauce yaourt-citron-herbes → 5 jours au frigo dans un pot fermé.",
    "Façonner 12 boulettes de bœuf crues (500 g) → 2 dîners, 2 jours au frigo ou congelées crues."
   ],
   "recettes": [
    {
     "nom": "Poulet mariné au four",
     "usage": "Batch dimanche — base de 5 repas",
     "portions": "5 portions de 200 g",
     "temps": "10 min prépa + 25 min four",
     "ingredients": [
      "1 kg de filets de poulet",
      "3 cuillères à soupe d'huile d'olive",
      "2 gousses d'ail écrasées",
      "1 cuillère à café de paprika",
      "1 cuillère à café de cumin",
      "1 cuillère à café d'herbes de Provence",
      "le jus d'1 citron",
      "1 cuillère à café de sel",
      "poivre"
     ],
     "etapes": [
      "Préchauffe le four à 200 °C (chaleur tournante).",
      "Dans un grand saladier, mélange l'huile, l'ail, le paprika, le cumin, les herbes, le jus de citron, le sel et le poivre.",
      "Ajoute les filets de poulet et retourne-les à la main pour qu'ils soient tous enrobés. Laisse 10 min pendant que le four chauffe.",
      "Étale les filets sur une plaque recouverte de papier cuisson, sans qu'ils se chevauchent.",
      "Enfourne 22 à 25 min. Le poulet est cuit quand la chair est blanche jusqu'au centre (coupe le plus gros filet en deux pour vérifier : plus aucune trace rosée) et que le jus qui sort est translucide.",
      "Laisse tiédir 15 min à l'air libre, puis coupe en lanières et répartis dans 5 boîtes."
     ],
     "conservation": "4 jours au frigo. Se congèle très bien en portions individuelles."
    },
    {
     "nom": "Riz basmati batch",
     "usage": "Batch dimanche — base féculents",
     "portions": "6 portions",
     "temps": "2 min prépa + 12 min cuisson",
     "ingredients": [
      "500 g de riz basmati cru",
      "1 litre d'eau",
      "1 cuillère à café de sel"
     ],
     "etapes": [
      "Rince le riz sous l'eau froide dans une passoire jusqu'à ce que l'eau ressorte à peu près claire (environ 30 secondes).",
      "Verse le riz, l'eau et le sel dans une casserole. Porte à ébullition à feu vif, sans couvercle.",
      "Dès que ça bout, baisse au minimum, couvre et laisse 11 min sans jamais soulever le couvercle.",
      "Coupe le feu et laisse reposer 5 min à couvert. Le riz est prêt quand toute l'eau est absorbée et que les grains se détachent à la fourchette.",
      "Aère à la fourchette, laisse refroidir 20 min à découvert (important pour la conservation), puis mets en boîtes."
     ],
     "conservation": "4 jours au frigo en boîte hermétique. Se congèle."
    },
    {
     "nom": "Lentilles vertes batch",
     "usage": "Batch dimanche — boîtes chantier",
     "portions": "4 portions",
     "temps": "3 min prépa + 25 min cuisson",
     "ingredients": [
      "300 g de lentilles vertes crues",
      "1,2 litre d'eau",
      "1 oignon rouge coupé en deux",
      "1 feuille de laurier",
      "1 cuillère à café de sel (à la fin)"
     ],
     "etapes": [
      "Rince les lentilles à l'eau froide dans une passoire.",
      "Mets-les dans une casserole avec l'eau froide, l'oignon coupé en deux et le laurier. Ne sale pas maintenant.",
      "Porte à ébullition puis baisse à feu doux et laisse frémir 22 à 25 min, à demi-couvert.",
      "Goûte une lentille : elle doit être tendre mais garder une légère résistance sous la dent, sans être en purée.",
      "Sale, égoutte, retire l'oignon et le laurier. Laisse refroidir 20 min avant de mettre en boîte."
     ],
     "conservation": "5 jours au frigo."
    },
    {
     "nom": "Légumes rôtis au four",
     "usage": "Batch dimanche — accompagne dîners et boîtes",
     "portions": "6 portions",
     "temps": "15 min prépa + 35 min four",
     "ingredients": [
      "3 courgettes",
      "3 poivrons (rouge/jaune)",
      "800 g de patate douce",
      "1 oignon rouge",
      "4 cuillères à soupe d'huile d'olive",
      "2 cuillères à café d'herbes de Provence",
      "sel, poivre"
     ],
     "etapes": [
      "Préchauffe le four à 200 °C.",
      "Lave les courgettes et les poivrons. Coupe les courgettes en rondelles épaisses de 1,5 cm, les poivrons en lanières, l'oignon en quartiers.",
      "Épluche la patate douce et coupe-la en cubes de 2 cm (plus petits que le reste, elle cuit moins vite).",
      "Mets tout dans un grand saladier, verse l'huile, les herbes, sel et poivre, et mélange à la main.",
      "Étale sur deux plaques (ne surcharge pas, sinon ça cuit à la vapeur au lieu de rôtir).",
      "Enfourne 35 min en remuant à mi-cuisson. C'est prêt quand les bords sont dorés et qu'un couteau traverse un cube de patate douce sans résistance.",
      "Laisse tiédir 20 min avant de mettre en boîtes."
     ],
     "conservation": "4 jours au frigo. Se mangent froids ou tièdes."
    },
    {
     "nom": "Œufs durs",
     "usage": "Batch dimanche — collations et boîtes chantier",
     "portions": "12 œufs",
     "temps": "1 min prépa + 10 min cuisson",
     "ingredients": [
      "12 œufs"
     ],
     "etapes": [
      "Sors les œufs du frigo 10 min avant (limite la casse).",
      "Porte une grande casserole d'eau à ébullition franche.",
      "Dépose les œufs délicatement à la cuillère et compte 10 min à petits bouillons.",
      "Égoutte et plonge immédiatement dans un saladier d'eau très froide pendant 5 min : c'est ce qui rend l'écalage facile.",
      "Sèche et range au frigo sans les écaler."
     ],
     "conservation": "4 jours au frigo, coquille intacte."
    },
    {
     "nom": "Sauce yaourt-citron-herbes",
     "usage": "Batch dimanche — assaisonne toutes les boîtes chantier",
     "portions": "environ 500 g, 7 usages",
     "temps": "5 min",
     "ingredients": [
      "400 g de yaourt grec",
      "le jus d'1 citron",
      "1 gousse d'ail écrasée",
      "2 cuillères à soupe d'huile d'olive",
      "1 cuillère à café de moutarde",
      "sel, poivre"
     ],
     "etapes": [
      "Verse le yaourt grec dans un bol.",
      "Ajoute le jus de citron, l'ail écrasé, l'huile d'olive et la moutarde.",
      "Fouette 30 secondes à la fourchette jusqu'à obtenir une texture lisse et coulante (si c'est trop épais, ajoute 1 cuillère à soupe d'eau).",
      "Sale, poivre, goûte et ajuste le citron.",
      "Transvase dans un pot à couvercle."
     ],
     "conservation": "5 jours au frigo."
    },
    {
     "nom": "Boîte chantier poulet-riz-légumes",
     "usage": "Boîte chantier lundi, mardi, jeudi — assemblage la veille au soir",
     "portions": "1 boîte, à répéter",
     "temps": "5 min d'assemblage",
     "ingredients": [
      "200 g de poulet mariné du batch",
      "1 grosse louche de riz batch (environ 200 g cuit)",
      "2 grosses cuillères de légumes rôtis",
      "2 cuillères à soupe de sauce yaourt-citron",
      "une poignée de tomates cerises"
     ],
     "etapes": [
      "Sors les boîtes du batch du frigo.",
      "Dans une boîte hermétique, mets le riz au fond, les légumes rôtis par-dessus, puis le poulet en lanières.",
      "Ajoute les tomates cerises coupées en deux.",
      "Mets la sauce dans un petit pot à part (elle détrempe si tu la mélanges la veille) ou verse-la directement si tu manges dans les 12 h.",
      "Ferme et mets au frigo. Ça se mange froid ou tiède, sans réchauffage."
     ],
     "conservation": "Assemblée la veille, à consommer dans les 24 h."
    },
    {
     "nom": "Boîte chantier lentilles-œufs",
     "usage": "Boîte chantier mercredi et vendredi — se mange froide",
     "portions": "1 boîte, à répéter",
     "temps": "5 min d'assemblage",
     "ingredients": [
      "1 grosse louche de lentilles du batch (environ 190 g cuites)",
      "2 œufs durs du batch",
      "2 cuillères de légumes rôtis",
      "1 poignée d'épinards frais",
      "2 cuillères à soupe de sauce yaourt-citron",
      "1 cuillère à soupe d'amandes"
     ],
     "etapes": [
      "Mets les lentilles au fond de la boîte.",
      "Ajoute les légumes rôtis et les épinards frais par-dessus.",
      "Écale les 2 œufs durs, coupe-les en deux et pose-les sur le dessus.",
      "Ajoute les amandes concassées grossièrement.",
      "Sauce dans un pot à part. Ferme et frigo."
     ],
     "conservation": "Assemblée la veille, à consommer dans les 24 h."
    },
    {
     "nom": "Boulettes de bœuf sauce tomate",
     "usage": "Dîner mardi (jour force) — cuisson 18 min",
     "portions": "2 dîners (12 boulettes)",
     "temps": "10 min prépa + 18 min cuisson",
     "ingredients": [
      "500 g de bœuf haché 5 %",
      "1 œuf",
      "1 gousse d'ail écrasée",
      "1 cuillère à café de cumin",
      "sel, poivre",
      "1 cuillère à soupe d'huile d'olive",
      "1 boîte de 400 g de tomates concassées",
      "1 cuillère à café d'herbes de Provence"
     ],
     "etapes": [
      "Dans un saladier, mélange à la main le bœuf haché, l'œuf, l'ail, le cumin, du sel et du poivre, jusqu'à ce que ce soit homogène.",
      "Forme 12 boulettes de la taille d'une balle de golf en roulant entre les paumes.",
      "Chauffe l'huile dans une poêle à feu moyen-vif. Dépose les boulettes sans les coller et laisse-les dorer 2 min par face sans y toucher (elles doivent se décoller toutes seules quand elles sont dorées).",
      "Verse les tomates concassées et les herbes, sale légèrement, baisse à feu doux.",
      "Couvre et laisse mijoter 12 min. C'est prêt quand la sauce a épaissi et qu'une boulette coupée en deux n'est plus rosée au centre.",
      "Sers avec 2 poings de riz du batch réchauffé 90 secondes à la poêle avec une cuillère d'eau."
     ],
     "conservation": "2 jours au frigo. Se congèle cuit."
    },
    {
     "nom": "Poêlée poulet-légumes express",
     "usage": "Dîner lundi et jeudi — 10 min",
     "portions": "1 portion",
     "temps": "10 min",
     "ingredients": [
      "200 g de poulet du batch",
      "2 grosses cuillères de légumes rôtis du batch",
      "1 poignée d'épinards frais",
      "1 louche de riz du batch (jour endurance) ou rien (jour léger)",
      "1 cuillère à soupe d'huile d'olive",
      "poivre"
     ],
     "etapes": [
      "Chauffe l'huile dans une poêle à feu moyen.",
      "Jette les légumes rôtis et le poulet coupé en lanières, remue 4 min jusqu'à ce que ce soit bien chaud et que les bords recolorent.",
      "Ajoute le riz si c'est un jour à glucides, remue 2 min de plus.",
      "Coupe le feu, jette les épinards frais et remue 30 secondes : ils doivent juste tomber, pas cuire.",
      "Poivre et sers."
     ],
     "conservation": "À manger immédiatement."
    },
    {
     "nom": "Omelette épinards-feta",
     "usage": "Dîner mercredi (jour léger) — 12 min",
     "portions": "1 portion",
     "temps": "12 min",
     "ingredients": [
      "3 œufs",
      "80 g d'épinards frais",
      "50 g de feta émiettée",
      "1 cuillère à soupe d'huile d'olive",
      "sel, poivre",
      "1 tranche de pain complet"
     ],
     "etapes": [
      "Bats les 3 œufs à la fourchette dans un bol avec une pincée de sel et du poivre, 20 secondes.",
      "Chauffe l'huile dans une poêle antiadhésive à feu moyen. Jette les épinards et remue 2 min jusqu'à ce qu'ils soient tombés et que l'eau se soit évaporée.",
      "Verse les œufs par-dessus, étale, puis parsème la feta émiettée.",
      "Laisse cuire 4 à 5 min à feu moyen-doux : le dessous doit être pris et doré, le dessus encore légèrement brillant.",
      "Replie en deux avec une spatule, laisse 1 min de plus et sers avec le pain complet."
     ],
     "conservation": "À manger immédiatement."
    },
    {
     "nom": "Saumon poêlé et légumes rôtis",
     "usage": "Dîner vendredi (veille sortie longue) — 12 min",
     "portions": "1 portion",
     "temps": "12 min",
     "ingredients": [
      "1 pavé de saumon de 130 g",
      "3 grosses cuillères de légumes rôtis du batch",
      "1 grosse louche de riz du batch",
      "1 cuillère à soupe d'huile d'olive",
      "un demi-citron",
      "sel, poivre"
     ],
     "etapes": [
      "Sèche le pavé de saumon avec du papier absorbant, sale et poivre les deux faces.",
      "Chauffe l'huile dans une poêle à feu moyen-vif. Quand elle est bien chaude, pose le saumon côté peau et laisse 5 min sans y toucher : la peau doit devenir croustillante et la chair blanchir sur le premier tiers.",
      "Retourne et laisse 3 min. Le saumon est cuit quand la chair s'ouvre en lamelles sous la fourchette tout en restant légèrement rosée au cœur.",
      "Pendant ce temps, réchauffe les légumes et le riz 2 min dans une seconde poêle avec une cuillère d'eau.",
      "Sers avec un filet de citron pressé."
     ],
     "conservation": "À manger immédiatement."
    }
   ],
   "courses": [
    {
     "rayon": "Protéines",
     "items": [
      "1 kg de filets de poulet",
      "500 g de bœuf haché 5 %",
      "2 pavés de saumon (environ 260 g)",
      "2 boîtes de thon au naturel (140 g)"
     ]
    },
    {
     "rayon": "Féculents & légumineuses",
     "items": [
      "1 paquet de riz basmati 1 kg",
      "1 paquet de lentilles vertes 500 g",
      "1 paquet de flocons d'avoine 500 g",
      "1 pain complet en tranches"
     ]
    },
    {
     "rayon": "Légumes & fruits",
     "items": [
      "3 courgettes",
      "3 poivrons",
      "800 g de patate douce",
      "3 oignons rouges",
      "1 barquette de tomates cerises 500 g",
      "2 sachets d'épinards frais (2 × 125 g)",
      "1 tête d'ail",
      "2 citrons",
      "6 bananes",
      "4 pommes"
     ]
    },
    {
     "rayon": "Produits laitiers & œufs",
     "items": [
      "3 boîtes de 12 œufs (36 œufs)",
      "1 pot de yaourt grec 1 kg",
      "1 bloc de feta 200 g",
      "1 pot de fromage blanc 500 g"
     ]
    },
    {
     "rayon": "Épicerie",
     "items": [
      "1 bouteille d'huile d'olive",
      "2 boîtes de tomates concassées 400 g",
      "1 pot de moutarde",
      "paprika, cumin, herbes de Provence, laurier",
      "1 sachet d'amandes 200 g",
      "1 pot de miel"
     ]
    }
   ],
   "jours": [
    {
     "jour": "Lun",
     "type": "Endurance facile (course 35 min)",
     "petitDej": "Habituel (3 œufs à la coque, 500 ml d'eau, vitamine D + K1 + complexe B)",
     "dejeuner": "Boîte chantier poulet-riz-légumes : 200 g de poulet, 1 poing de riz, légumes rôtis, tomates cerises, sauce yaourt en pot à part — se mange froide",
     "collation": "Après la course : 1 banane + 150 g de fromage blanc",
     "diner": "Poêlée poulet-légumes express avec 1 poing de riz + grande poignée d'épinards"
    },
    {
     "jour": "Mar",
     "type": "Jour force (charges modérées)",
     "petitDej": "Habituel + 1 banane et 40 g de flocons d'avoine (séance de force dans la journée, tu as besoin de glucides disponibles)",
     "dejeuner": "Boîte chantier poulet-riz-légumes (2 poings de riz aujourd'hui) + 1 pomme",
     "collation": "Après la séance de force : 2 œufs durs + 1 banane dans les 45 min",
     "diner": "Boulettes de bœuf sauce tomate + 2 poings de riz du batch + légumes rôtis — c'est le repas le plus copieux de la semaine"
    },
    {
     "jour": "Mer",
     "type": "Jour léger (Pilates + marche)",
     "petitDej": "Habituel",
     "dejeuner": "Boîte chantier lentilles-œufs : lentilles, 2 œufs durs, légumes rôtis, épinards, amandes, sauce à part",
     "collation": "1 pomme + 1 poignée d'amandes",
     "diner": "Omelette épinards-feta (3 œufs) + 1 tranche de pain complet + grande salade — assiette légère, légumes dominants"
    },
    {
     "jour": "Jeu",
     "type": "Endurance facile (vélo 50 min)",
     "petitDej": "Habituel",
     "dejeuner": "Boîte chantier poulet-riz-légumes (1,5 poing de riz) + 1 yaourt grec",
     "collation": "Avant le vélo si tu roules le soir : 1 banane 30 min avant",
     "diner": "Poêlée poulet-légumes express avec 1 poing de riz + épinards frais"
    },
    {
     "jour": "Ven",
     "type": "Jour force (CrossFit box) + veille de sortie longue",
     "petitDej": "Habituel + 1 banane et 40 g de flocons d'avoine (WOD dans la journée)",
     "dejeuner": "Boîte chantier lentilles-œufs + 1 tranche de pain complet",
     "collation": "Après le WOD : reste de poulet du batch (150 g) + 1 banane",
     "diner": "Saumon poêlé + légumes rôtis + 2 poings de riz — on charge les glucides pour la sortie longue de demain matin"
    },
    {
     "jour": "Sam",
     "type": "Sortie longue facile (course 55 min)",
     "petitDej": "Habituel + 1 tranche de pain complet avec du miel, 45 min avant de partir (c'est la seule séance longue, tu as besoin d'un peu de sucre en réserve)",
     "dejeuner": "Assiette maison : 2 boîtes de thon égouttées + reste de riz + légumes rôtis + sauce yaourt-citron",
     "collation": "Dans l'heure après la course : 1 banane + 200 g de yaourt grec",
     "diner": "Boulettes de bœuf sauce tomate (2e portion) + légumes rôtis + 1 poing de riz"
    },
    {
     "jour": "Dim",
     "type": "Repos complet + batch cooking",
     "petitDej": "Habituel",
     "dejeuner": "Grande salade composée : épinards, tomates cerises, 2 œufs durs restants, feta, amandes, huile d'olive et citron",
     "collation": "—",
     "diner": "Assiette légère pendant le batch : reste de légumes rôtis + 1 pavé de saumon ou 150 g de poulet frais, pas de féculent"
    }
   ]
  },
  "generatedAt": "2026-08-22T13:35:14.381Z",
  "semaineLabel": "2026-S35"
 }
};
