// AUTO-GENERATED by scripts/bilan.js — 2026-08-29T16:00:22.486Z
// Ne pas éditer : relancer sync.command.
window.BILAN = {
 "generatedAt": "2026-08-29T16:00:22.486Z",
 "mois": [
  {
   "key": "2025-09",
   "label": "sept. 25",
   "h": 38.3,
   "n": 38,
   "jours": 27,
   "re": 741,
   "disc": {
    "nat": {
     "h": 0,
     "km": 0,
     "n": 0
    },
    "velo": {
     "h": 4.2,
     "km": 90,
     "n": 1
    },
    "run": {
     "h": 5.9,
     "km": 52,
     "n": 4
    },
    "autre": {
     "h": 28.1,
     "km": 54,
     "n": 33
    }
   },
   "types": {
    "Pilates": 23,
    "Run": 4,
    "Hike": 2,
    "WeightTraining": 5,
    "EMountainBikeRide": 3,
    "Ride": 1
   }
  },
  {
   "key": "2025-10",
   "label": "oct. 25",
   "h": 33.3,
   "n": 29,
   "jours": 25,
   "re": 827,
   "disc": {
    "nat": {
     "h": 0,
     "km": 0,
     "n": 0
    },
    "velo": {
     "h": 10.5,
     "km": 247,
     "n": 3
    },
    "run": {
     "h": 5.2,
     "km": 34,
     "n": 2
    },
    "autre": {
     "h": 17.6,
     "km": 32,
     "n": 24
    }
   },
   "types": {
    "Pilates": 22,
    "Ride": 3,
    "HighIntensityIntervalTraining": 1,
    "EMountainBikeRide": 1,
    "TrailRun": 1,
    "Run": 1
   }
  },
  {
   "key": "2025-11",
   "label": "nov. 25",
   "h": 30.8,
   "n": 31,
   "jours": 24,
   "re": 821,
   "disc": {
    "nat": {
     "h": 0.1,
     "km": 0,
     "n": 1
    },
    "velo": {
     "h": 0.3,
     "km": 6,
     "n": 1
    },
    "run": {
     "h": 9.8,
     "km": 91,
     "n": 8
    },
    "autre": {
     "h": 20.6,
     "km": 104,
     "n": 21
    }
   },
   "types": {
    "Pilates": 15,
    "Run": 8,
    "Hike": 1,
    "EMountainBikeRide": 3,
    "HighIntensityIntervalTraining": 2,
    "Ride": 1,
    "Swim": 1
   }
  },
  {
   "key": "2025-12",
   "label": "déc. 25",
   "h": 23.4,
   "n": 24,
   "jours": 22,
   "re": 504,
   "disc": {
    "nat": {
     "h": 0.6,
     "km": 1,
     "n": 2
    },
    "velo": {
     "h": 2.8,
     "km": 58,
     "n": 2
    },
    "run": {
     "h": 9.5,
     "km": 91,
     "n": 8
    },
    "autre": {
     "h": 10.5,
     "km": 18,
     "n": 12
    }
   },
   "types": {
    "Run": 8,
    "Pilates": 11,
    "EMountainBikeRide": 1,
    "Ride": 2,
    "Swim": 2
   }
  },
  {
   "key": "2026-01",
   "label": "janv. 26",
   "h": 29.6,
   "n": 40,
   "jours": 27,
   "re": 917,
   "disc": {
    "nat": {
     "h": 1.3,
     "km": 4,
     "n": 5
    },
    "velo": {
     "h": 0.7,
     "km": 0,
     "n": 1
    },
    "run": {
     "h": 11.3,
     "km": 118,
     "n": 13
    },
    "autre": {
     "h": 16.3,
     "km": 15,
     "n": 21
    }
   },
   "types": {
    "Run": 13,
    "Pilates": 13,
    "Swim": 5,
    "HighIntensityIntervalTraining": 7,
    "EMountainBikeRide": 1,
    "Ride": 1
   }
  },
  {
   "key": "2026-02",
   "label": "févr. 26",
   "h": 30.2,
   "n": 39,
   "jours": 23,
   "re": 1003,
   "disc": {
    "nat": {
     "h": 3,
     "km": 8,
     "n": 8
    },
    "velo": {
     "h": 10.3,
     "km": 224,
     "n": 9
    },
    "run": {
     "h": 5.3,
     "km": 55,
     "n": 8
    },
    "autre": {
     "h": 11.6,
     "km": 15,
     "n": 14
    }
   },
   "types": {
    "Swim": 8,
    "Pilates": 8,
    "EMountainBikeRide": 1,
    "Run": 8,
    "HighIntensityIntervalTraining": 3,
    "Ride": 4,
    "Workout": 2,
    "VirtualRide": 5
   }
  },
  {
   "key": "2026-03",
   "label": "mars 26",
   "h": 33.1,
   "n": 34,
   "jours": 23,
   "re": 920,
   "disc": {
    "nat": {
     "h": 3.1,
     "km": 7,
     "n": 7
    },
    "velo": {
     "h": 13.8,
     "km": 403,
     "n": 14
    },
    "run": {
     "h": 5.3,
     "km": 53,
     "n": 4
    },
    "autre": {
     "h": 11,
     "km": 29,
     "n": 9
    }
   },
   "types": {
    "VirtualRide": 13,
    "Pilates": 7,
    "Run": 4,
    "Swim": 7,
    "Hike": 2,
    "Ride": 1
   }
  },
  {
   "key": "2026-04",
   "label": "avr. 26",
   "h": 20.1,
   "n": 28,
   "jours": 18,
   "re": 788,
   "disc": {
    "nat": {
     "h": 1.4,
     "km": 3,
     "n": 3
    },
    "velo": {
     "h": 9,
     "km": 236,
     "n": 8
    },
    "run": {
     "h": 5.3,
     "km": 57,
     "n": 7
    },
    "autre": {
     "h": 4.4,
     "km": 0,
     "n": 10
    }
   },
   "types": {
    "Run": 7,
    "VirtualRide": 6,
    "Pilates": 8,
    "Swim": 3,
    "Ride": 2,
    "HighIntensityIntervalTraining": 1,
    "Workout": 1
   }
  },
  {
   "key": "2026-05",
   "label": "mai 26",
   "h": 17.2,
   "n": 28,
   "jours": 18,
   "re": 367,
   "disc": {
    "nat": {
     "h": 1.8,
     "km": 4,
     "n": 3
    },
    "velo": {
     "h": 4,
     "km": 106,
     "n": 5
    },
    "run": {
     "h": 2.8,
     "km": 29,
     "n": 5
    },
    "autre": {
     "h": 8.6,
     "km": 15,
     "n": 15
    }
   },
   "types": {
    "VirtualRide": 3,
    "Pilates": 12,
    "Run": 5,
    "Ride": 2,
    "Swim": 3,
    "EMountainBikeRide": 1,
    "Workout": 2
   }
  },
  {
   "key": "2026-06",
   "label": "juin 26",
   "h": 8.4,
   "n": 15,
   "jours": 13,
   "re": 177,
   "disc": {
    "nat": {
     "h": 0.9,
     "km": 2,
     "n": 2
    },
    "velo": {
     "h": 0,
     "km": 0,
     "n": 0
    },
    "run": {
     "h": 3.8,
     "km": 37,
     "n": 5
    },
    "autre": {
     "h": 3.7,
     "km": 0,
     "n": 8
    }
   },
   "types": {
    "Run": 5,
    "Pilates": 8,
    "Swim": 2
   }
  },
  {
   "key": "2026-07",
   "label": "juil. 26",
   "h": 5.3,
   "n": 11,
   "jours": 10,
   "re": 106,
   "disc": {
    "nat": {
     "h": 0,
     "km": 0,
     "n": 0
    },
    "velo": {
     "h": 0,
     "km": 0,
     "n": 0
    },
    "run": {
     "h": 1.4,
     "km": 14,
     "n": 3
    },
    "autre": {
     "h": 3.8,
     "km": 0,
     "n": 8
    }
   },
   "types": {
    "Pilates": 8,
    "Run": 3
   }
  },
  {
   "key": "2026-08",
   "label": "août 26",
   "h": 15,
   "n": 19,
   "jours": 13,
   "re": 404,
   "disc": {
    "nat": {
     "h": 0.4,
     "km": 1,
     "n": 2
    },
    "velo": {
     "h": 0.9,
     "km": 27,
     "n": 1
    },
    "run": {
     "h": 6,
     "km": 56,
     "n": 7
    },
    "autre": {
     "h": 7.6,
     "km": 0,
     "n": 9
    }
   },
   "types": {
    "Pilates": 4,
    "Run": 7,
    "Workout": 5,
    "VirtualRide": 1,
    "Swim": 2
   }
  }
 ],
 "total": {
  "h": 284.7,
  "n": 336,
  "jours": 243
 },
 "efficacite": {
  "course": [
   {
    "date": "2025-08-31",
    "km": 12.8,
    "pace": "7:35",
    "paceSec": 455,
    "hr": 132,
    "dplus": 63
   },
   {
    "date": "2025-09-05",
    "km": 13.6,
    "pace": "6:14",
    "paceSec": 374,
    "hr": 143,
    "dplus": 116
   },
   {
    "date": "2025-09-13",
    "km": 14.9,
    "pace": "7:51",
    "paceSec": 471,
    "hr": 123,
    "dplus": 120
   },
   {
    "date": "2025-09-21",
    "km": 15.2,
    "pace": "6:58",
    "paceSec": 418,
    "hr": 129,
    "dplus": 136
   },
   {
    "date": "2025-10-25",
    "km": 20.1,
    "pace": "11:28",
    "paceSec": 688,
    "hr": 127,
    "dplus": 920
   },
   {
    "date": "2025-10-28",
    "km": 14.2,
    "pace": "5:44",
    "paceSec": 344,
    "hr": 149,
    "dplus": 139
   },
   {
    "date": "2025-11-09",
    "km": 19.5,
    "pace": "6:59",
    "paceSec": 419,
    "hr": 147,
    "dplus": 555
   },
   {
    "date": "2025-11-17",
    "km": 8.2,
    "pace": "6:02",
    "paceSec": 362,
    "hr": 153,
    "dplus": 105
   },
   {
    "date": "2025-11-18",
    "km": 9.9,
    "pace": "6:00",
    "paceSec": 360,
    "hr": 139,
    "dplus": 106
   },
   {
    "date": "2025-11-19",
    "km": 8.2,
    "pace": "6:08",
    "paceSec": 368,
    "hr": 165,
    "dplus": 111
   },
   {
    "date": "2025-11-21",
    "km": 21,
    "pace": "6:47",
    "paceSec": 407,
    "hr": 128,
    "dplus": 235
   },
   {
    "date": "2025-11-29",
    "km": 14,
    "pace": "5:47",
    "paceSec": 347,
    "hr": 141,
    "dplus": 105
   },
   {
    "date": "2025-12-04",
    "km": 17.9,
    "pace": "6:19",
    "paceSec": 379,
    "hr": 133,
    "dplus": 86
   },
   {
    "date": "2025-12-13",
    "km": 17.9,
    "pace": "6:43",
    "paceSec": 403,
    "hr": 127,
    "dplus": 159
   },
   {
    "date": "2025-12-25",
    "km": 16.6,
    "pace": "6:34",
    "paceSec": 394,
    "hr": 133,
    "dplus": 100
   },
   {
    "date": "2025-12-28",
    "km": 11.7,
    "pace": "5:36",
    "paceSec": 336,
    "hr": 141,
    "dplus": 84
   },
   {
    "date": "2026-01-01",
    "km": 27.6,
    "pace": "5:47",
    "paceSec": 347,
    "hr": 129,
    "dplus": 235
   },
   {
    "date": "2026-01-10",
    "km": 11.6,
    "pace": "5:01",
    "paceSec": 301,
    "hr": 167,
    "dplus": 117
   },
   {
    "date": "2026-01-24",
    "km": 13.1,
    "pace": "5:52",
    "paceSec": 352,
    "hr": 146,
    "dplus": 111
   },
   {
    "date": "2026-01-29",
    "km": 14,
    "pace": "5:49",
    "paceSec": 349,
    "hr": 135,
    "dplus": 95
   },
   {
    "date": "2026-03-06",
    "km": 13.3,
    "pace": "5:13",
    "paceSec": 313,
    "hr": 148,
    "dplus": 92
   },
   {
    "date": "2026-03-07",
    "km": 11.7,
    "pace": "7:42",
    "paceSec": 462,
    "hr": 118,
    "dplus": 81
   },
   {
    "date": "2026-03-23",
    "km": 21.1,
    "pace": "5:48",
    "paceSec": 348,
    "hr": 135,
    "dplus": 144
   },
   {
    "date": "2026-04-01",
    "km": 10.4,
    "pace": "5:53",
    "paceSec": 353,
    "hr": 137,
    "dplus": 130
   },
   {
    "date": "2026-04-10",
    "km": 8.4,
    "pace": "5:09",
    "paceSec": 309,
    "hr": 144,
    "dplus": 87
   },
   {
    "date": "2026-04-12",
    "km": 10,
    "pace": "5:17",
    "paceSec": 317,
    "hr": 153,
    "dplus": 58
   },
   {
    "date": "2026-04-30",
    "km": 10.2,
    "pace": "5:30",
    "paceSec": 330,
    "hr": 144,
    "dplus": 72
   },
   {
    "date": "2026-05-01",
    "km": 11,
    "pace": "5:38",
    "paceSec": 338,
    "hr": 141,
    "dplus": 99
   },
   {
    "date": "2026-06-03",
    "km": 10.1,
    "pace": "5:37",
    "paceSec": 337,
    "hr": 137,
    "dplus": 133
   },
   {
    "date": "2026-06-28",
    "km": 9.9,
    "pace": "5:43",
    "paceSec": 343,
    "hr": 139,
    "dplus": 28
   },
   {
    "date": "2026-06-28",
    "km": 9.8,
    "pace": "7:44",
    "paceSec": 464,
    "hr": 126,
    "dplus": 71
   },
   {
    "date": "2026-08-26",
    "km": 12.2,
    "pace": "6:27",
    "paceSec": 387,
    "hr": 130,
    "dplus": 86
   },
   {
    "date": "2026-08-28",
    "km": 13.8,
    "pace": "7:10",
    "paceSec": 430,
    "hr": 125,
    "dplus": 122
   }
  ],
  "velo": [
   {
    "date": "2025-08-30",
    "min": 104,
    "w": 143,
    "hr": 154,
    "km": 42
   },
   {
    "date": "2025-09-28",
    "min": 252,
    "w": 125,
    "hr": 132,
    "km": 90
   },
   {
    "date": "2025-10-04",
    "min": 112,
    "w": 157,
    "hr": 142,
    "km": 46
   },
   {
    "date": "2025-10-12",
    "min": 410,
    "w": 128,
    "hr": 136,
    "km": 156
   },
   {
    "date": "2025-10-17",
    "min": 108,
    "w": 159,
    "hr": 143,
    "km": 46
   },
   {
    "date": "2025-12-14",
    "min": 152,
    "w": 119,
    "hr": 137,
    "km": 58
   },
   {
    "date": "2026-02-18",
    "min": 124,
    "w": 164,
    "hr": 121,
    "km": 28
   },
   {
    "date": "2026-02-21",
    "min": 119,
    "w": 169,
    "hr": 142,
    "km": 49
   },
   {
    "date": "2026-02-23",
    "min": 63,
    "w": 145,
    "hr": 113,
    "km": 31
   },
   {
    "date": "2026-02-23",
    "min": 81,
    "w": 156,
    "hr": 135,
    "km": 30
   },
   {
    "date": "2026-02-24",
    "min": 64,
    "w": 154,
    "hr": 117,
    "km": 31
   },
   {
    "date": "2026-03-02",
    "min": 76,
    "w": 178,
    "hr": 124,
    "km": 41
   },
   {
    "date": "2026-03-04",
    "min": 62,
    "w": 192,
    "hr": 128,
    "km": 33
   },
   {
    "date": "2026-03-14",
    "min": 63,
    "w": 201,
    "hr": 130,
    "km": 31
   },
   {
    "date": "2026-03-21",
    "min": 225,
    "w": 135,
    "hr": 131,
    "km": 87
   },
   {
    "date": "2026-03-31",
    "min": 62,
    "w": 205,
    "hr": 131,
    "km": 31
   },
   {
    "date": "2026-04-05",
    "min": 160,
    "w": 158,
    "hr": 140,
    "km": 59
   },
   {
    "date": "2026-04-05",
    "min": 80,
    "w": 116,
    "hr": 133,
    "km": 28
   },
   {
    "date": "2026-04-08",
    "min": 60,
    "w": 189,
    "hr": 128,
    "km": 28
   },
   {
    "date": "2026-05-02",
    "min": 71,
    "w": 156,
    "hr": 131,
    "km": 25
   },
   {
    "date": "2026-05-31",
    "min": 73,
    "w": 174,
    "hr": 141,
    "km": 32
   }
  ],
  "courseTrim": [
   {
    "trimestre": "2025-T3",
    "paceA140": "7:40",
    "n": 4
   },
   {
    "trimestre": "2025-T4",
    "paceA140": "6:46",
    "n": 12
   },
   {
    "trimestre": "2026-T1",
    "paceA140": "6:02",
    "n": 7
   },
   {
    "trimestre": "2026-T2",
    "paceA140": "5:52",
    "n": 8
   },
   {
    "trimestre": "2026-T3",
    "paceA140": "7:29",
    "n": 2
   }
  ],
  "veloTrim": [
   {
    "trimestre": "2025-T3",
    "wA140": 131,
    "n": 2
   },
   {
    "trimestre": "2025-T4",
    "wA140": 141,
    "n": 4
   },
   {
    "trimestre": "2026-T1",
    "wA140": 187,
    "n": 10
   },
   {
    "trimestre": "2026-T2",
    "wA140": 165,
    "n": 5
   }
  ]
 },
 "lastActivityId": 19945359558,
 "coach": {
  "verdict": "L'entraînement redémarre bien mais la base est encore mince : 11 h en août contre 30 h/mois l'hiver dernier, et l'allure normalisée à 140 bpm est repartie à 6:57/km au T3 contre 5:52/km au T2 — c'est le prix normal de trois mois quasi off, pas un problème structurel. La sortie du 26/08 (12,2 km à 6:27/km pour 130 bpm de moyenne) est le bon signal : tu tiens 1 h 20 en aisance franche sans dérive, la filière aérobie de base est intacte. Côté CrossFit, trois séances en une semaine avec des FC max à 170-185 bpm : l'intensité est déjà là, c'est le volume facile et la force chiffrée qui manquent. Attention quand même, la charge 7 j (144) est à 1,43 fois la charge 28 j (101) — tu remontes vite après 18 jours off sur 28. Le HRV est repassé BALANCED le 25/08 après une semaine LOW (28-40), et le sommeil moyen est correct à 8 h 11 : les feux sont orange-vert, pas rouge.",
  "forts": [
   "Aérobie de base préservée : 12,2 km à 130 bpm de moyenne le 26/08, aucune dérive cardiaque sur 1 h 20.",
   "Sommeil solide — 8 h 11 de moyenne sur 7 nuits, avec 144 min de profond le 25/08.",
   "Reprise CrossFit franche et bien tolérée : 3 séances en 6 jours (21, 23, 26/08) sans chute du HRV le lendemain.",
   "Répartition d'intensité déjà correcte cette semaine : 84 % facile / 16 % dur, exactement la polarisation visée."
  ],
  "manques": [
   "Pas de cycle de force écrit : le back squat 5×5 du 25/08 n'a pas de charge tracée — note les kilos à chaque séance dès lundi prochain.",
   "Zéro stimulus VO2max depuis la reprise : il faut un demi-Cooper puis des 30/30 dès que le HRV tient en base.",
   "Volume vélo quasi nul (0,9 h en août) alors que c'est un pilier hybride — 1 sortie Zwift facile par semaine minimum.",
   "Natation à l'abandon (11 min en août) : 1 créneau technique de 30 min suffirait à ne pas repartir de zéro."
  ],
  "vigilance": "Ratio de charge à 1,43 sur une base de seulement 2,8 séances/semaine — le risque n'est pas cardio mais tendineux (Achille, coudes sur les tractions/wall walks) : monte le volume facile, pas l'intensité.",
  "semaine": {
   "titre": "Fin de semaine de reprise : consolider en facile, une seule séance de qualité restante",
   "volumeCible": "~6 h (dont 3,8 h déjà faites)",
   "doubles": "2",
   "jours": [
    {
     "jour": "Lun",
     "matin": {
      "ico": "—",
      "titre": "Rien",
      "intention": "repos",
      "detail": "",
      "gardefou": ""
     },
     "soir": {
      "ico": "🏋️",
      "titre": "Force pure — FAIT (25/08)",
      "intention": "force",
      "detail": "Back squat 5×5 ~70 %, développé/dips, rowing, gainage. 45 min, FC moy 121. Note les charges pour la semaine prochaine : c'est le point de départ du cycle 5×5.",
      "gardefou": "Déjà réalisé — rien à ajouter."
     }
    },
    {
     "jour": "Mar",
     "matin": {
      "ico": "—",
      "titre": "Rien",
      "intention": "repos",
      "detail": "",
      "gardefou": ""
     },
     "soir": {
      "ico": "—",
      "titre": "Rien",
      "intention": "repos",
      "detail": "",
      "gardefou": ""
     }
    },
    {
     "jour": "Mer",
     "matin": {
      "ico": "🏃",
      "titre": "Endurance facile — FAIT (26/08)",
      "intention": "aisance",
      "detail": "12,2 km en 1 h 19 à 130 bpm. Exactement la bonne séance.",
      "gardefou": "Déjà réalisé."
     },
     "soir": {
      "ico": "🏋️",
      "titre": "Box CrossFit — FAIT (26/08)",
      "intention": "filière moyenne",
      "detail": "AMRAP 15' ski-erg + wall walks, FC moy 118 / max 160.",
      "gardefou": "Déjà réalisé."
     }
    },
    {
     "jour": "Jeu",
     "matin": {
      "ico": "🚴",
      "titre": "Vélo facile home-trainer",
      "intention": "aisance",
      "detail": "45 min sur Zwift, plat, FC < 135 bpm, cadence 85-90 rpm, ~150-160 W. Tu dois pouvoir parler tout du long. C'est de la récupération active après deux jours chargés.",
      "gardefou": "Si les jambes sont lourdes après le doublé de mercredi, coupe à 30 min — ne monte jamais au-dessus de 140 bpm."
     },
     "soir": {
      "ico": "🧘",
      "titre": "Pilates / mobilité",
      "intention": "récup",
      "detail": "30 min : hanches, chevilles, thoracique. Insiste sur les chevilles (squat) et les épaules (wall walks d'hier).",
      "gardefou": "Aucune position douloureuse tenue — on mobilise, on ne force pas."
     }
    },
    {
     "jour": "Ven",
     "matin": {
      "ico": "🏊",
      "titre": "Natation technique",
      "intention": "skill",
      "detail": "30 min : 300 m échauffement, 8×50 m éducatifs (rattrapé, poings fermés, 6-1-6) avec 20 s de récup, 200 m souple. Aucune notion de chrono — on réveille l'appui, c'est tout.",
      "gardefou": "Si le créneau saute (chantier), remplace par 15 min de gainage à la maison, pas par une course."
     },
     "soir": {
      "ico": "🏋️",
      "titre": "Box ou NST — séance de qualité de la semaine",
      "intention": "filière moyenne",
      "detail": "WOD du club. Deux règles : (1) évite tout ce qui charge lourd en hang squat clean ou thruster — tu en as fait dimanche à 30 kg ; (2) évite les tractions et wall walks, coudes et épaules ont déjà pris cette semaine. Si le WOD du jour empile les deux, fais l'échauffement + le skill et scale le métcon à 60 % de l'intensité. Cible : 12-15 min d'effort dur, pas 30.",
      "gardefou": "Si le HRV du matin repasse LOW ou que tu dors moins de 6 h 30 jeudi soir → tu fais l'échauffement et le skill, tu sautes le WOD."
     }
    },
    {
     "jour": "Sam",
     "matin": {
      "ico": "🏃",
      "titre": "Footing en aisance + relances libres",
      "intention": "aisance",
      "detail": "50-55 min, FC < 140 bpm, allure libre (autour de 6:20-6:40/km). Sur les 15 dernières minutes, place 4-5 relances de 20-30 s à la sensation « je force un peu », retour au calme immédiat. Pas de chrono, pas de cible d'allure : tu varies à sensation constante.",
      "gardefou": "Les relances sont optionnelles : si la FC ne redescend pas sous 140 en 1 min après la relance, tu arrêtes les relances et tu finis en trottinant."
     },
     "soir": {
      "ico": "—",
      "titre": "Rien",
      "intention": "repos",
      "detail": "",
      "gardefou": ""
     }
    },
    {
     "jour": "Dim",
     "matin": {
      "ico": "—",
      "titre": "Repos complet",
      "intention": "repos",
      "detail": "Journée off intégrale. C'est elle qui rend possible le bloc « Hybride Automne » qui démarre lundi 31/08.",
      "gardefou": "Pas de « petite sortie pour bouger ». Repos = repos."
     },
     "soir": {
      "ico": "🛒",
      "titre": "Batch cooking",
      "intention": "repos",
      "detail": "1 h 30 de cuisine pour la semaine (voir la partie nutrition). C'est ta séance de dimanche.",
      "gardefou": ""
     }
    }
   ]
  },
  "regle": "Si la semaine déborde, saute la natation du vendredi matin puis le vélo du jeudi ; ne saute jamais le footing facile du samedi — c'est lui qui reconstruit la base, et il est le seul à ne pas être remplaçable.",
  "nutrition": {
   "principe": "Sur 77,5 kg en reprise avec deux séances de force par semaine, vise ~130-150 g de protéines par jour, réparties en 3-4 prises de 30-40 g plutôt qu'un gros bloc le soir — c'est la répartition qui pilote la reconstruction musculaire, pas le total. Les glucides se calent sur les séances : assiette bien remplie les soirs de box (vendredi) et la veille de la sortie longue (vendredi soir pour samedi matin), assiette plus légère et légumes dominants le jeudi et le dimanche. Aucun comptage : un poing de féculent = un jour facile, deux poings = un jour dur, une paume de protéine à chaque repas, des légumes partout.",
   "batch": [
    "Cuire 1,2 kg de blancs de poulet marinés paprika-citron au four → 6 portions de 200 g, 4 j au frigo (congeler 2 portions pour la fin de semaine)",
    "Cuire 500 g de riz basmati cru → ~1,3 kg cuit, 6 portions d'un gros poing, 4 j au frigo",
    "Cuire 400 g de lentilles vertes cru → ~900 g cuites, 5 portions, 5 j au frigo",
    "Rôtir 1,5 kg de légumes (courgettes, poivrons, patate douce) au four → 6 portions, 4 j au frigo",
    "Préparer 10 œufs durs → collations et boîtes, 7 j au frigo",
    "Faire 500 ml de sauce yaourt-citron-herbes → assaisonne toutes les boîtes, 5 j au frigo",
    "Portionner 6 boîtes chantier le dimanche soir (riz ou lentilles + poulet + légumes + sauce à part)"
   ],
   "recettes": [
    {
     "nom": "Poulet mariné paprika-citron au four",
     "usage": "batch dimanche — base de 5 repas",
     "portions": "6 portions de 200 g",
     "temps": "10 min prépa + 25 min four",
     "ingredients": [
      "1,2 kg de blancs de poulet",
      "3 c. à soupe d'huile d'olive",
      "2 c. à café de paprika doux",
      "1 c. à café d'ail en poudre",
      "1 citron (jus)",
      "1 c. à café de sel",
      "Poivre"
     ],
     "etapes": [
      "1. Préchauffe le four à 200 °C chaleur tournante.",
      "2. Dans un grand saladier, mélange l'huile, le paprika, l'ail, le jus de citron, le sel et le poivre.",
      "3. Ajoute les blancs de poulet et retourne-les à la main jusqu'à ce qu'ils soient tous enrobés d'orange.",
      "4. Étale-les à plat sur une plaque couverte de papier cuisson, sans qu'ils se chevauchent.",
      "5. Enfourne 22 à 25 min. C'est cuit quand le jus qui sort en piquant au couteau est clair, jamais rosé, et que la chair s'effiloche facilement.",
      "6. Laisse tiédir 15 min à l'air libre avant de couper en morceaux et de mettre en boîtes — sinon la condensation détrempe tout."
     ],
     "conservation": "4 j au frigo en boîte fermée ; congèle très bien en portions individuelles"
    },
    {
     "nom": "Riz basmati batch",
     "usage": "batch dimanche — base des jours durs",
     "portions": "6 gros poings",
     "temps": "2 min prépa + 12 min cuisson",
     "ingredients": [
      "500 g de riz basmati cru",
      "900 ml d'eau",
      "1 c. à café de sel"
     ],
     "etapes": [
      "1. Rince le riz dans une passoire sous l'eau froide jusqu'à ce que l'eau qui coule soit à peu près claire (30 s).",
      "2. Mets le riz, l'eau et le sel dans une casserole, couvre, porte à ébullition à feu vif.",
      "3. Dès que ça bout, baisse au minimum et laisse 11 min sans jamais soulever le couvercle.",
      "4. Coupe le feu, laisse reposer 5 min couvert, puis aère à la fourchette : les grains doivent se détacher, pas coller en bloc.",
      "5. Étale sur un plat pour refroidir vite avant de mettre au frigo."
     ],
     "conservation": "4 j au frigo ; réchauffe avec 1 c. à soupe d'eau ou mange froid en salade"
    },
    {
     "nom": "Lentilles vertes batch",
     "usage": "batch dimanche — base des jours légers",
     "portions": "5 portions",
     "temps": "5 min prépa + 25 min cuisson",
     "ingredients": [
      "400 g de lentilles vertes sèches",
      "1 oignon",
      "1 feuille de laurier",
      "1 c. à café de sel (à la fin)"
     ],
     "etapes": [
      "1. Rince les lentilles à l'eau froide. Pas besoin de trempage.",
      "2. Mets-les dans une casserole avec l'oignon coupé en deux, le laurier et 3 fois leur volume d'eau froide, sans sel.",
      "3. Porte à ébullition puis baisse à frémissement, 22 à 25 min à découvert.",
      "4. Goûte : elles doivent être tendres mais garder une peau qui résiste sous la dent, pas en purée.",
      "5. Sale, égoutte, retire l'oignon et le laurier, arrose d'un filet d'huile d'olive et laisse refroidir."
     ],
     "conservation": "5 j au frigo ; se congèlent"
    },
    {
     "nom": "Légumes rôtis au four",
     "usage": "batch dimanche — dans toutes les boîtes et tous les dîners",
     "portions": "6 portions",
     "temps": "10 min prépa + 35 min four",
     "ingredients": [
      "3 courgettes (~700 g)",
      "2 poivrons rouges (~400 g)",
      "1 patate douce (~400 g)",
      "4 c. à soupe d'huile d'olive",
      "2 c. à café d'herbes de Provence",
      "Sel, poivre"
     ],
     "etapes": [
      "1. Four à 200 °C. Coupe les courgettes en rondelles épaisses (1,5 cm), les poivrons en lanières, la patate douce en cubes de 2 cm.",
      "2. Mélange tout dans un saladier avec l'huile, les herbes, sel et poivre.",
      "3. Étale sur deux plaques — surtout pas en tas, sinon ça cuit à la vapeur au lieu de rôtir.",
      "4. Enfourne 30 à 35 min. C'est prêt quand les bords sont dorés-bruns et qu'un cube de patate douce se traverse sans résistance à la pointe du couteau.",
      "5. Laisse refroidir sur la plaque avant de mettre en boîtes."
     ],
     "conservation": "4 j au frigo ; se mangent froids ou tièdes, parfaits en boîte chantier"
    },
    {
     "nom": "Œufs durs",
     "usage": "batch dimanche — collations et compléments de boîte",
     "portions": "10 œufs",
     "temps": "12 min",
     "ingredients": [
      "10 œufs"
     ],
     "etapes": [
      "1. Plonge les œufs dans une casserole d'eau déjà bouillante à l'aide d'une cuillère.",
      "2. Compte exactement 9 min à petits bouillons.",
      "3. Transfère-les tout de suite dans un saladier d'eau très froide, 5 min : c'est ce choc qui rend l'écalage facile.",
      "4. Garde-les avec la coquille au frigo, écale au dernier moment."
     ],
     "conservation": "7 j au frigo non écalés"
    },
    {
     "nom": "Sauce yaourt-citron-herbes",
     "usage": "batch dimanche — assaisonne toutes les boîtes froides",
     "portions": "~500 ml, 7 usages",
     "temps": "5 min",
     "ingredients": [
      "400 g de yaourt grec nature",
      "1 citron (jus)",
      "2 c. à soupe d'huile d'olive",
      "1 gousse d'ail écrasée",
      "1 c. à soupe de moutarde",
      "1 poignée de persil ou ciboulette ciselée",
      "Sel, poivre"
     ],
     "etapes": [
      "1. Mets tout dans un bol.",
      "2. Fouette 30 s jusqu'à obtenir une texture lisse et nappante, qui tient sur la cuillère.",
      "3. Verse dans un pot fermé. Transporte-la à part de la boîte, tu la verses au moment de manger."
     ],
     "conservation": "5 j au frigo"
    },
    {
     "nom": "Boîte chantier riz-poulet-légumes",
     "usage": "boîte chantier lundi, mercredi, vendredi",
     "portions": "1 portion, à répéter",
     "temps": "5 min d'assemblage",
     "ingredients": [
      "1 gros poing de riz batch (~200 g cuit)",
      "200 g de poulet batch en morceaux",
      "1 poing de légumes rôtis batch",
      "3 c. à soupe de sauce yaourt (à part)",
      "1 poignée de roquette"
     ],
     "etapes": [
      "1. Dans la boîte, mets le riz au fond.",
      "2. Pose le poulet et les légumes rôtis dessus, côte à côte.",
      "3. Ajoute la roquette par-dessus au dernier moment.",
      "4. La sauce voyage dans un petit pot séparé — tu la verses sur place, sinon la roquette est morte à midi.",
      "5. Se mange froide ou tiède, aucun besoin de micro-ondes."
     ],
     "conservation": "Assemblée la veille au soir, 24 h au frigo"
    },
    {
     "nom": "Boîte chantier lentilles-œufs",
     "usage": "boîte chantier jeudi, samedi",
     "portions": "1 portion",
     "temps": "5 min d'assemblage",
     "ingredients": [
      "1 grosse portion de lentilles batch (~200 g cuites)",
      "2 œufs durs batch",
      "1 poing de légumes rôtis batch",
      "1/2 avocat",
      "3 c. à soupe de sauce yaourt (à part)"
     ],
     "etapes": [
      "1. Lentilles au fond de la boîte.",
      "2. Légumes rôtis dessus.",
      "3. Écale les 2 œufs, coupe-les en deux, pose-les sur le dessus.",
      "4. L'avocat se coupe le matin même, arrosé d'un filet de citron pour qu'il ne noircisse pas.",
      "5. Sauce à part."
     ],
     "conservation": "24 h au frigo, l'avocat ajouté le matin"
    },
    {
     "nom": "Poêlée express poulet-légumes",
     "usage": "dîner jeudi et dimanche",
     "portions": "1 portion",
     "temps": "12 min",
     "ingredients": [
      "200 g de poulet batch",
      "2 poings de légumes rôtis batch",
      "100 g d'épinards frais",
      "1 c. à soupe d'huile d'olive",
      "1 c. à café de curry",
      "1 c. à soupe de crème fraîche épaisse"
     ],
     "etapes": [
      "1. Chauffe l'huile dans une poêle à feu moyen-vif.",
      "2. Jette les épinards, remue 2 min : ils doivent s'affaisser de moitié et devenir vert foncé.",
      "3. Ajoute les légumes rôtis et le poulet coupé, saupoudre le curry, remue 4 min pour tout réchauffer à cœur (le poulet doit être chaud au centre, teste avec le doigt).",
      "4. Coupe le feu, ajoute la crème, mélange 20 s hors du feu pour ne pas la faire trancher.",
      "5. Sers immédiatement."
     ],
     "conservation": "À manger tout de suite"
    },
    {
     "nom": "Riz sauté aux œufs et poulet",
     "usage": "dîner vendredi (soir de box) et veille de sortie longue",
     "portions": "1 grosse portion",
     "temps": "10 min",
     "ingredients": [
      "2 gros poings de riz batch (~300 g cuit)",
      "150 g de poulet batch",
      "2 œufs",
      "1 poing de légumes rôtis batch",
      "2 c. à soupe de sauce soja",
      "1 c. à soupe d'huile",
      "1 c. à café de gingembre râpé (ou en poudre)"
     ],
     "etapes": [
      "1. Chauffe l'huile à feu vif dans une grande poêle.",
      "2. Casse les 2 œufs directement dedans, brouille-les vivement 1 min jusqu'à ce qu'ils soient juste pris, puis réserve-les dans une assiette.",
      "3. Mets le riz froid dans la poêle, étale-le et laisse-le 2 min sans remuer : il doit commencer à accrocher légèrement et faire des petits grains dorés.",
      "4. Ajoute le poulet, les légumes rôtis, le gingembre et la sauce soja, remue 3 min.",
      "5. Remets les œufs, mélange 30 s, sers.",
      "6. Le riz froid du batch est indispensable ici — du riz fraîchement cuit collerait en pâte."
     ],
     "conservation": "À manger tout de suite"
    },
    {
     "nom": "Omelette lentilles-fromage",
     "usage": "dîner samedi soir (après sortie longue, repas rapide)",
     "portions": "1 portion",
     "temps": "8 min",
     "ingredients": [
      "3 œufs",
      "1 portion de lentilles batch (~150 g)",
      "40 g de comté râpé",
      "1 poing de légumes rôtis batch",
      "1 c. à soupe d'huile d'olive",
      "Sel, poivre"
     ],
     "etapes": [
      "1. Bats les 3 œufs à la fourchette avec sel et poivre, 20 s, jusqu'à ce que blanc et jaune soient homogènes.",
      "2. Chauffe l'huile à feu moyen dans une poêle de 24 cm.",
      "3. Verse les lentilles et les légumes, réchauffe 2 min.",
      "4. Verse les œufs par-dessus, laisse prendre 3 min sans toucher : les bords doivent être fermes, le centre encore brillant.",
      "5. Parsème le comté, couvre 1 min pour le faire fondre.",
      "6. Plie en deux et sers — le cœur doit rester moelleux, pas sec."
     ],
     "conservation": "À manger tout de suite"
    },
    {
     "nom": "Bol de récupération yaourt-banane-miel",
     "usage": "collation après séance de force ou de box",
     "portions": "1 portion",
     "temps": "3 min",
     "ingredients": [
      "250 g de yaourt grec (ou skyr)",
      "1 banane",
      "1 c. à soupe de miel",
      "30 g de flocons d'avoine",
      "20 g de noix concassées"
     ],
     "etapes": [
      "1. Mets le yaourt dans un bol.",
      "2. Coupe la banane en rondelles par-dessus.",
      "3. Ajoute les flocons, les noix, puis le miel en filet.",
      "4. Mange dans l'heure qui suit la séance : c'est la fenêtre où les glucides et les protéines partent le plus vite vers le muscle."
     ],
     "conservation": "À faire au moment"
    }
   ],
   "courses": [
    {
     "rayon": "Protéines",
     "items": [
      "1,2 kg de blancs de poulet (2 barquettes)",
      "1 sachet de noix 100 g"
     ]
    },
    {
     "rayon": "Féculents & légumineuses",
     "items": [
      "1 paquet de riz basmati 1 kg",
      "1 paquet de lentilles vertes 500 g",
      "1 paquet de flocons d'avoine 500 g"
     ]
    },
    {
     "rayon": "Légumes & fruits",
     "items": [
      "3 courgettes",
      "2 poivrons rouges",
      "1 patate douce (~400 g)",
      "1 sachet de roquette 125 g",
      "1 sachet d'épinards frais 300 g",
      "2 avocats",
      "5 bananes",
      "3 citrons",
      "1 oignon",
      "1 tête d'ail",
      "1 botte de persil ou ciboulette"
     ]
    },
    {
     "rayon": "Produits laitiers & œufs",
     "items": [
      "24 œufs (1 boîte de 12 + 1 boîte de 12 — 21 pour le petit-déj fixe + batch et dîners)",
      "1 pot de yaourt grec 1 kg",
      "1 petite crème fraîche épaisse 20 cl",
      "1 sachet de comté râpé 200 g"
     ]
    },
    {
     "rayon": "Épicerie",
     "items": [
      "1 bouteille d'huile d'olive 50 cl",
      "1 flacon de sauce soja 25 cl",
      "1 pot de moutarde",
      "1 pot de miel",
      "Paprika doux, ail en poudre, herbes de Provence, curry, gingembre, laurier",
      "Sel, poivre"
     ]
    }
   ],
   "jours": [
    {
     "jour": "Lun",
     "type": "jour force (séance faite lundi soir)",
     "petitDej": "Habituel",
     "dejeuner": "Boîte chantier riz-poulet-légumes + sauce yaourt à part",
     "collation": "Après la séance de force : bol de récupération yaourt-banane-miel",
     "diner": "Riz sauté aux œufs et poulet — 2 poings de riz, on recharge après le squat"
    },
    {
     "jour": "Mar",
     "type": "repos complet",
     "petitDej": "Habituel",
     "dejeuner": "Boîte chantier lentilles-œufs",
     "collation": "—",
     "diner": "Poêlée express poulet-légumes, sans riz : légumes dominants, 1 paume de poulet"
    },
    {
     "jour": "Mer",
     "type": "doublé course + box",
     "petitDej": "Habituel + 1 banane et 30 g de flocons avant la sortie de 1 h 20 — 12 km à jeun sur 3 œufs seuls, tu finis vide",
     "dejeuner": "Boîte chantier riz-poulet-légumes",
     "collation": "Après la box : bol de récupération yaourt-banane-miel",
     "diner": "Riz sauté aux œufs et poulet, grosse portion — journée à deux séances, c'est le repas qui compte"
    },
    {
     "jour": "Jeu",
     "type": "jour facile (vélo + pilates)",
     "petitDej": "Habituel",
     "dejeuner": "Boîte chantier lentilles-œufs",
     "collation": "—",
     "diner": "Poêlée express poulet-légumes + 1 poing de lentilles"
    },
    {
     "jour": "Ven",
     "type": "doublé natation + box (jour dur)",
     "petitDej": "Habituel + 1 tranche de pain ou 30 g de flocons avant la natation",
     "dejeuner": "Boîte chantier riz-poulet-légumes, portion pleine",
     "collation": "1 banane 30 min avant la box, puis bol de récupération après",
     "diner": "Riz sauté aux œufs et poulet, 2 gros poings de riz — et tu recharges aussi pour la sortie de samedi matin"
    },
    {
     "jour": "Sam",
     "type": "endurance facile (footing 50-55 min)",
     "petitDej": "Habituel + 1 banane si tu pars courir dans l'heure",
     "dejeuner": "Boîte chantier lentilles-œufs",
     "collation": "Après le footing : 1 yaourt grec + miel",
     "diner": "Omelette lentilles-fromage — rapide, protéiné, sans excès de glucides puisque dimanche est off"
    },
    {
     "jour": "Dim",
     "type": "repos complet + batch cooking",
     "petitDej": "Habituel",
     "dejeuner": "Restes du frigo : lentilles + légumes rôtis + 2 œufs durs, assiette légère",
     "collation": "—",
     "diner": "Poêlée express poulet-légumes, légumes dominants, 1 seule paume de poulet — jour off, on allège"
    }
   ]
  },
  "generatedAt": "2026-08-27T13:45:49.730Z",
  "programme": {
   "programme": "Hybride Automne 2026",
   "objectif": "Devenir hybride : tenir une heure de course en aisance ET des charges propres en CrossFit, sans blessure.",
   "cible": {
    "date": "2026-11-21",
    "libelle": "Test hybride maison (samedi 21/11) : 10 km en aisance sous 55 min (FC moyenne < 155) le matin, puis l'après-midi 5 tractions strictes enchaînées + back squat 5 reps à 1× poids de corps + 500 m rameur."
   },
   "semaineDansCycle": 0,
   "totalSemaines": 12,
   "bloc": {
    "id": 1,
    "nom": "Fondation",
    "semaines": 4,
    "debut": "2026-08-31",
    "but": "Reposer la régularité et la tolérance tendineuse. Aucune intensité en course.",
    "doubles": [
     3,
     3,
     4,
     2
    ],
    "priorites": [
     "Bi-quotidien progressif : 3 doublés en semaine 1 et 2, 4 en semaine 3, 2 en semaine de décharge (matin aérobie facile, soir qualité)",
     "6 jours actifs par semaine, volume 5 h → 7 h, progression max +15 %/semaine",
     "Toute la course en aisance stricte (FC < 140), sortie longue jusqu'à 1 h 15",
     "2 séances de force par semaine (dont la box NST), charges modérées, technique avant charge",
     "Réintroduire vélo (1×/sem) et natation (1×/sem) comme volume sans impact",
     "Aucune séance de fractionné course — le corps encaisse encore la reprise"
    ],
    "test": "Semaine 4 (décharge) : demi-Cooper (3 min à fond après échauffement) pour mesurer vVO2max, si HRV en base."
   },
   "semaineDansBloc": 0,
   "decharge": false,
   "avantDebut": true,
   "debut": "2026-08-31",
   "termine": false
  },
  "semaineLabel": "2026-S35",
  "semaineDebut": "2026-08-24",
  "semaineFin": "2026-08-30"
 },
 "coachSuivant": {
  "verdict": "Oui, ça repart, mais tu es au tout début : la sortie du 26/08 (12,2 km en 1h19 à 130 bpm, soit 6:27/km) montre que le moteur aérobie est intact, mais l'allure normalisée à 140 bpm est passée de 5:52/km au 2e trimestre à ~6:57/km aujourd'hui — c'est le prix normal de 3 mois à 4 h/semaine, et ça se récupère en 6 à 8 semaines de régularité. Le signal encourageant est ailleurs : ton HRV est remonté de 28 ms (statut LOW le 18/08) à 49 ms le 27/08, la FC repos est repassée de 56 à 47 bpm, et tu dors 8h11 de moyenne sur 7 nuits. Autrement dit, tu as encaissé la reprise et tu es en base — tu as le feu vert physiologique pour monter à 3 doublés cette semaine. Côté force, 80 kg au back squat sur 5 reps à 77,5 kg de poids de corps, c'est 1,03× ton poids : la cible du test (95 kg sur 5) demande +15 kg en 12 semaines, ce qui est atteignable à +2,5 kg/semaine avec des semaines de décharge. Je n'ai aucune donnée sur d'éventuelles douleurs tendineuses ni sur ce que tu manges réellement — dis-le moi si quelque chose tire.",
  "forts": [
   "Le moteur aérobie n'a pas disparu : 12,2 km à 130 bpm seulement, tu tiens 1h19 en aisance stricte sans forcer.",
   "Récupération franchement bonne : 491 min de sommeil de moyenne sur 7 nuits et HRV à 49 ms le 27/08 contre une base à 38.",
   "Tu es déjà polyvalent : sur les 10 derniers jours tu as fait course, vélo, natation, CrossFit et Pilates — la base hybride existe.",
   "Force honnête pour une reprise : 80 kg × 5 au back squat et des tractions strictes en finisher le 26/08."
  ],
  "manques": [
   "Aucune régularité chiffrée : 4 h en S35 et 2,8 séances/semaine sur 28 jours, il faut monter à 6 séances/semaine avant de parler d'intensité.",
   "Zéro travail de charnière de hanche lourde (soulevé de terre, swing) dans l'historique — c'est le pattern qui manque pour le CrossFit.",
   "Pas de sortie longue depuis le 26/08 : il faut réinstaller une heure de course hebdomadaire pour viser les 10 km en 55 min.",
   "Le vélo a quasi disparu (0,9 h en août contre 13,8 h en mars) : c'est ton volume aérobie sans impact les matins avec les enfants."
  ],
  "vigilance": "Le risque n°1 cette semaine c'est le tendon d'Achille et le genou : tu passes de ~1 h de course par semaine à ~2 h avec des chaussures et des tendons désentraînés — toute douleur qui persiste après l'échauffement = stop course, vélo à la place.",
  "semaine": {
   "titre": "Reposer la régularité : 6 jours actifs, tout en aisance, 2 séances de force",
   "volumeCible": "~6 h 30",
   "doubles": "3",
   "jours": [
    {
     "jour": "Lun",
     "matin": {
      "ico": "🚴",
      "titre": "Home-trainer facile 40 min",
      "intention": "aisance",
      "detail": "Tu es avec les enfants, donc tout se passe à la maison. Objectif : faire tourner les jambes et réveiller le système sans aucune contrainte — tu dois pouvoir parler tout du long.",
      "etapes": [
       "10 min de pédalage très souple, FC sous 120 bpm, cadence 85-90 tours/min",
       "25 min en aisance : FC 125-135 bpm, cadence libre, tu peux tenir une conversation",
       "3× 20 secondes de cadence rapide (100-105 tours/min) sans monter la résistance, 1 min souple entre",
       "5 min de retour au calme très souple",
       "2 min d'étirement mollets + quadriceps debout"
      ],
      "gardefou": "Si la FC dépasse 140 bpm sans que tu forces, baisse la résistance : le matin, on ne négocie pas l'aisance."
     },
     "soir": {
      "ico": "🏋️",
      "titre": "Force lourde — squat et poussée (semaine 1/4 du cycle 5×5)",
      "intention": "force",
      "detail": "C'est la séance dure de la journée et le point de départ chiffré de ton cycle de force : 80 kg au back squat, la charge que tu as validée le 27/08. Technique avant charge, les deux dernières reps de chaque série doivent rester propres.",
      "etapes": [
       "Échauffement 8 min : 3 min rameur souple, puis 10 squats à vide, 10 fentes par jambe, 10 rotations d'épaules",
       "Montée en charge au back squat (barre sur le haut du dos) : 10 reps à vide, 5 à 40 kg, 5 à 60 kg, 3 à 70 kg",
       "Back squat 5 séries de 5 reps à 80 kg — 2 min 30 de récupération entre les séries",
       "Développé couché ou pompes lestées 4 séries de 8 reps — charge où la 8e sort propre, 1 min 30 de récup",
       "Rowing barre (buste penché à 45°, dos plat, tirer la barre vers le nombril) 4 séries de 8 reps à 40 kg, 1 min 30 de récup",
       "Gainage : 3 × 45 secondes de planche ventrale + 3 × 30 secondes de planche latérale par côté",
       "5 min de vélo souple ou marche pour redescendre"
      ],
      "gardefou": "Si une rep du squat te fait pencher le buste en avant ou décoller les talons, tu arrêtes la série et tu baisses de 5 kg — cette semaine, on installe la technique, pas le record."
     }
    },
    {
     "jour": "Mar",
     "matin": {
      "ico": "🧘",
      "titre": "Pilates / mobilité 25 min",
      "intention": "récup",
      "detail": "Lendemain de force lourde : on fait circuler, on ne charge rien. Séance courte à la maison, respiration ample, aucune douleur recherchée.",
      "etapes": [
       "5 min de respiration et mobilisation du bassin allongé sur le dos",
       "10 min de mobilité hanches et chevilles : fentes en pas de course tenues 30 s par côté, accroupi profond tenu 1 min × 2",
       "8 min de gainage doux : planche 3 × 30 s, pont fessier 3 × 12 reps",
       "3 min d'étirement quadriceps, ischio-jambiers et mollets"
      ],
      "gardefou": "Si les cuisses sont très raides du squat de la veille, remplace le gainage par 10 min de marche — pas d'étirement forcé sur un muscle courbaturé."
     },
     "soir": {
      "ico": "—",
      "titre": "Rien",
      "intention": "repos",
      "detail": "",
      "gardefou": ""
     }
    },
    {
     "jour": "Mer",
     "matin": {
      "ico": "🤸",
      "titre": "Gainage + corde à sauter 20 min",
      "intention": "skill",
      "detail": "Avec les enfants, donc maison. Séance courte de coordination et de raideur de cheville — c'est ce qui protège ton Achille quand tu remontes le volume de course.",
      "etapes": [
       "3 min d'échauffement : montées de genoux sur place, cercles de chevilles, talons-fesses",
       "Corde à sauter : 6 séries de 40 secondes, 40 secondes de repos — pieds proches du sol, contact court",
       "Gainage : 3 tours de 30 s planche + 12 mountain climbers + 12 pont fessier",
       "2 min d'étirement mollets contre le mur, 30 s par jambe × 2"
      ],
      "gardefou": "Si les mollets brûlent avant la 4e série de corde, arrête là : la corde est un outil de raideur, pas une séance de cardio."
     },
     "soir": {
      "ico": "🏋️",
      "titre": "Box CrossFit ou NST — WOD du club",
      "intention": "filière moyenne",
      "detail": "Séance dure de la semaine. Tu prends le WOD au tableau tel qu'il est. Tant que le programme NST n'est pas fourni, ce créneau est « box ou NST » : si tu as le NST d'ici là, c'est lui qui passe en priorité et tu ignores le WOD.",
      "etapes": [
       "Échauffement de la box en entier, sans le zapper",
       "Travail de skill / technique proposé par le coach — c'est là que tu progresses, tu le fais frais",
       "WOD au niveau Sc ou Int : vise la même charge que le 23/08 (30 kg sur les mouvements barre), pas plus",
       "Finisher seulement si tu as encore de la marge : 15 à 20 tractions strictes cumulées",
       "5 min de vélo ou rameur très souple pour redescendre"
      ],
      "gardefou": "Si le WOD contient du squat lourd ou du soulevé lourd, tu réduis la charge de 20 % : tu as déjà squatté lourd lundi."
     }
    },
    {
     "jour": "Jeu",
     "matin": {
      "ico": "—",
      "titre": "Rien",
      "intention": "repos",
      "detail": "",
      "gardefou": ""
     },
     "soir": {
      "ico": "—",
      "titre": "Repos complet",
      "intention": "repos",
      "detail": "C'est ta journée sans rien de la semaine, et elle est volontaire : elle tombe après le WOD et avant les trois jours les plus chargés. Marche si tu veux, rien d'autre.",
      "gardefou": ""
     }
    },
    {
     "jour": "Ven",
     "matin": {
      "ico": "🚴",
      "titre": "Home-trainer facile 40 min",
      "intention": "aisance",
      "detail": "Les garçons sont encore à la maison ce matin (ils partent chez leur mère dans la matinée) : séance à la maison. Objectif inchangé — faire tourner les jambes en aisance stricte avant la journée de chantier.",
      "etapes": [
       "10 min de pédalage souple, cadence 85-90 tours/min, FC sous 120 bpm",
       "25 min en aisance : FC 125-135 bpm, tu dois pouvoir parler tout du long",
       "3 × 20 s à cadence rapide (100-105) sans monter la résistance, 1 min souple entre chaque",
       "5 min de retour au calme + 5 min de mobilité hanches et chevilles"
      ],
      "gardefou": "Si les jambes sont lourdes de la semaine, coupe à 30 min — cette séance ne doit jamais être dure."
     },
     "soir": {
      "ico": "🏋️",
      "titre": "Force 2 — charnière de hanche et tirage",
      "intention": "force",
      "detail": "Deuxième séance de force de la semaine, sur le pattern qui te manque : la charnière de hanche (le mouvement où le bassin recule et le dos reste plat). Charges modérées, on cherche le geste propre, pas la performance.",
      "etapes": [
       "Échauffement 8 min : 3 min rameur, 15 ponts fessiers, 15 good-mornings à vide (barre sur les épaules, buste qui descend en gardant le dos plat)",
       "Soulevé de terre roumain (barre le long des jambes, bassin qui recule, on descend jusqu'à mi-tibia) 4 séries de 6 reps à 60 kg — 2 min de récup",
       "Tractions strictes : 5 séries de 3 reps (ou tractions excentriques, 5 s à la descente, si les 3 ne sortent pas) — 2 min de récup",
       "Fentes marchées avec haltères 3 séries de 10 pas par jambe, 12 kg par main, 90 s de récup",
       "Gainage anti-rotation : 3 × 30 s de planche latérale par côté",
       "5 min de marche ou vélo souple"
      ],
      "gardefou": "Au premier arrondi du bas du dos sur le soulevé roumain, tu termines la série et tu baisses à 50 kg — le dos plat est non négociable."
     }
    },
    {
     "jour": "Sam",
     "matin": {
      "ico": "🏃",
      "titre": "Sortie longue 1 h 15 en aisance",
      "intention": "filière longue",
      "detail": "Week-end sans les enfants : c'est la séance clé de la semaine, celle qui reconstruit la tolérance tendineuse et la base aérobie. Une seule règle : FC sous 140 bpm du début à la fin, quitte à marcher dans les montées. Les garçons sont partis vendredi matin : le week-end est libre, c'est la séance clé de la semaine.",
      "etapes": [
       "10 min de trot très lent en échauffement, FC sous 125 bpm",
       "60 min de course continue à FC 130-140 bpm, allure libre selon la sensation — marche 1 min dès que la FC dépasse 142",
       "Sur les 15 dernières minutes, si la FC est basse et que les jambes sont bonnes, laisse l'allure accélérer spontanément sans dépasser 140 bpm",
       "5 min de marche de retour au calme",
       "Boire 500 ml d'eau et manger dans les 30 min qui suivent",
       "5 min d'étirements mollets, ischio-jambiers, fessiers"
      ],
      "gardefou": "Si tu n'es plus capable de tenir la FC sous 140 en courant, tu termines en marche/course alternée — le temps passé en aisance compte, pas la continuité."
     },
     "soir": {
      "ico": "—",
      "titre": "Rien",
      "intention": "repos",
      "detail": "",
      "gardefou": ""
     }
    },
    {
     "jour": "Dim",
     "matin": {
      "ico": "🚶",
      "titre": "Marche + mobilité 40 min",
      "intention": "récup",
      "detail": "Desautel est fermée le dimanche : on remplace la natation par de la récupération active à la maison ou dehors, au lendemain de la sortie longue. Rien de cardio, on fait circuler.",
      "etapes": [
       "30 min de marche tranquille (ou 20 min de home-trainer très souple si tu préfères rester à la maison)",
       "10 min de mobilité : hanches, chevilles, thoracique",
       "3 × 12 extensions de mollets lentes à la descente, pour l'Achille",
       "Étirements ischios et quadriceps, 30 s par côté"
      ],
      "gardefou": "Aucune intensité aujourd'hui, même si tu te sens bien : c'est ce qui permet d'enchaîner la semaine 2."
     },
     "soir": {
      "ico": "🍲",
      "titre": "Batch cooking (pas une séance)",
      "intention": "repos",
      "detail": "Préparation des repas de la semaine.",
      "etapes": [],
      "gardefou": ""
     }
    }
   ]
  },
  "regle": "Si la semaine déborde, tu sautes en priorité le gainage/corde du mercredi matin, puis la natation du dimanche ; tu ne sautes jamais la sortie longue du samedi ni la séance de force du lundi soir — ce sont les deux piliers du bloc Fondation.",
  "nutrition": {
   "principe": "À 77,5 kg avec deux séances de force par semaine, vise environ 150 g de protéines par jour, répartis en 4 prises d'environ 35-40 g (une paume de viande ou de poisson, 3 œufs, ou 200 g de yaourt grec) — la répartition compte plus que le total. Les glucides se calent sur les séances : plus gros le soir des jours de force (lundi, vendredi) et le soir précédant la sortie longue (vendredi), plus légers le jeudi (repos) et le mardi. Le jeudi et le dimanche soir, l'assiette bascule vers les légumes et une source de protéines simple, sans gros féculent. Pas de comptage : tu utilises le poing pour les féculents et la paume pour les protéines.",
   "batch": [
    "Cuire 1 kg de filets de poulet marinés au four → 5 portions de ~180 g, 4 jours au frigo (congeler 2 portions si tu vises jusqu'à dimanche)",
    "Cuire 300 g de riz basmati cru + 250 g de lentilles vertes crues séparément → 6 portions mélangées, 4 jours au frigo",
    "Rôtir 1,5 kg de légumes (courgettes, poivrons, carottes, oignons) au four → 6 portions, 5 jours au frigo",
    "Faire cuire 6 œufs durs → 6 jours au frigo, coquille non écalée",
    "Préparer 1 chili de bœuf haché et haricots rouges → 4 portions, 4 jours au frigo, se congèle",
    "Mélanger une sauce yaourt-citron-herbes (400 g) → 5 jours au frigo, pour relever les boîtes chantier",
    "Monter 4 pots de flocons d'avoine au yaourt (overnight oats) → 4 jours au frigo, collation d'après-séance"
   ],
   "recettes": [
    {
     "nom": "Poulet mariné au four",
     "usage": "batch dimanche — base des boîtes chantier et de plusieurs dîners",
     "portions": "5 portions",
     "temps": "10 min prépa + 25 min four",
     "ingredients": [
      "1 kg de filets de poulet",
      "3 cuillères à soupe d'huile d'olive",
      "2 cuillères à café de paprika",
      "1 cuillère à café de cumin",
      "2 gousses d'ail écrasées",
      "le jus d'1 citron",
      "1 cuillère à café de sel, poivre"
     ],
     "etapes": [
      "Préchauffe le four à 200 °C (chaleur tournante).",
      "Dans un grand saladier, mélange l'huile, le paprika, le cumin, l'ail, le jus de citron, le sel et le poivre.",
      "Ajoute les filets de poulet et retourne-les à la main pour bien les enrober. Laisse 10 min pendant que le four chauffe.",
      "Étale les filets sur une plaque couverte de papier cuisson, sans qu'ils se chevauchent.",
      "Enfourne 22 à 25 min. Le poulet est cuit quand la chair est blanche jusqu'au cœur : coupe le plus épais, il ne doit rester aucune trace rosée et le jus qui sort doit être clair.",
      "Laisse tiédir 15 min sur la plaque, puis répartis en 5 boîtes."
     ],
     "conservation": "4 jours au frigo, se congèle très bien en portions"
    },
    {
     "nom": "Riz-lentilles du batch",
     "usage": "batch dimanche — féculent de toutes les boîtes chantier",
     "portions": "6 portions",
     "temps": "5 min prépa + 25 min cuisson",
     "ingredients": [
      "300 g de riz basmati cru",
      "250 g de lentilles vertes crues",
      "1 oignon coupé en petits dés",
      "1 cuillère à soupe d'huile d'olive",
      "sel"
     ],
     "etapes": [
      "Rince le riz sous l'eau froide jusqu'à ce que l'eau sorte à peu près claire.",
      "Dans une casserole, couvre les lentilles de 3 fois leur volume d'eau froide salée. Porte à ébullition puis laisse frémir 20 à 22 min : elles doivent s'écraser sous le doigt mais garder leur forme. Égoutte.",
      "En parallèle, dans une autre casserole, mets le riz avec 1,5 fois son volume d'eau et un peu de sel. Porte à ébullition, couvre, baisse au minimum et laisse 11 min sans ouvrir. Coupe le feu et laisse gonfler 5 min.",
      "Fais revenir l'oignon 4 min dans l'huile d'olive jusqu'à ce qu'il devienne translucide.",
      "Mélange riz, lentilles et oignon dans un grand plat. Laisse refroidir à découvert 20 min avant de mettre en boîtes (sinon ça fermente)."
     ],
     "conservation": "4 jours au frigo, se congèle"
    },
    {
     "nom": "Légumes rôtis au four",
     "usage": "batch dimanche — moitié légume des boîtes et des dîners",
     "portions": "6 portions",
     "temps": "15 min prépa + 35 min four",
     "ingredients": [
      "3 courgettes coupées en demi-rondelles épaisses",
      "3 poivrons coupés en lanières",
      "500 g de carottes en rondelles",
      "2 oignons en quartiers",
      "4 cuillères à soupe d'huile d'olive",
      "2 cuillères à café d'herbes de Provence",
      "sel, poivre"
     ],
     "etapes": [
      "Préchauffe le four à 200 °C.",
      "Mélange tous les légumes dans un grand saladier avec l'huile, les herbes, le sel et le poivre.",
      "Étale sur deux plaques (ne surcharge pas, sinon les légumes cuisent à la vapeur au lieu de rôtir).",
      "Enfourne 30 à 35 min, en remuant à mi-cuisson. C'est prêt quand les bords sont dorés et qu'une carotte se transperce facilement à la fourchette.",
      "Laisse refroidir avant de répartir en boîtes."
     ],
     "conservation": "5 jours au frigo"
    },
    {
     "nom": "Œufs durs",
     "usage": "batch dimanche — collation et complément protéines des boîtes",
     "portions": "6 œufs",
     "temps": "12 min",
     "ingredients": [
      "6 œufs"
     ],
     "etapes": [
      "Sors les œufs du frigo 10 min avant pour éviter qu'ils éclatent.",
      "Plonge-les dans une casserole d'eau bouillante à l'aide d'une cuillère.",
      "Compte 9 min à petits bouillons pour un jaune ferme mais pas crayeux.",
      "Transvase-les immédiatement dans un saladier d'eau très froide et laisse 5 min : ça arrête la cuisson et facilite l'écalage.",
      "Garde-les au frigo dans leur coquille, écale au moment de manger."
     ],
     "conservation": "6 jours au frigo, coquille intacte"
    },
    {
     "nom": "Chili de bœuf aux haricots rouges",
     "usage": "batch dimanche — dîner mercredi + boîte chantier jeudi",
     "portions": "4 portions",
     "temps": "10 min prépa + 30 min mijotage",
     "ingredients": [
      "500 g de bœuf haché 5 %",
      "2 boîtes de 400 g de haricots rouges égouttés et rincés",
      "2 boîtes de 400 g de tomates concassées",
      "1 oignon en dés",
      "2 gousses d'ail écrasées",
      "1 cuillère à soupe d'huile d'olive",
      "2 cuillères à café de cumin",
      "1 cuillère à café de paprika",
      "sel, poivre"
     ],
     "etapes": [
      "Fais chauffer l'huile dans une grande casserole, ajoute l'oignon et l'ail, remue 4 min jusqu'à ce que l'oignon devienne translucide.",
      "Ajoute le bœuf haché, écrase-le à la cuillère en bois et fais-le colorer 5 min : il ne doit plus rester de rose.",
      "Ajoute le cumin, le paprika, le sel et le poivre, remue 1 min pour réveiller les épices.",
      "Verse les tomates concassées et les haricots rouges, mélange.",
      "Laisse mijoter à feu doux 25 à 30 min sans couvercle, en remuant de temps en temps. C'est prêt quand la sauce a épaissi et n'est plus liquide au fond.",
      "Laisse tiédir, répartis en 4 boîtes."
     ],
     "conservation": "4 jours au frigo, se congèle"
    },
    {
     "nom": "Sauce yaourt-citron-herbes",
     "usage": "batch dimanche — à ajouter sur les boîtes chantier froides",
     "portions": "environ 400 g, 6 utilisations",
     "temps": "5 min",
     "ingredients": [
      "400 g de yaourt grec",
      "le jus d'1 citron",
      "1 cuillère à café de moutarde",
      "1 gousse d'ail écrasée",
      "2 cuillères à soupe d'herbes de Provence ou d'herbes fraîches",
      "sel, poivre"
     ],
     "etapes": [
      "Mets le yaourt grec dans un bol.",
      "Ajoute le jus de citron, la moutarde, l'ail, les herbes, le sel et le poivre.",
      "Fouette à la fourchette 1 min jusqu'à obtenir une texture lisse et nappante (elle doit couler lentement de la cuillère).",
      "Verse dans un pot fermé."
     ],
     "conservation": "5 jours au frigo"
    },
    {
     "nom": "Pots de flocons d'avoine au yaourt",
     "usage": "batch dimanche — collation d'après-séance du soir",
     "portions": "4 pots",
     "temps": "10 min + une nuit au frigo",
     "ingredients": [
      "200 g de flocons d'avoine",
      "500 g de fromage blanc",
      "2 bananes écrasées",
      "2 cuillères à soupe de miel",
      "80 g d'amandes concassées"
     ],
     "etapes": [
      "Écrase les bananes à la fourchette dans un saladier.",
      "Ajoute le fromage blanc, le miel et les flocons d'avoine, mélange bien.",
      "Répartis dans 4 pots avec couvercle.",
      "Ajoute les amandes concassées sur le dessus, ferme et mets au frigo au moins une nuit : les flocons doivent avoir gonflé et la texture être crémeuse, plus du tout granuleuse."
     ],
     "conservation": "4 jours au frigo"
    },
    {
     "nom": "Omelette aux épinards et feta",
     "usage": "dîner mardi (jour léger)",
     "portions": "1 portion",
     "temps": "10 min",
     "ingredients": [
      "3 œufs",
      "100 g d'épinards frais",
      "50 g de feta émiettée",
      "1 cuillère à soupe d'huile d'olive",
      "sel, poivre"
     ],
     "etapes": [
      "Bats les 3 œufs à la fourchette avec sel et poivre, 30 secondes, jusqu'à ce que le mélange soit homogène.",
      "Chauffe l'huile dans une poêle à feu moyen, jette les épinards et remue 2 min : ils doivent retomber complètement en volume.",
      "Verse les œufs par-dessus, baisse le feu.",
      "Parsème la feta et laisse cuire 4 à 5 min sans remuer : le dessus doit être juste pris, encore légèrement brillant.",
      "Plie l'omelette en deux et sers avec une portion de légumes rôtis du batch."
     ],
     "conservation": "à manger tout de suite"
    },
    {
     "nom": "Saumon poêlé et patates douces rôties",
     "usage": "dîner vendredi (veille de la sortie longue)",
     "portions": "1 portion (patates douces pour 2 repas)",
     "temps": "5 min prépa + 30 min four + 8 min poêle",
     "ingredients": [
      "1 pavé de saumon (125 g)",
      "400 g de patates douces en cubes",
      "1 cuillère à soupe d'huile d'olive",
      "1/2 citron",
      "sel, poivre"
     ],
     "etapes": [
      "Préchauffe le four à 200 °C. Étale les cubes de patate douce avec l'huile, le sel et le poivre sur une plaque.",
      "Enfourne 28 à 30 min : les bords doivent être dorés et la fourchette entrer sans résistance.",
      "10 min avant la fin, chauffe une poêle à feu moyen-vif sans matière grasse et pose le saumon côté peau.",
      "Laisse 5 min sans y toucher : la peau doit être croustillante et la chair devenir opaque en remontant sur les côtés.",
      "Retourne et compte 2 à 3 min. Le saumon est cuit quand il s'effeuille à la fourchette mais reste légèrement rosé au centre.",
      "Presse le demi-citron dessus et sers avec les patates douces (garde la moitié pour le lendemain)."
     ],
     "conservation": "patates douces : 3 jours au frigo"
    },
    {
     "nom": "Pâtes complètes au thon et tomate",
     "usage": "dîner samedi (recharge après la sortie longue)",
     "portions": "1 portion",
     "temps": "15 min",
     "ingredients": [
      "120 g de pâtes complètes crues",
      "2 boîtes de 140 g de thon égoutté",
      "1 boîte de 400 g de tomates concassées",
      "1 gousse d'ail écrasée",
      "1 cuillère à soupe d'huile d'olive",
      "20 g de parmesan râpé",
      "sel, poivre"
     ],
     "etapes": [
      "Fais bouillir une grande casserole d'eau salée et cuis les pâtes selon le temps indiqué sur le paquet, moins 1 min : elles doivent rester fermes sous la dent.",
      "Pendant ce temps, chauffe l'huile dans une poêle, ajoute l'ail et remue 30 secondes sans le laisser brunir.",
      "Verse les tomates concassées, sale, poivre, laisse réduire 8 min à feu moyen : la sauce doit épaissir et ne plus être aqueuse.",
      "Ajoute le thon égoutté, mélange et chauffe 2 min.",
      "Égoutte les pâtes, mélange-les à la sauce, ajoute le parmesan et sers immédiatement."
     ],
     "conservation": "à manger tout de suite"
    },
    {
     "nom": "Velouté courgette-pois chiches",
     "usage": "dîner jeudi (jour de repos)",
     "portions": "2 portions",
     "temps": "20 min",
     "ingredients": [
      "1 courgette en rondelles",
      "1 boîte de 400 g de pois chiches égouttés",
      "1 oignon en dés",
      "1 cuillère à soupe d'huile d'olive",
      "600 ml d'eau",
      "sel, poivre, 1 cuillère à café de cumin"
     ],
     "etapes": [
      "Fais revenir l'oignon dans l'huile 4 min jusqu'à ce qu'il devienne translucide.",
      "Ajoute la courgette, les pois chiches, le cumin, le sel et le poivre, remue 2 min.",
      "Verse les 600 ml d'eau, porte à ébullition puis laisse cuire 12 min à feu moyen : la courgette doit s'écraser à la cuillère.",
      "Mixe au mixeur plongeant jusqu'à obtenir une texture lisse et onctueuse, sans morceaux.",
      "Sers avec 2 œufs durs du batch pour la protéine."
     ],
     "conservation": "3 jours au frigo"
    },
    {
     "nom": "Wrap poulet-légumes",
     "usage": "boîte chantier — mercredi et vendredi",
     "portions": "1 portion (2 wraps)",
     "temps": "5 min, sans cuisson",
     "ingredients": [
      "2 tortillas de blé",
      "150 g de poulet mariné du batch, coupé en lanières",
      "1 portion de légumes rôtis du batch",
      "2 cuillères à soupe de sauce yaourt-citron du batch",
      "quelques feuilles de salade verte"
     ],
     "etapes": [
      "Étale 1 cuillère à soupe de sauce yaourt sur chaque tortilla, en laissant 2 cm de bord libre.",
      "Répartis la salade, puis les légumes rôtis, puis le poulet.",
      "Roule serré en repliant d'abord le bas de la tortilla, puis les côtés.",
      "Coupe en deux en biais et emballe dans du papier cuisson : ça se mange froid sans réchauffer."
     ],
     "conservation": "à préparer la veille au soir, 24 h au frigo"
    }
   ],
   "courses": [
    {
     "rayon": "Protéines",
     "items": [
      "1 kg de filets de poulet",
      "500 g de bœuf haché 5 %",
      "2 pavés de saumon (250 g)",
      "2 boîtes de thon au naturel (140 g chacune)"
     ]
    },
    {
     "rayon": "Féculents & légumineuses",
     "items": [
      "500 g de riz basmati",
      "250 g de lentilles vertes",
      "500 g de pâtes complètes",
      "500 g de flocons d'avoine",
      "1 paquet de 6 tortillas de blé",
      "800 g de patates douces",
      "2 boîtes de haricots rouges (400 g)",
      "1 boîte de pois chiches (400 g)",
      "1 pain complet"
     ]
    },
    {
     "rayon": "Légumes & fruits",
     "items": [
      "4 courgettes",
      "3 poivrons",
      "1 kg de carottes",
      "4 oignons",
      "1 tête d'ail",
      "3 boîtes de tomates concassées (400 g)",
      "300 g d'épinards frais",
      "1 salade verte",
      "6 bananes",
      "4 pommes",
      "2 citrons"
     ]
    },
    {
     "rayon": "Produits laitiers & œufs",
     "items": [
      "30 œufs (2 boîtes de 12 + 1 de 6)",
      "400 g de yaourt grec",
      "500 g de fromage blanc",
      "200 g de feta",
      "100 g de parmesan râpé"
     ]
    },
    {
     "rayon": "Épicerie",
     "items": [
      "1 bouteille d'huile d'olive",
      "paprika, cumin, herbes de Provence",
      "sel, poivre",
      "1 pot de moutarde",
      "1 pot de miel",
      "1 pot de beurre de cacahuète",
      "200 g d'amandes"
     ]
    }
   ],
   "jours": [
    {
     "jour": "Lun",
     "type": "jour force (home-trainer matin + squat lourd soir)",
     "petitDej": "Habituel",
     "dejeuner": "Boîte froide : 1 portion de riz-lentilles + 180 g de poulet mariné + 1 portion de légumes rôtis + 2 cuillères à soupe de sauce yaourt-citron",
     "collation": "Avant la séance du soir (vers 17 h) : 1 banane + 1 cuillère à soupe de beurre de cacahuète. Après : 1 pot de flocons d'avoine",
     "diner": "Chili de bœuf-haricots rouges (1 portion) + 1 poing de riz du batch — jour de force, on charge protéines et glucides"
    },
    {
     "jour": "Mar",
     "type": "jour léger (Pilates matin, rien le soir)",
     "petitDej": "Habituel",
     "dejeuner": "Boîte froide : salade verte + 150 g de poulet mariné + 1 portion de légumes rôtis + 2 œufs durs + sauce yaourt",
     "collation": "1 pomme + 30 g d'amandes",
     "diner": "Omelette 3 œufs aux épinards et feta + légumes rôtis du batch — pas de gros féculent, la journée est calme"
    },
    {
     "jour": "Mer",
     "type": "jour box (gainage matin, WOD le soir)",
     "petitDej": "Habituel",
     "dejeuner": "2 wraps poulet-légumes (préparés la veille) + 1 pomme",
     "collation": "1 h avant la box : 1 banane + 2 tranches de pain complet avec du miel. Après la box : 200 g de fromage blanc",
     "diner": "Chili de bœuf (1 portion) + 1 poing de riz-lentilles — reconstruire après le WOD, dans l'heure qui suit"
    },
    {
     "jour": "Jeu",
     "type": "repos complet",
     "petitDej": "Habituel",
     "dejeuner": "Boîte froide : 1 portion de chili + salade verte + 1 poing de riz-lentilles",
     "collation": "—",
     "diner": "Velouté courgette-pois chiches + 2 œufs durs — assiette légère, légumes dominants, tu ne t'entraînes pas"
    },
    {
     "jour": "Ven",
     "type": "jour double (course facile matin + force soir), veille de sortie longue",
     "petitDej": "Habituel + 1 banane avant de partir courir (40 min de course à jeun sur une reprise, autant avoir un peu de sucre disponible)",
     "dejeuner": "2 wraps poulet-légumes + 1 pomme",
     "collation": "Avant la force du soir : 2 tranches de pain complet + miel. Après : 1 pot de flocons d'avoine",
     "diner": "Saumon poêlé + patates douces rôties (grosse portion) — glucides du soir pour la sortie longue de demain matin"
    },
    {
     "jour": "Sam",
     "type": "sortie longue 1 h 15",
     "petitDej": "Habituel + 40 g de flocons d'avoine avec une banane écrasée, 1 h avant de partir",
     "dejeuner": "Reste de patates douces + 150 g de poulet mariné + légumes rôtis + sauce yaourt",
     "collation": "Dans les 30 min après la sortie : 200 g de fromage blanc + 1 banane + miel",
     "diner": "Pâtes complètes au thon et tomate + parmesan — la vraie recharge de la semaine"
    },
    {
     "jour": "Dim",
     "type": "récupération (natation) + batch cooking",
     "petitDej": "Habituel",
     "dejeuner": "Reste de pâtes au thon ou dernière portion de chili + salade verte",
     "collation": "1 pomme + 30 g d'amandes pendant que le four tourne",
     "diner": "Omelette 3 œufs + légumes rôtis frais sortis du four + 2 tranches de pain complet — simple, tu es déjà en cuisine"
    }
   ]
  },
  "generatedAt": "2026-08-30T19:00:00.000Z",
  "figeLe": "2026-08-30T19:00:00.000Z",
  "programme": {
   "programme": "Hybride Automne 2026",
   "objectif": "Devenir hybride : tenir une heure de course en aisance ET des charges propres en CrossFit, sans blessure.",
   "cible": {
    "date": "2026-11-21",
    "libelle": "Test hybride maison (samedi 21/11) : 10 km en aisance sous 55 min (FC moyenne < 155) le matin, puis l'après-midi 5 tractions strictes enchaînées + back squat 5 reps à 1,2× poids de corps (≈ 95 kg) + 500 m rameur."
   },
   "semaineDansCycle": 1,
   "totalSemaines": 12,
   "bloc": {
    "id": 1,
    "nom": "Fondation",
    "semaines": 4,
    "debut": "2026-08-31",
    "but": "Reposer la régularité et la tolérance tendineuse. Aucune intensité en course.",
    "doubles": [
     3,
     3,
     4,
     2
    ],
    "priorites": [
     "Bi-quotidien progressif : 3 doublés en semaine 1 et 2, 4 en semaine 3, 2 en semaine de décharge (matin aérobie facile, soir qualité)",
     "6 jours actifs par semaine, volume 5 h → 7 h, progression max +15 %/semaine",
     "Toute la course en aisance stricte (FC < 140), sortie longue jusqu'à 1 h 15",
     "2 séances de force par semaine (dont la box NST), charges modérées, technique avant charge",
     "Réintroduire vélo (1×/sem) et natation (1×/sem) comme volume sans impact",
     "Aucune séance de fractionné course — le corps encaisse encore la reprise"
    ],
    "test": "Semaine 4 (décharge) : demi-Cooper (3 min à fond après échauffement) pour mesurer vVO2max, si HRV en base."
   },
   "semaineDansBloc": 1,
   "decharge": false,
   "avantDebut": false,
   "debut": "2026-08-31",
   "termine": false
  },
  "semaineLabel": "2026-S36",
  "semaineDebut": "2026-08-31",
  "semaineFin": "2026-09-06"
 }
};
