// AUTO-GENERATED by scripts/carnet.js — 2026-09-29T17:00:28.744Z
// Ne pas éditer : relancer sync.command.
window.CARNET = {
 "generatedAt": "2026-09-29T17:00:28.744Z",
 "semaine": {
  "label": "S40",
  "start": "2026-09-27T22:00:00.000Z",
  "sec": 3611,
  "km": 0,
  "count": 2,
  "disc": {
   "natation": {
    "sec": 0,
    "km": 0,
    "count": 0
   },
   "velo": {
    "sec": 0,
    "km": 0,
    "count": 0
   },
   "course": {
    "sec": 0,
    "km": 0,
    "count": 0
   },
   "autre": {
    "sec": 3611,
    "km": 0,
    "count": 2
   }
  },
  "autres": {
   "Renfo": 1,
   "Pilates": 1
  },
  "vs4": -86,
  "avg4sec": 25280
 },
 "charge": {
  "ratio": 0.97,
  "statut": "ok",
  "aigue": 123,
  "chronique": 127,
  "sum7": 80,
  "sum28": 569,
  "nb28": 26,
  "typique": 140
 },
 "intensite": {
  "easy": 99,
  "hard": 1,
  "n": 27,
  "seuil": 140
 },
 "regularite": {
  "seancesParSemaine": 6.8,
  "joursOff28": 10,
  "plusLongue28": {
   "sec": 7781,
   "disc": "autre",
   "name": "Crossfit",
   "date": "2026-09-06T08:04:09.000Z"
  },
  "plusLongueSemaine": {
   "sec": 2943,
   "disc": "autre",
   "name": "NST",
   "date": "2026-09-29T11:24:36.000Z"
  }
 },
 "derniere": {
  "id": 20377731703,
  "date": "2026-09-29T11:24:36.000Z",
  "disc": "autre",
  "type": "Workout",
  "typeLabel": "Renfo",
  "name": "NST",
  "sec": 2943,
  "km": 0,
  "hr": 138,
  "watts": null,
  "effort": 48,
  "photo": null,
  "contenu": null,
  "contenuFr": null,
  "note": null
 },
 "joursDepuis": 0,
 "recentes": [
  {
   "id": 20377731703,
   "date": "2026-09-29T11:24:36.000Z",
   "disc": "autre",
   "type": "Workout",
   "typeLabel": "Renfo",
   "name": "NST",
   "sec": 2943,
   "km": 0,
   "hr": 138,
   "watts": null,
   "effort": 48,
   "photo": null,
   "contenu": null,
   "contenuFr": null,
   "note": null
  },
  {
   "id": 20373564500,
   "date": "2026-09-29T04:58:37.000Z",
   "disc": "autre",
   "type": "Pilates",
   "typeLabel": "Pilates",
   "name": "Pilates le matin",
   "sec": 668,
   "km": 0,
   "hr": 87,
   "watts": null,
   "effort": 1,
   "photo": null,
   "contenu": null,
   "contenuFr": null,
   "note": null
  },
  {
   "id": 20314668352,
   "date": "2026-09-24T17:41:19.000Z",
   "disc": "autre",
   "type": "Workout",
   "typeLabel": "Renfo",
   "name": "NST",
   "sec": 3589,
   "km": 0,
   "hr": 107,
   "watts": null,
   "effort": 11,
   "photo": null,
   "contenu": null,
   "contenuFr": null,
   "note": null
  },
  {
   "id": 20295275941,
   "date": "2026-09-23T10:28:03.000Z",
   "disc": "autre",
   "type": "Workout",
   "typeLabel": "Renfo",
   "name": "Entraînement le midi",
   "sec": 5167,
   "km": 0,
   "hr": 114,
   "watts": null,
   "effort": 20,
   "photo": null,
   "contenu": null,
   "contenuFr": null,
   "note": null
  },
  {
   "id": 20282879407,
   "date": "2026-09-22T14:16:12.000Z",
   "disc": "autre",
   "type": "Workout",
   "typeLabel": "Renfo",
   "name": "Entraînement dans l'après-midi",
   "sec": 2968,
   "km": 0,
   "hr": 103,
   "watts": null,
   "effort": 9,
   "photo": null,
   "contenu": null,
   "contenuFr": null,
   "note": null
  },
  {
   "id": 20276473179,
   "date": "2026-09-22T03:34:42.000Z",
   "disc": "course",
   "type": "Run",
   "typeLabel": null,
   "name": "Course à pied le matin",
   "sec": 2773,
   "km": 7.3,
   "hr": 132,
   "watts": 253,
   "effort": 31,
   "photo": "https://dgtzuqphqg23d.cloudfront.net/VWIqHclRoyIXqbBBCbh3bRjQ6loKWjkam0ohA0QRDFE-1536x2048.jpg",
   "contenu": null,
   "contenuFr": null,
   "note": null
  },
  {
   "id": 20269787481,
   "date": "2026-09-21T15:42:39.000Z",
   "disc": "autre",
   "type": "Workout",
   "typeLabel": "Renfo",
   "name": "Entraînement dans l'après-midi",
   "sec": 3818,
   "km": 0,
   "hr": 125,
   "watts": null,
   "effort": 29,
   "photo": null,
   "contenu": null,
   "contenuFr": null,
   "note": null
  },
  {
   "id": 20262736389,
   "date": "2026-09-21T03:49:59.000Z",
   "disc": "autre",
   "type": "Pilates",
   "typeLabel": "Pilates",
   "name": "Discipline",
   "sec": 1533,
   "km": 0,
   "hr": 97,
   "watts": null,
   "effort": 4,
   "photo": null,
   "contenu": null,
   "contenuFr": null,
   "note": null
  },
  {
   "id": 20237903928,
   "date": "2026-09-19T09:02:14.000Z",
   "disc": "autre",
   "type": "Workout",
   "typeLabel": "Renfo",
   "name": "NST",
   "sec": 4172,
   "km": 0,
   "hr": 114,
   "watts": null,
   "effort": 17,
   "photo": null,
   "contenu": null,
   "contenuFr": null,
   "note": null
  },
  {
   "id": 20235454779,
   "date": "2026-09-19T05:26:04.000Z",
   "disc": "course",
   "type": "Run",
   "typeLabel": null,
   "name": "Course à pied le matin",
   "sec": 3584,
   "km": 10.3,
   "hr": 138,
   "watts": 292,
   "effort": 63,
   "photo": null,
   "contenu": null,
   "contenuFr": null,
   "note": null
  }
 ],
 "semaines": [
  {
   "label": "S28",
   "start": "2026-07-05T22:00:00.000Z",
   "sec": 7029,
   "km": 3.6,
   "count": 4,
   "effort": 38,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "course": {
     "sec": 1159,
     "km": 3.6481999999999997,
     "count": 1
    },
    "autre": {
     "sec": 5870,
     "km": 0,
     "count": 3
    }
   },
   "autres": {
    "Pilates": 3
   }
  },
  {
   "label": "S29",
   "start": "2026-07-12T22:00:00.000Z",
   "sec": 6227,
   "km": 6.3,
   "count": 3,
   "effort": 53,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "course": {
     "sec": 2189,
     "km": 6.2961,
     "count": 1
    },
    "autre": {
     "sec": 4038,
     "km": 0,
     "count": 2
    }
   },
   "autres": {
    "Pilates": 2
   }
  },
  {
   "label": "S30",
   "start": "2026-07-19T22:00:00.000Z",
   "sec": 1794,
   "km": 4.5,
   "count": 1,
   "effort": 7,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "course": {
     "sec": 1794,
     "km": 4.5223,
     "count": 1
    },
    "autre": {
     "sec": 0,
     "km": 0,
     "count": 0
    }
   },
   "autres": {}
  },
  {
   "label": "S31",
   "start": "2026-07-26T22:00:00.000Z",
   "sec": 1273,
   "km": 0,
   "count": 1,
   "effort": 2,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "course": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "autre": {
     "sec": 1273,
     "km": 0,
     "count": 1
    }
   },
   "autres": {
    "Pilates": 1
   }
  },
  {
   "label": "S32",
   "start": "2026-08-02T22:00:00.000Z",
   "sec": 5975,
   "km": 10.6,
   "count": 3,
   "effort": 65,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "course": {
     "sec": 3854,
     "km": 10.5503,
     "count": 2
    },
    "autre": {
     "sec": 2121,
     "km": 0,
     "count": 1
    }
   },
   "autres": {
    "Pilates": 1
   }
  },
  {
   "label": "S33",
   "start": "2026-08-09T22:00:00.000Z",
   "sec": 0,
   "km": 0,
   "count": 0,
   "effort": 0,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "course": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "autre": {
     "sec": 0,
     "km": 0,
     "count": 0
    }
   },
   "autres": {}
  },
  {
   "label": "S34",
   "start": "2026-08-16T22:00:00.000Z",
   "sec": 20448,
   "km": 46.1,
   "count": 7,
   "effort": 195,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 3332,
     "km": 26.6785,
     "count": 1
    },
    "course": {
     "sec": 7093,
     "km": 19.4335,
     "count": 3
    },
    "autre": {
     "sec": 10023,
     "km": 0,
     "count": 3
    }
   },
   "autres": {
    "Renfo": 2,
    "Pilates": 1
   }
  },
  {
   "label": "S35",
   "start": "2026-08-23T22:00:00.000Z",
   "sec": 31067,
   "km": 37.2,
   "count": 10,
   "effort": 181,
   "disc": {
    "natation": {
     "sec": 1564,
     "km": 1,
     "count": 2
    },
    "velo": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "course": {
     "sec": 14241,
     "km": 36.1853,
     "count": 3
    },
    "autre": {
     "sec": 15262,
     "km": 0,
     "count": 5
    }
   },
   "autres": {
    "Renfo": 3,
    "Pilates": 2
   }
  },
  {
   "label": "S36",
   "start": "2026-08-30T22:00:00.000Z",
   "sec": 37685,
   "km": 34.8,
   "count": 8,
   "effort": 190,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 2813,
     "km": 19.6587,
     "count": 1
    },
    "course": {
     "sec": 3971,
     "km": 10.1253,
     "count": 1
    },
    "autre": {
     "sec": 30901,
     "km": 5.0252,
     "count": 6
    }
   },
   "autres": {
    "Renfo": 4,
    "Marche": 1,
    "Pilates": 1
   }
  },
  {
   "label": "S37",
   "start": "2026-09-06T22:00:00.000Z",
   "sec": 23284,
   "km": 0.3,
   "count": 6,
   "effort": 121,
   "disc": {
    "natation": {
     "sec": 408,
     "km": 0.25,
     "count": 1
    },
    "velo": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "course": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "autre": {
     "sec": 22876,
     "km": 0,
     "count": 5
    }
   },
   "autres": {
    "Renfo": 5
   }
  },
  {
   "label": "S38",
   "start": "2026-09-13T22:00:00.000Z",
   "sec": 20304,
   "km": 10.3,
   "count": 7,
   "effort": 125,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "course": {
     "sec": 3584,
     "km": 10.3115,
     "count": 1
    },
    "autre": {
     "sec": 16720,
     "km": 0,
     "count": 6
    }
   },
   "autres": {
    "Renfo": 3,
    "Pilates": 3
   }
  },
  {
   "label": "S39",
   "start": "2026-09-20T22:00:00.000Z",
   "sec": 19848,
   "km": 7.3,
   "count": 6,
   "effort": 104,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "course": {
     "sec": 2773,
     "km": 7.2824,
     "count": 1
    },
    "autre": {
     "sec": 17075,
     "km": 0,
     "count": 5
    }
   },
   "autres": {
    "Renfo": 4,
    "Pilates": 1
   }
  },
  {
   "label": "S40",
   "start": "2026-09-27T22:00:00.000Z",
   "sec": 3611,
   "km": 0,
   "count": 2,
   "effort": 49,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "course": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "autre": {
     "sec": 3611,
     "km": 0,
     "count": 2
    }
   },
   "autres": {
    "Renfo": 1,
    "Pilates": 1
   }
  }
 ]
};
