// AUTO-GENERATED by scripts/carnet.js — 2026-09-04T16:00:23.555Z
// Ne pas éditer : relancer sync.command.
window.CARNET = {
 "generatedAt": "2026-09-04T16:00:23.555Z",
 "semaine": {
  "label": "S36",
  "start": "2026-08-30T22:00:00.000Z",
  "sec": 18455,
  "km": 24.7,
  "count": 5,
  "disc": {
   "natation": {
    "sec": 0,
    "km": 0,
    "count": 0
   },
   "velo": {
    "sec": 2813,
    "km": 19.6587,
    "count": 1
   },
   "course": {
    "sec": 0,
    "km": 0,
    "count": 0
   },
   "autre": {
    "sec": 15642,
    "km": 5.0252,
    "count": 4
   }
  },
  "autres": {
   "Renfo": 2,
   "Marche": 1,
   "Pilates": 1
  },
  "vs4": 28,
  "avg4sec": 14373
 },
 "charge": {
  "ratio": 1.2,
  "statut": "ok",
  "aigue": 147,
  "chronique": 123,
  "sum7": 140,
  "sum28": 447,
  "nb28": 22,
  "typique": 140
 },
 "intensite": {
  "easy": 94,
  "hard": 6,
  "n": 22,
  "seuil": 140
 },
 "regularite": {
  "seancesParSemaine": 5,
  "joursOff28": 14,
  "plusLongue28": {
   "sec": 6573,
   "disc": "autre",
   "name": "Entraînement dans l'après-midi",
   "date": "2026-09-04T13:04:48.000Z"
  },
  "plusLongueSemaine": {
   "sec": 6573,
   "disc": "autre",
   "name": "Entraînement dans l'après-midi",
   "date": "2026-09-04T13:04:48.000Z"
  }
 },
 "derniere": {
  "id": 20034525453,
  "date": "2026-09-04T13:04:48.000Z",
  "disc": "autre",
  "type": "Workout",
  "typeLabel": "Renfo",
  "name": "Entraînement dans l'après-midi",
  "sec": 6573,
  "km": 0,
  "hr": 124,
  "watts": null,
  "effort": 39,
  "photo": null,
  "contenu": null,
  "contenuFr": null,
  "note": null
 },
 "joursDepuis": 0,
 "recentes": [
  {
   "id": 20034525453,
   "date": "2026-09-04T13:04:48.000Z",
   "disc": "autre",
   "type": "Workout",
   "typeLabel": "Renfo",
   "name": "Entraînement dans l'après-midi",
   "sec": 6573,
   "km": 0,
   "hr": 124,
   "watts": null,
   "effort": 39,
   "photo": null,
   "contenu": null,
   "contenuFr": null,
   "note": null
  },
  {
   "id": 20030829525,
   "date": "2026-09-04T08:27:52.000Z",
   "disc": "autre",
   "type": "Workout",
   "typeLabel": "Renfo",
   "name": "Séance altero",
   "sec": 4111,
   "km": 0,
   "hr": 107,
   "watts": null,
   "effort": 12,
   "photo": null,
   "contenu": null,
   "contenuFr": null,
   "note": null
  },
  {
   "id": 19985028094,
   "date": "2026-09-01T02:12:54.000Z",
   "disc": "velo",
   "type": "VirtualRide",
   "typeLabel": null,
   "name": "Zwift - High-Cadence Builds",
   "sec": 2813,
   "km": 19.7,
   "hr": 112,
   "watts": 138,
   "effort": 8,
   "photo": "https://dgtzuqphqg23d.cloudfront.net/ZvoPiHOYQYwA_gNyvFejSDKT-FlYGfDGt4gi05lWO70-2048x1430.jpg",
   "contenu": "High-Cadence Builds (Zwift - Whole Lotta Lava)\nStructure: 30sec @150w / 30sec @175w / 30sec @130w / 30sec @150w / 30sec @175w (répété)\nRécupération: 5 min @120w entre blocs\nPuissance moyenne: 139w\nDistance: 19.6 km\nDurée: 46:31\nCalories: 369 kcal\nFC moyenne: 112 bpm\nPic puissance: 502w\nPic FC: 126 bpm",
   "contenuFr": "High-Cadence Builds (Zwift - Whole Lotta Lava)\nStructure: 30sec @150w / 30sec @175w / 30sec @130w / 30sec @150w / 30sec @175w (répété)\nRécupération: 5 min @120w entre blocs\nPuissance moyenne: 139w\nDistance: 19.6 km\nDurée: 46:31\nCalories: 369 kcals\nFC moyenne: 112 bpms\nPic puissance: 502w\nPic FC: 126 bpms",
   "note": null
  },
  {
   "id": 19977764573,
   "date": "2026-08-31T15:03:31.000Z",
   "disc": "autre",
   "type": "Walk",
   "typeLabel": "Marche",
   "name": "Marche dans l'après-midi",
   "sec": 3081,
   "km": 5,
   "hr": 106,
   "watts": null,
   "effort": 9,
   "photo": null,
   "contenu": null,
   "contenuFr": null,
   "note": null
  },
  {
   "id": 19971709902,
   "date": "2026-08-31T05:47:12.000Z",
   "disc": "autre",
   "type": "Pilates",
   "typeLabel": "Pilates",
   "name": "Programme",
   "sec": 1877,
   "km": 0,
   "hr": 81,
   "watts": null,
   "effort": 3,
   "photo": "https://dgtzuqphqg23d.cloudfront.net/y5_SdluIwq9Wq3neeBL5F2fd2-db1N1Coa2qzd6_ung-942x2048.jpg",
   "contenu": "Mobilité + gainage (nuit courte)\n\n5 min de respiration nasale + rotations d'épaules et de bassin, debout\nDislocations à l'élastique (bras tendus, l'élastique passe de devant à derrière la tête) 2×10, lentement\nSots press au PVC (barre en plastique au-dessus de la tête, on s'accroupit sous la barre) 2×8\nOverhead squat au PVC : 3× tenir 30 s en position basse, barre au-dessus de la tête, bras tendus\nMobilité chevilles genou-mur : 2×10 par jambe (genou avance vers le mur, talon collé au sol)\nGainage : planche ventrale 3×40 s + planche latérale 2×30 s par côté\n5 min étirement des fléchisseurs de hanche (fente genou au sol, bassin qui rentre)",
   "contenuFr": "Mobilité + gainage (nuit courte)\n5 min de respiration nasale + rotations d'épaules et de bassin, debout\nDislocations à l'élastique (bras tendus, l'élastique passe de devant à derrière la tête) 2×10, lentement\nSots press au PVC (barre en plastique au-dessus de la tête, on s'accroupit sous la barre) 2×8\nsquat barre au-dessus de la tête au PVC : 3× tenir 30 s en position basse, barre au-dessus de la tête, bras tendus\nMobilité chevilles genou-mur : 2×10 par jambe (genou avance vers le mur, talon collé au sol)\nGainage : planche ventrale 3×40 s + planche latérale 2×30 s par côté\n5 min étirement des fléchisseurs de hanche (fente genou au sol, bassin qui rentre)",
   "note": null
  },
  {
   "id": 19953230142,
   "date": "2026-08-29T17:15:39.000Z",
   "disc": "course",
   "type": "Run",
   "typeLabel": null,
   "name": "Course à pied en soirée",
   "sec": 3566,
   "km": 10.1,
   "hr": 140,
   "watts": 283,
   "effort": 37,
   "photo": null,
   "contenu": null,
   "contenuFr": null,
   "note": null
  },
  {
   "id": 19945359558,
   "date": "2026-08-29T07:20:49.000Z",
   "disc": "autre",
   "type": "Workout",
   "typeLabel": "Renfo",
   "name": "Crossfit",
   "sec": 4497,
   "km": 0,
   "hr": 123,
   "watts": null,
   "effort": 32,
   "photo": "https://dgtzuqphqg23d.cloudfront.net/VAKECToE3SwJHjaCudl6NxBRymVRUzLo4HuCoZrkfv8-2048x1536.jpg",
   "contenu": "Samedi 29 Août\n\nWarm up\n30\"/20\"/10\" x 3' ergo\nthen,\n5+5 scorpions\n5+5 reverse scorpions\n5 russian baby makers\nthen, 2 rounds :\n10 scap pull-ups\n10 kipping\n10 pvc overhead squat\n\nTeam of 3\n\n1. AMRAP 12'\nP1 : max cals ski\nP2 : Rest\nP3 : 5 power snatch @60/40 Rx\n10 pull-up / chest to bar\n\nREST 2'\n\n2. AMRAP 12'\nP1 : max cals echo\nP2 : Rest\nP3 : 5 overhead squat @60/40 Rx\n10 pull-ups / chest to bar\n\nSwitch quand P3 a terminé son round\n\nScaling\nElite : 70/45 + chest\nINT : 50/35 + pull-ups\nSC : 40/30 + jumping\nDeb : 30/25 + ring row",
   "contenuFr": "Samedi 29 Août\néchauffement\n30\"/20\"/10\" x 3' ergo\npuis,\n5+5 scorpions\n5+5 reverses scorpions\n5 russians baby makers\npuis, 2 tours :\n10 scaps traction\n10 kippings\n10 pvcs squat barre au-dessus de la tête\nTeam of 3\n1. AMRAP (maximum de tours) 12'\nP1 : max cals ski erg\nP2 : récupération\nP3 : 5 arrachés debout @60/40 Rx\n10 tractions / chest to bar\nrécupération 2 min\n2. AMRAP (maximum de tours) 12'\nP1 : max cals echo\nP2 : récupération\nP3 : 5 squats barre au-dessus de la tête @60/40 Rx\n10 tractions / chest to bar\non change quand P3 a terminé son tour\nScaling\nElite : 70/45 + chest\nINT : 50/35 + traction\nSC : 40/30 + jumping\nDeb : 30/25 + tirage horizontal aux anneaux",
   "note": "Team of 3 fait à 30 kg (entre Déb 30 et Sc 40). Difficulté sur les overhead squats : manque de mobilité épaules/thoracique/chevilles à travailler."
  },
  {
   "id": 19935452223,
   "date": "2026-08-28T11:56:49.000Z",
   "disc": "autre",
   "type": "Pilates",
   "typeLabel": "Pilates",
   "name": "Discipline",
   "sec": 2485,
   "km": 0,
   "hr": 111,
   "watts": null,
   "effort": 7,
   "photo": null,
   "contenu": null,
   "contenuFr": null,
   "note": null
  },
  {
   "id": 19932012756,
   "date": "2026-08-28T04:37:09.000Z",
   "disc": "course",
   "type": "Run",
   "typeLabel": null,
   "name": "Course à pied le matin",
   "sec": 5951,
   "km": 13.8,
   "hr": 125,
   "watts": 225,
   "effort": 23,
   "photo": null,
   "contenu": null,
   "contenuFr": null,
   "note": null
  },
  {
   "id": 19925423492,
   "date": "2026-08-27T15:41:59.000Z",
   "disc": "natation",
   "type": "Swim",
   "typeLabel": null,
   "name": "Natation dans l'après-midi",
   "sec": 875,
   "km": 0.5,
   "hr": 117,
   "watts": null,
   "effort": 12,
   "photo": null,
   "contenu": null,
   "contenuFr": null,
   "note": null
  }
 ],
 "semaines": [
  {
   "label": "S24",
   "start": "2026-06-07T22:00:00.000Z",
   "sec": 1463,
   "km": 0,
   "count": 1,
   "effort": 4,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "course": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "autre": {
     "sec": 1463,
     "km": 0,
     "count": 1
    }
   },
   "autres": {
    "Pilates": 1
   }
  },
  {
   "label": "S25",
   "start": "2026-06-14T22:00:00.000Z",
   "sec": 1066,
   "km": 3.4,
   "count": 1,
   "effort": 19,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "course": {
     "sec": 1066,
     "km": 3.4285,
     "count": 1
    },
    "autre": {
     "sec": 0,
     "km": 0,
     "count": 0
    }
   },
   "autres": {}
  },
  {
   "label": "S26",
   "start": "2026-06-21T22:00:00.000Z",
   "sec": 13391,
   "km": 19.8,
   "count": 5,
   "effort": 72,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "course": {
     "sec": 7971,
     "km": 19.767699999999998,
     "count": 2
    },
    "autre": {
     "sec": 5420,
     "km": 0,
     "count": 3
    }
   },
   "autres": {
    "Pilates": 3
   }
  },
  {
   "label": "S27",
   "start": "2026-06-28T22:00:00.000Z",
   "sec": 5818,
   "km": 0,
   "count": 4,
   "effort": 17,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "course": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "autre": {
     "sec": 5818,
     "km": 0,
     "count": 4
    }
   },
   "autres": {
    "Pilates": 4
   }
  },
  {
   "label": "S28",
   "start": "2026-07-05T22:00:00.000Z",
   "sec": 7029,
   "km": 3.6,
   "count": 4,
   "effort": 38,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "course": {
     "sec": 1159,
     "km": 3.6481999999999997,
     "count": 1
    },
    "autre": {
     "sec": 5870,
     "km": 0,
     "count": 3
    }
   },
   "autres": {
    "Pilates": 3
   }
  },
  {
   "label": "S29",
   "start": "2026-07-12T22:00:00.000Z",
   "sec": 6227,
   "km": 6.3,
   "count": 3,
   "effort": 53,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "course": {
     "sec": 2189,
     "km": 6.2961,
     "count": 1
    },
    "autre": {
     "sec": 4038,
     "km": 0,
     "count": 2
    }
   },
   "autres": {
    "Pilates": 2
   }
  },
  {
   "label": "S30",
   "start": "2026-07-19T22:00:00.000Z",
   "sec": 1794,
   "km": 4.5,
   "count": 1,
   "effort": 7,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "course": {
     "sec": 1794,
     "km": 4.5223,
     "count": 1
    },
    "autre": {
     "sec": 0,
     "km": 0,
     "count": 0
    }
   },
   "autres": {}
  },
  {
   "label": "S31",
   "start": "2026-07-26T22:00:00.000Z",
   "sec": 1273,
   "km": 0,
   "count": 1,
   "effort": 2,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "course": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "autre": {
     "sec": 1273,
     "km": 0,
     "count": 1
    }
   },
   "autres": {
    "Pilates": 1
   }
  },
  {
   "label": "S32",
   "start": "2026-08-02T22:00:00.000Z",
   "sec": 5975,
   "km": 10.6,
   "count": 3,
   "effort": 65,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "course": {
     "sec": 3854,
     "km": 10.5503,
     "count": 2
    },
    "autre": {
     "sec": 2121,
     "km": 0,
     "count": 1
    }
   },
   "autres": {
    "Pilates": 1
   }
  },
  {
   "label": "S33",
   "start": "2026-08-09T22:00:00.000Z",
   "sec": 0,
   "km": 0,
   "count": 0,
   "effort": 0,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "course": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "autre": {
     "sec": 0,
     "km": 0,
     "count": 0
    }
   },
   "autres": {}
  },
  {
   "label": "S34",
   "start": "2026-08-16T22:00:00.000Z",
   "sec": 20448,
   "km": 46.1,
   "count": 7,
   "effort": 195,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 3332,
     "km": 26.6785,
     "count": 1
    },
    "course": {
     "sec": 7093,
     "km": 19.4335,
     "count": 3
    },
    "autre": {
     "sec": 10023,
     "km": 0,
     "count": 3
    }
   },
   "autres": {
    "Renfo": 2,
    "Pilates": 1
   }
  },
  {
   "label": "S35",
   "start": "2026-08-23T22:00:00.000Z",
   "sec": 31067,
   "km": 37.2,
   "count": 10,
   "effort": 181,
   "disc": {
    "natation": {
     "sec": 1564,
     "km": 1,
     "count": 2
    },
    "velo": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "course": {
     "sec": 14241,
     "km": 36.1853,
     "count": 3
    },
    "autre": {
     "sec": 15262,
     "km": 0,
     "count": 5
    }
   },
   "autres": {
    "Renfo": 3,
    "Pilates": 2
   }
  },
  {
   "label": "S36",
   "start": "2026-08-30T22:00:00.000Z",
   "sec": 18455,
   "km": 24.7,
   "count": 5,
   "effort": 71,
   "disc": {
    "natation": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "velo": {
     "sec": 2813,
     "km": 19.6587,
     "count": 1
    },
    "course": {
     "sec": 0,
     "km": 0,
     "count": 0
    },
    "autre": {
     "sec": 15642,
     "km": 5.0252,
     "count": 4
    }
   },
   "autres": {
    "Renfo": 2,
    "Marche": 1,
    "Pilates": 1
   }
  }
 ]
};
