// AUTO-GENERATED by scripts/sync.js — 2026-08-30T04:00:23.829Z
// Do not edit manually — run sync.command to refresh.

(function() {
  // Deep-merge real Strava data into window.ATHLETES.benoit
  const real = {
  "forme": {
    "chargeAigue": 244,
    "chronique": 110,
    "ratio": 2.22,
    "statut": "surcharge"
  },
  "derniereSéance": {
    "date": "Aujourd'hui, 21h15",
    "type": "Course à pied",
    "icone": "🏃",
    "durée": "59min",
    "distance": "10.1 km",
    "puissanceMoyenne": "282.6W",
    "ressenti": 5,
    "ressentLabel": "Excellente séance",
    "note": "Course à pied en soirée",
    "stravaId": 19953230142
  },
  "alerte": {
    "type": "surcharge",
    "titre": "Attention : signaux de surcharge détectés",
    "message": "Ratio à 2.22 — au-dessus du seuil critique (1.3). Réduis l'intensité cette semaine.",
    "action": "Voir mes options de récupération"
  },
  "seances": [
    {
      "date": "Hier",
      "type": "Course à pied",
      "icone": "🏃",
      "duree": "59min",
      "distance": "10.1 km",
      "ressenti": 5,
      "charge": 37,
      "ratio": 2.22
    },
    {
      "date": "Hier",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "1h14",
      "distance": "—",
      "ressenti": 5,
      "charge": 32,
      "ratio": 2.22
    },
    {
      "date": "Av.-hier",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "41min",
      "distance": "—",
      "ressenti": 5,
      "charge": 7,
      "ratio": 2.22
    },
    {
      "date": "Av.-hier",
      "type": "Course à pied",
      "icone": "🏃",
      "duree": "1h39",
      "distance": "13.8 km",
      "ressenti": 5,
      "charge": 23,
      "ratio": 2.22
    },
    {
      "date": "Jeu 27",
      "type": "Natation",
      "icone": "🏊",
      "duree": "14min",
      "distance": "500 m",
      "ressenti": 5,
      "charge": 12,
      "ratio": 2.22
    },
    {
      "date": "Mer 26",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "50min",
      "distance": "—",
      "ressenti": 5,
      "charge": 13,
      "ratio": 2.22
    },
    {
      "date": "Mer 26",
      "type": "Course à pied",
      "icone": "🏃",
      "duree": "1h18",
      "distance": "12.2 km",
      "ressenti": 5,
      "charge": 22,
      "ratio": 2.22
    },
    {
      "date": "Mar 25",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "45min",
      "distance": "—",
      "ressenti": 5,
      "charge": 12,
      "ratio": 2.22
    },
    {
      "date": "Mar 25",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "41min",
      "distance": "—",
      "ressenti": 5,
      "charge": 7,
      "ratio": 2.22
    },
    {
      "date": "Lun 24",
      "type": "Natation",
      "icone": "🏊",
      "duree": "11min",
      "distance": "500 m",
      "ressenti": 5,
      "charge": 16,
      "ratio": 2.22
    },
    {
      "date": "Dim 23",
      "type": "Course à pied",
      "icone": "🏃",
      "duree": "44min",
      "distance": "6.7 km",
      "ressenti": 5,
      "charge": 24,
      "ratio": 2.22
    },
    {
      "date": "Dim 23",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "1h11",
      "distance": "—",
      "ressenti": 5,
      "charge": 39,
      "ratio": 2.22
    },
    {
      "date": "Sam 22",
      "type": "Vélo (home)",
      "icone": "🚴",
      "duree": "55min",
      "distance": "26.7 km",
      "ressenti": 5,
      "charge": 22,
      "ratio": 2.22
    },
    {
      "date": "Sam 22",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "30min",
      "distance": "—",
      "ressenti": 5,
      "charge": 4,
      "ratio": 2.22
    },
    {
      "date": "Ven 21",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "1h05",
      "distance": "—",
      "ressenti": 5,
      "charge": 23,
      "ratio": 2.22
    }
  ],
  "disciplines": [
    {
      "nom": "Vélo",
      "icone": "🚴",
      "count": 1,
      "couleur": "#6C63FF"
    },
    {
      "nom": "Course",
      "icone": "🏃",
      "count": 11,
      "couleur": "#00D4AA"
    },
    {
      "nom": "Natation",
      "icone": "🏊",
      "count": 2,
      "couleur": "#FF6B6B"
    },
    {
      "nom": "Renfo",
      "icone": "💪",
      "count": 16,
      "couleur": "#FFD166"
    }
  ],
  "historique": {
    "semaines": [
      "S24",
      "S25",
      "S26",
      "S27",
      "S28",
      "S29",
      "S30",
      "S31",
      "S32",
      "S33",
      "S34",
      "S35"
    ],
    "chargeAigue": [
      4,
      19,
      72,
      17,
      38,
      53,
      7,
      2,
      65,
      0,
      195,
      181
    ],
    "chargeChronique": [
      4,
      12,
      32,
      28,
      37,
      45,
      29,
      25,
      32,
      19,
      66,
      110
    ],
    "volumeSec": [
      1463,
      1066,
      13391,
      5818,
      7029,
      6227,
      1794,
      1273,
      5975,
      0,
      20448,
      31067
    ],
    "seancesCount": [
      1,
      1,
      5,
      4,
      4,
      3,
      1,
      1,
      3,
      0,
      7,
      10
    ]
  },
  "_lastSync": "2026-08-30T04:00:23.829Z",
  "_activitiesCount": 423
};

  if (window.ATHLETES && window.ATHLETES.benoit) {
    // Merge forme fields (preserve hrv, sleep etc. that come from Whoop)
    Object.assign(window.ATHLETES.benoit.forme, real.forme);
    window.ATHLETES.benoit.derniereSéance = real.derniereSéance;
    window.ATHLETES.benoit.alerte         = real.alerte;
    window.ATHLETES.benoit.seances        = real.seances;
    window.ATHLETES.benoit.disciplines    = real.disciplines;
    window.ATHLETES.benoit.historique     = real.historique;
    window.ATHLETES.benoit._lastSync      = real._lastSync;
  }
})();
