// AUTO-GENERATED by scripts/sync.js — 2026-08-03T19:00:18.080Z
// Do not edit manually — run sync.command to refresh.

(function() {
  // Deep-merge real Strava data into window.ATHLETES.benoit
  const real = {
  "forme": {
    "chargeAigue": 2,
    "chronique": 25,
    "ratio": 0.08,
    "statut": "sous-charge"
  },
  "derniereSéance": {
    "date": "Il y a 3 jours",
    "type": "Renforcement",
    "icone": "💪",
    "durée": "21min",
    "distance": null,
    "puissanceMoyenne": null,
    "ressenti": 5,
    "ressentLabel": "Excellente séance",
    "note": "Pilates en soirée",
    "stravaId": 19532389226
  },
  "alerte": {
    "type": "sous-charge",
    "titre": "Tu peux progresser davantage",
    "message": "Ratio à 0.08 — ton corps est bien récupéré. C'est le bon moment pour augmenter le volume.",
    "action": "Voir comment augmenter ma charge"
  },
  "seances": [
    {
      "date": "Jeu 30",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "21min",
      "distance": "—",
      "ressenti": 5,
      "charge": 2,
      "ratio": 0.08
    },
    {
      "date": "Dim 26",
      "type": "Course à pied",
      "icone": "🏃",
      "duree": "29min",
      "distance": "4.5 km",
      "ressenti": 5,
      "charge": 7,
      "ratio": 0.08
    },
    {
      "date": "Dim 19",
      "type": "Course à pied",
      "icone": "🏃",
      "duree": "36min",
      "distance": "6.3 km",
      "ressenti": 5,
      "charge": 48,
      "ratio": 0.08
    },
    {
      "date": "Mer 15",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "16min",
      "distance": "—",
      "ressenti": 5,
      "charge": 2,
      "ratio": 0.08
    },
    {
      "date": "Mar 14",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "50min",
      "distance": "—",
      "ressenti": 5,
      "charge": 3,
      "ratio": 0.08
    },
    {
      "date": "Dim 12",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "29min",
      "distance": "—",
      "ressenti": 5,
      "charge": 5,
      "ratio": 0.08
    },
    {
      "date": "Dim 12",
      "type": "Course à pied",
      "icone": "🏃",
      "duree": "19min",
      "distance": "3.6 km",
      "ressenti": 5,
      "charge": 22,
      "ratio": 0.08
    },
    {
      "date": "Sam 11",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "24min",
      "distance": "—",
      "ressenti": 5,
      "charge": 3,
      "ratio": 0.08
    },
    {
      "date": "Jeu 9",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "44min",
      "distance": "—",
      "ressenti": 5,
      "charge": 8,
      "ratio": 0.08
    },
    {
      "date": "Dim 5",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "7min",
      "distance": "—",
      "ressenti": 4,
      "charge": 4,
      "ratio": 0.08
    },
    {
      "date": "Sam 4",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "35min",
      "distance": "—",
      "ressenti": 5,
      "charge": 6,
      "ratio": 0.08
    },
    {
      "date": "Mar 30",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "28min",
      "distance": "—",
      "ressenti": 5,
      "charge": 4,
      "ratio": 0.08
    },
    {
      "date": "Lun 29",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "24min",
      "distance": "—",
      "ressenti": 5,
      "charge": 3,
      "ratio": 0.08
    },
    {
      "date": "Dim 28",
      "type": "Course à pied",
      "icone": "🏃",
      "duree": "1h16",
      "distance": "9.8 km",
      "ressenti": 5,
      "charge": 24,
      "ratio": 0.08
    },
    {
      "date": "Dim 28",
      "type": "Course à pied",
      "icone": "🏃",
      "duree": "56min",
      "distance": "9.9 km",
      "ressenti": 5,
      "charge": 36,
      "ratio": 0.08
    }
  ],
  "disciplines": [
    {
      "nom": "Course",
      "icone": "🏃",
      "count": 6,
      "couleur": "#00D4AA"
    },
    {
      "nom": "Renfo",
      "icone": "💪",
      "count": 14,
      "couleur": "#FFD166"
    }
  ],
  "historique": {
    "semaines": [
      "S21",
      "S22",
      "S23",
      "S24",
      "S25",
      "S26",
      "S27",
      "S28",
      "S29",
      "S30",
      "S31",
      "S32"
    ],
    "chargeAigue": [
      65,
      114,
      75,
      4,
      19,
      72,
      17,
      38,
      53,
      7,
      2,
      0
    ],
    "chargeChronique": [
      65,
      90,
      85,
      65,
      53,
      43,
      28,
      37,
      45,
      29,
      25,
      16
    ],
    "volumeSec": [
      14912,
      16391,
      10969,
      1463,
      1066,
      13391,
      5818,
      7029,
      6227,
      1794,
      1273,
      0
    ],
    "seancesCount": [
      5,
      7,
      6,
      1,
      1,
      5,
      4,
      4,
      3,
      1,
      1,
      0
    ]
  },
  "_lastSync": "2026-08-03T19:00:18.080Z",
  "_activitiesCount": 403
};

  if (window.ATHLETES && window.ATHLETES.benoit) {
    // Merge forme fields (preserve hrv, sleep etc. that come from Whoop)
    Object.assign(window.ATHLETES.benoit.forme, real.forme);
    window.ATHLETES.benoit.derniereSéance = real.derniereSéance;
    window.ATHLETES.benoit.alerte         = real.alerte;
    window.ATHLETES.benoit.seances        = real.seances;
    window.ATHLETES.benoit.disciplines    = real.disciplines;
    window.ATHLETES.benoit.historique     = real.historique;
    window.ATHLETES.benoit._lastSync      = real._lastSync;
  }
})();
