// AUTO-GENERATED by scripts/sync.js — 2026-07-07T04:00:11.364Z
// Do not edit manually — run sync.command to refresh.

(function() {
  // Deep-merge real Strava data into window.ATHLETES.benoit
  const real = {
  "forme": {
    "chargeAigue": 14,
    "chronique": 28,
    "ratio": 0.5,
    "statut": "sous-charge"
  },
  "derniereSéance": {
    "date": "Hier, 9h32",
    "type": "Renforcement",
    "icone": "💪",
    "durée": "7min",
    "distance": null,
    "puissanceMoyenne": null,
    "ressenti": 5,
    "ressentLabel": "Excellente séance",
    "note": "Pilates le matin",
    "stravaId": 19184202738
  },
  "alerte": {
    "type": "sous-charge",
    "titre": "Tu peux progresser davantage",
    "message": "Ratio à 0.5 — ton corps est bien récupéré. C'est le bon moment pour augmenter le volume.",
    "action": "Voir comment augmenter ma charge"
  },
  "seances": [
    {
      "date": "Av.-hier",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "7min",
      "distance": "—",
      "ressenti": 4,
      "charge": 4,
      "ratio": 0.5
    },
    {
      "date": "Sam 4",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "35min",
      "distance": "—",
      "ressenti": 5,
      "charge": 6,
      "ratio": 0.5
    },
    {
      "date": "Mar 30",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "28min",
      "distance": "—",
      "ressenti": 5,
      "charge": 4,
      "ratio": 0.5
    },
    {
      "date": "Lun 29",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "24min",
      "distance": "—",
      "ressenti": 5,
      "charge": 3,
      "ratio": 0.5
    },
    {
      "date": "Dim 28",
      "type": "Course à pied",
      "icone": "🏃",
      "duree": "1h16",
      "distance": "9.8 km",
      "ressenti": 5,
      "charge": 24,
      "ratio": 0.5
    },
    {
      "date": "Dim 28",
      "type": "Course à pied",
      "icone": "🏃",
      "duree": "56min",
      "distance": "9.9 km",
      "ressenti": 5,
      "charge": 36,
      "ratio": 0.5
    },
    {
      "date": "Ven 26",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "37min",
      "distance": "—",
      "ressenti": 5,
      "charge": 5,
      "ratio": 0.5
    },
    {
      "date": "Jeu 25",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "29min",
      "distance": "—",
      "ressenti": 5,
      "charge": 4,
      "ratio": 0.5
    },
    {
      "date": "Lun 22",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "23min",
      "distance": "—",
      "ressenti": 5,
      "charge": 3,
      "ratio": 0.5
    },
    {
      "date": "Ven 19",
      "type": "Course à pied",
      "icone": "🏃",
      "duree": "17min",
      "distance": "3.4 km",
      "ressenti": 5,
      "charge": 19,
      "ratio": 0.5
    },
    {
      "date": "Dim 14",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "24min",
      "distance": "—",
      "ressenti": 5,
      "charge": 4,
      "ratio": 0.5
    },
    {
      "date": "Sam 6",
      "type": "Renforcement",
      "icone": "💪",
      "duree": "27min",
      "distance": "—",
      "ressenti": 5,
      "charge": 3,
      "ratio": 0.5
    },
    {
      "date": "Jeu 4",
      "type": "Natation",
      "icone": "🏊",
      "duree": "28min",
      "distance": "1,10 km",
      "ressenti": 5,
      "charge": 18,
      "ratio": 0.5
    },
    {
      "date": "Mer 3",
      "type": "Course à pied",
      "icone": "🏃",
      "duree": "56min",
      "distance": "10.1 km",
      "ressenti": 5,
      "charge": 26,
      "ratio": 0.5
    },
    {
      "date": "Mar 2",
      "type": "Natation",
      "icone": "🏊",
      "duree": "24min",
      "distance": "850 m",
      "ressenti": 5,
      "charge": 12,
      "ratio": 0.5
    }
  ],
  "disciplines": [
    {
      "nom": "Vélo",
      "icone": "🚴",
      "count": 3,
      "couleur": "#6C63FF"
    },
    {
      "nom": "Course",
      "icone": "🏃",
      "count": 5,
      "couleur": "#00D4AA"
    },
    {
      "nom": "Natation",
      "icone": "🏊",
      "count": 4,
      "couleur": "#FF6B6B"
    },
    {
      "nom": "Renfo",
      "icone": "💪",
      "count": 19,
      "couleur": "#FFD166"
    },
    {
      "nom": "Autre",
      "icone": "🏅",
      "count": 1,
      "couleur": "#8B8FA8"
    }
  ],
  "historique": {
    "semaines": [
      "S17",
      "S18",
      "S19",
      "S20",
      "S21",
      "S22",
      "S23",
      "S24",
      "S25",
      "S26",
      "S27",
      "S28"
    ],
    "chargeAigue": [
      247,
      225,
      72,
      21,
      65,
      114,
      75,
      4,
      19,
      72,
      17,
      0
    ],
    "chargeChronique": [
      247,
      236,
      181,
      141,
      96,
      68,
      69,
      65,
      53,
      43,
      28,
      27
    ],
    "volumeSec": [
      22310,
      27525,
      8062,
      6726,
      14912,
      16391,
      10969,
      1463,
      1066,
      13391,
      5818,
      0
    ],
    "seancesCount": [
      11,
      12,
      5,
      4,
      5,
      7,
      6,
      1,
      1,
      5,
      4,
      0
    ]
  },
  "_lastSync": "2026-07-07T04:00:11.364Z",
  "_activitiesCount": 394
};

  if (window.ATHLETES && window.ATHLETES.benoit) {
    // Merge forme fields (preserve hrv, sleep etc. that come from Whoop)
    Object.assign(window.ATHLETES.benoit.forme, real.forme);
    window.ATHLETES.benoit.derniereSéance = real.derniereSéance;
    window.ATHLETES.benoit.alerte         = real.alerte;
    window.ATHLETES.benoit.seances        = real.seances;
    window.ATHLETES.benoit.disciplines    = real.disciplines;
    window.ATHLETES.benoit.historique     = real.historique;
    window.ATHLETES.benoit._lastSync      = real._lastSync;
  }
})();
