// AUTO-GENERATED by scripts/sync.js — ne pas éditer.
window.NST = {
 "2026-S36": {
  "source": "NST",
  "importedAt": "2026-08-29T14:51:45.294Z",
  "jours": [
   {
    "jour": "Lun",
    "titre": "HAUT DU CORPS (Press) · semaine de transition S4/4",
    "contenu": "WARM UP\n1 tour : 60/60 s étirement dynamique pectoraux + 60/60 s étirement dynamique dorsaux\n4 min Ski ou Rameur (20 s facile / 10 s difficile)\npuis 40 close grip bench press à la barre à vide + 20 close grip ring rows + 20 close grip bench press léger + 20 close grip ring rows\npuis montée en charge au close grip bench press\n\nABSOLUTE STRENGTH (Press)\n4 séries : 10 close grip bench press — repos 75 s — 5-8 bench plyo push-ups — repos 75 s\nCharges légères à modérées, exécution parfaite et vitesse : 45-55 % du 1RM bench (40-45 % avec élastiques)\nProgression du bloc : S1 5RM · S2 3RM · S3 1RM · S4 transition (actuelle)\n\nSTRENGTH ENDURANCE (Press/Pull)\nEMOM 12 min : minute 1 = 20 s suspension menton au-dessus de la barre (pronation) · minute 2 = 20 s maintien haut de dips aux anneaux\nNiveaux : Elite = gilet lesté · RX = poids de corps · Intermédiaire = élastique ou appui sur box\n\nCONDITIONING (Threshold) — intervalles au seuil, 75-85 % d'effort\nRX : AMRAP 20 min — 4 bar muscle-ups / 8 strict HSPU / 15-11 cal rameur, 1 min de repos entre les tours, ordre inversé à chaque tour\nIntermédiaire : 3 bar muscle-ups / 6 strict HSPU / 12-9 cal rameur\nScaled : 6 kipping pull-ups ou chest-to-bar / 6 kipping HSPU / 12-9 cal rameur\n\n(OPTIONNEL) STRENGTH ACCESSORY\n2-3 séries pour la qualité : une série max de incline DB bicep curls (6-10 kg) + une série max de banded anchored sit-ups"
   },
   {
    "jour": "Mar",
    "titre": "BAS DU CORPS (Front Squat) · semaine de transition",
    "contenu": "WARM UP\nOptionnel : 60/60 s étirement dynamique de la hanche antérieure\n2000/1800 m vélo C2 en 30 s facile / 30 s modéré\npuis mini-bande : 3 × (5 squats + 5 s de maintien à la parallèle sur la dernière rep) et 3 × (5 ponts fessiers + 5 s en haut sur la dernière rep)\npuis montée en charge aux front squats avec élastique\nSans mini-bande : 30 s wall sit + 10 good-mornings à la barre + 30 s de maintien de squat à la parallèle barre en back rack + 5 kang squats\n\nABSOLUTE STRENGTH (Front Squat)\n4 séries : 10 front squats sur banc ou box basse — repos 75 s — 3 seated box jumps — repos 75 s\nCharges légères à modérées : 40-50 % du 1RM front squat (30-40 % avec élastiques)\nTempo 21X1 : descente contrôlée sur le banc, courte pause, remontée la plus explosive possible\nNote NST : le banc limite l'amplitude, on garde la mécanique du front squat avec une contrainte faible\nProgression du bloc : S1 5RM · S2 3RM · S3 1RM · S4 transition (actuelle)\n\nSTRENGTH ENDURANCE (Hinge)\n3 séries, 2 min de repos entre les séries : 10/10 soulevé de terre roumain à une jambe avec haltère (jambe libre en appui)\nCharges : Elite 32,5 kg+ · RX 25 kg · Intermédiaire 17,5 kg\nTempo : descente contrôlée, arrêt juste avant que les haltères touchent le sol, remontée rapide\n\nSTRENGTH-SPEED (Clean) & CONDITIONING — VO2max, 90 % d'effort, zone 4-5\nRX : EMOM jusqu'à l'échec (20 min max) — 5 toes-to-bar / 5 power cleans (52 kg) / 5 burpees face à la barre\nIntermédiaire : 4 toes-to-bar / 4 power cleans / 4 burpees face à la barre\nScore : nombre de tours complets (1 à 20)\nProgression du bloc : S1 3-position power clean · S2 2-position · S3 1 power clean · S4 transition\n\n(OPTIONNEL) STRENGTH ACCESSORY\n2-3 séries pour la qualité : une série difficile de loaded GHD hip extensions (viser 10+ reps) + une série difficile de banded hamstring curls (viser 20+ reps), en s'arrêtant 2-4 reps avant l'échec"
   }
  ]
 }
};
