// AUTO-GENERATED by scripts/sync.js — ne pas éditer.
window.NST = {
 "2026-S36": {
  "source": "NST",
  "importedAt": "2026-08-29T04:52:53.437Z",
  "jours": [
   {
    "jour": "Lun",
    "titre": "HAUT DU CORPS (Press) · semaine de transition S4/4",
    "contenu": "WARM UP\n1 tour : 60/60 s étirement dynamique pectoraux + 60/60 s étirement dynamique dorsaux\n4 min Ski ou Rameur (20 s facile / 10 s difficile)\npuis 40 close grip bench press à la barre à vide + 20 close grip ring rows + 20 close grip bench press (charge légère) + 20 close grip ring rows\npuis montée en charge au close grip bench press\n\nABSOLUTE STRENGTH (Press)\n4 séries : 10 close grip bench press — repos 75 s — 5-8 bench plyo push-ups — repos 75 s\nCharges légères à modérées, exécution parfaite et vitesse : 45-55 % du 1RM bench (40-45 % avec élastiques)\nProgression du bloc : S1 5RM · S2 3RM · S3 1RM · S4 transition (actuelle)\n\nSTRENGTH ENDURANCE (Press/Pull)\nEMOM 12 min : minute 1 = 20 s suspension menton au-dessus de la barre (pronation) · minute 2 = 20 s maintien haut de dips aux anneaux\nNiveaux : Elite = gilet lesté · RX = poids de corps · Intermédiaire = élastique ou appui sur box\n\nCONDITIONING (Threshold) — intervalles au seuil, 75-85 % d'effort\nRX : AMRAP 20 min — 4 bar muscle-ups / 8 strict HSPU / 15-11 cal rameur, 1 min de repos entre les tours, on inverse l'ordre à chaque tour\nIntermédiaire : 3 bar muscle-ups / 6 strict HSPU / 12-9 cal rameur\nScaled : 6 kipping pull-ups ou chest-to-bar / 6 kipping HSPU / 12-9 cal rameur\nScore : total des reps et calories sur 20 min\n\n(OPTIONNEL) STRENGTH ACCESSORY\n2-3 séries pour la qualité, repos libre : une série max de incline DB bicep curls (6-10 kg) + une série max de banded anchored sit-ups"
   },
   {
    "jour": "Mar",
    "titre": "BAS DU CORPS (Front Squat) · semaine de transition",
    "contenu": "WARM UP\nABSOLUTE STRENGTH (Front Squat)\nSTRENGTH ENDURANCE (Hinge / charnière de hanche)\nSTRENGTH-SPEED (Clean) & CONDITIONING\n(OPTIONNEL) STRENGTH ACCESSORY\nDetail complet a recuperer sur FITR"
   }
  ]
 }
};
