// AUTO-GENERATED by scripts/sync.js — 2026-09-03T17:00:30.867Z
// Strava observations for scoring.js (merged via window.WEARABLE_OBS)
window.WEARABLE_OBS = (window.WEARABLE_OBS || []).concat([
  {
    "signal_id": "acute_chronic_ratio",
    "raw_value": 1.2,
    "athlete_id": "benoit",
    "timestamp": 1788454829738
  },
  {
    "signal_id": "last_session_rpe",
    "raw_value": 1,
    "athlete_id": "benoit",
    "timestamp": 1788235974000
  },
  {
    "signal_id": "aerobic_decoupling",
    "raw_value": 0,
    "athlete_id": "benoit",
    "timestamp": 1787891829000
  },
  {
    "signal_id": "aerobic_decoupling",
    "raw_value": 0.9,
    "athlete_id": "benoit",
    "timestamp": 1787717504000
  }
]);
