// AUTO-GENERATED by scripts/sync.js — 2026-08-06T19:00:18.427Z
// Strava observations for scoring.js (merged via window.WEARABLE_OBS)
window.WEARABLE_OBS = (window.WEARABLE_OBS || []).concat([
  {
    "signal_id": "acute_chronic_ratio",
    "raw_value": 1.67,
    "athlete_id": "benoit",
    "timestamp": 1786042817478
  },
  {
    "signal_id": "last_session_rpe",
    "raw_value": 1,
    "athlete_id": "benoit",
    "timestamp": 1785995045000
  }
]);
