// AUTO-GENERATED by scripts/sync.js — 2026-05-13T21:13:02.528Z
// Strava observations for scoring.js (merged via window.WEARABLE_OBS)
window.WEARABLE_OBS = (window.WEARABLE_OBS || []).concat([
  {
    "signal_id": "acute_chronic_ratio",
    "raw_value": 0.05,
    "athlete_id": "benoit",
    "timestamp": 1778699851346
  },
  {
    "signal_id": "last_session_rpe",
    "raw_value": 1,
    "athlete_id": "benoit",
    "timestamp": 1778473505000
  },
  {
    "signal_id": "aerobic_decoupling",
    "raw_value": 0,
    "athlete_id": "benoit",
    "timestamp": 1777649919000
  },
  {
    "signal_id": "aerobic_decoupling",
    "raw_value": 0,
    "athlete_id": "benoit",
    "timestamp": 1775030561000
  }
]);
