// AUTO-GENERATED by scripts/programme.js — ne pas éditer.
window.PROGRAMME = {
 "nom": "Hybride Automne 2026",
 "debut": "2026-08-31",
 "fin": "2026-11-22",
 "objectif": "Devenir hybride : tenir une heure de course en aisance ET des charges propres en CrossFit, sans blessure.",
 "cible": {
  "date": "2026-11-21",
  "libelle": "Test hybride maison (samedi 21/11) : 10 km en aisance sous 55 min (FC moyenne < 155) le matin, puis l'après-midi 5 tractions strictes enchaînées + back squat 5 reps à 1,2× poids de corps (≈ 95 kg) + 500 m rameur."
 },
 "depart": {
  "course": "12,2 km en 1h19 à 130 bpm (26/08) ; allure normalisée à 140 bpm : 5:52/km",
  "force": "Back squat 80 kg sur 5 reps (27/08) ; WOD à 30 kg (hang squat clean / thrusters) ; strict pull-ups en finisher",
  "volume": "≈ 4 h/semaine sur 3 mois creux, remontée à 5-6 h fin août",
  "physio": "HRV base 38 ms, FC repos 49-50, sommeil 7 h 30-8 h"
 },
 "blocs": [
  {
   "id": 1,
   "nom": "Fondation",
   "semaines": 4,
   "debut": "2026-08-31",
   "but": "Reposer la régularité et la tolérance tendineuse. Aucune intensité en course.",
   "doubles": [
    3,
    3,
    4,
    2
   ],
   "priorites": [
    "Bi-quotidien progressif : 3 doublés en semaine 1 et 2, 4 en semaine 3, 2 en semaine de décharge (matin aérobie facile, soir qualité)",
    "6 jours actifs par semaine, volume 5 h → 7 h, progression max +15 %/semaine",
    "Toute la course en aisance stricte (FC < 140), sortie longue jusqu'à 1 h 15",
    "2 séances de force par semaine (dont la box NST), charges modérées, technique avant charge",
    "Réintroduire vélo (1×/sem) et natation (1×/sem) comme volume sans impact",
    "Aucune séance de fractionné course — le corps encaisse encore la reprise"
   ],
   "test": "Semaine 4 (décharge) : demi-Cooper (3 min à fond après échauffement) pour mesurer vVO2max, si HRV en base."
  },
  {
   "id": 2,
   "nom": "Développement",
   "semaines": 4,
   "debut": "2026-09-28",
   "but": "Installer le stimulus VO2max façon Billat et monter la force.",
   "doubles": [
    4,
    5,
    5,
    3
   ],
   "priorites": [
    "Bi-quotidien : 4 doublés puis 5 (matin aérobie ou skill, soir qualité) — plafond 5 tant que le HRV n'est pas stable dans sa base",
    "1 séance VO2max/semaine en 30/30 calés sur la vVO2max mesurée (2×(8→12)×30/30, récup 3')",
    "Volume 6 h → 7 h, sortie longue 1 h 15 → 1 h 30 à sensation (variations libres autorisées)",
    "Force : 5×5 progressif (+2,5 kg par semaine quand les 5 reps sortent propres), viser 87,5-90 kg en fin de bloc",
    "Polarisation stricte : viser 80 % du temps sous 140 bpm, 20 % très dur, rien entre les deux",
    "Jamais deux séances dures consécutives ; le dur se mérite par une nuit correcte (HRV en base)"
   ],
   "test": "Semaine 8 (décharge) : refaire le demi-Cooper et comparer ; test tractions strictes max."
  },
  {
   "id": 3,
   "nom": "Expression",
   "semaines": 4,
   "debut": "2026-10-26",
   "but": "Rendre la forme utilisable : combiner endurance et force dans la même journée.",
   "doubles": [
    5,
    5,
    4,
    2
   ],
   "priorites": [
    "Bi-quotidien stabilisé à 5 doublés, réduit à 2 la semaine du test",
    "Maintenir 1 séance VO2max/semaine (30/30 ou 3×3 min à vVO2max)",
    "1 séance combinée par semaine (course en aisance puis force dans la journée) pour préparer le test",
    "Force : chercher le back squat 5 reps à 1,2× poids de corps (≈ 95 kg) et 5 tractions strictes enchaînées",
    "Volume stable 6 h 30-7 h, dernière semaine allégée de 40 % avant le test",
    "Semaine 12 : test hybride le samedi 21/11"
   ],
   "test": "Semaine 12 : test hybride (10 km en aisance + force l'après-midi)."
  }
 ],
 "reglesPermanentes": [
  "La semaine de décharge (4e de chaque bloc) : -40 % de volume, on garde la fréquence et un rappel d'intensité court.",
  "Hiérarchie des séances : 1) programme NST (prioritaire, non modifiable), 2) WOD de la box du club, 3) séances ajoutées par le coach (endurance, VO2max, récup).",
  "Les séances CrossFit viennent de la programmation du club (WOD au tableau, lu sur photo) : le coach construit AUTOUR, il ne rajoute jamais une séance de force le lendemain d'un jour lourd à la box. Le module NST arrivera en complément (parrainage) — à intégrer quand Benoît l'aura.",
  "Si HRV en statut LOW deux matins de suite, ou FC repos > base +5 bpm : la séance dure de la semaine saute, remplacée par de l'aisance.",
  "Toute douleur tendineuse (Achille, genou) = arrêt de la course, vélo/natation à la place, jusqu'à disparition complète.",
  "Le petit-déjeuner est fixe ; midi = boîte chantier ; les repas suivent la séance du jour."
 ],
 "courant": {
  "programme": "Hybride Automne 2026",
  "objectif": "Devenir hybride : tenir une heure de course en aisance ET des charges propres en CrossFit, sans blessure.",
  "cible": {
   "date": "2026-11-21",
   "libelle": "Test hybride maison (samedi 21/11) : 10 km en aisance sous 55 min (FC moyenne < 155) le matin, puis l'après-midi 5 tractions strictes enchaînées + back squat 5 reps à 1,2× poids de corps (≈ 95 kg) + 500 m rameur."
  },
  "semaineDansCycle": 1,
  "totalSemaines": 12,
  "bloc": {
   "id": 1,
   "nom": "Fondation",
   "semaines": 4,
   "debut": "2026-08-31",
   "but": "Reposer la régularité et la tolérance tendineuse. Aucune intensité en course.",
   "doubles": [
    3,
    3,
    4,
    2
   ],
   "priorites": [
    "Bi-quotidien progressif : 3 doublés en semaine 1 et 2, 4 en semaine 3, 2 en semaine de décharge (matin aérobie facile, soir qualité)",
    "6 jours actifs par semaine, volume 5 h → 7 h, progression max +15 %/semaine",
    "Toute la course en aisance stricte (FC < 140), sortie longue jusqu'à 1 h 15",
    "2 séances de force par semaine (dont la box NST), charges modérées, technique avant charge",
    "Réintroduire vélo (1×/sem) et natation (1×/sem) comme volume sans impact",
    "Aucune séance de fractionné course — le corps encaisse encore la reprise"
   ],
   "test": "Semaine 4 (décharge) : demi-Cooper (3 min à fond après échauffement) pour mesurer vVO2max, si HRV en base."
  },
  "semaineDansBloc": 1,
  "decharge": false,
  "avantDebut": false,
  "debut": "2026-08-31",
  "termine": false
 },
 "generatedAt": "2026-08-30T05:00:22.008Z"
};
