// AUTO-GENERATED by scripts/garmin.py — 2026-09-03T07:00:12
// Ne pas éditer : relancer sync.command.
window.SOMMEIL = {
 "generatedAt": "2026-09-03T07:00:12",
 "jours": [
  {
   "date": "2026-06-05",
   "sommeil": {
    "total_min": 543,
    "profond_min": 138,
    "leger_min": 252,
    "paradoxal_min": 153,
    "eveil_min": 6,
    "score": 88,
    "debut": 1780607796000,
    "fin": 1780640736000,
    "fc_repos_nuit": 50,
    "spo2_moy": null,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 33,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 32,
    "haut": 46
   },
   "fc_repos": 50,
   "body_battery": {
    "max": 60,
    "min": 14,
    "reveil": 60
   },
   "stress_moy": 26,
   "pas": 7016,
   "readiness": {
    "score": 63,
    "niveau": "MODERATE"
   }
  },
  {
   "date": "2026-06-06",
   "sommeil": {
    "total_min": 530,
    "profond_min": 103,
    "leger_min": 223,
    "paradoxal_min": 204,
    "eveil_min": 2,
    "score": 85,
    "debut": 1780702786000,
    "fin": 1780734706000,
    "fc_repos_nuit": 48,
    "spo2_moy": 97.0,
    "respiration_moy": 14.0
   },
   "hrv_nuit": 40,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 32,
    "haut": 46
   },
   "fc_repos": 48,
   "body_battery": {
    "max": 90,
    "min": 34,
    "reveil": 90
   },
   "stress_moy": 24,
   "pas": 14256,
   "readiness": {
    "score": 70,
    "niveau": "MODERATE"
   }
  },
  {
   "date": "2026-06-07",
   "sommeil": {
    "total_min": 413,
    "profond_min": 87,
    "leger_min": 224,
    "paradoxal_min": 102,
    "eveil_min": 0,
    "score": 84,
    "debut": 1780792372000,
    "fin": 1780817152000,
    "fc_repos_nuit": 49,
    "spo2_moy": 95.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 47,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 32,
    "haut": 46
   },
   "fc_repos": 49,
   "body_battery": {
    "max": 91,
    "min": 26,
    "reveil": 91
   },
   "stress_moy": 28,
   "pas": 10203,
   "readiness": {
    "score": 79,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-06-08",
   "sommeil": {
    "total_min": 331,
    "profond_min": 92,
    "leger_min": 141,
    "paradoxal_min": 99,
    "eveil_min": 0,
    "score": 74,
    "debut": 1780877078000,
    "fin": 1780896966000,
    "fc_repos_nuit": 49,
    "spo2_moy": 97.0,
    "respiration_moy": 14.0
   },
   "hrv_nuit": 42,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 32,
    "haut": 46
   },
   "fc_repos": 49,
   "body_battery": {
    "max": 80,
    "min": 14,
    "reveil": 80
   },
   "stress_moy": 33,
   "pas": 8939,
   "readiness": {
    "score": 73,
    "niveau": "MODERATE"
   }
  },
  {
   "date": "2026-06-09",
   "sommeil": {
    "total_min": 440,
    "profond_min": 136,
    "leger_min": 187,
    "paradoxal_min": 117,
    "eveil_min": 0,
    "score": 96,
    "debut": 1780960807000,
    "fin": 1780987207000,
    "fc_repos_nuit": 50,
    "spo2_moy": 95.0,
    "respiration_moy": 14.0
   },
   "hrv_nuit": 43,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 32,
    "haut": 46
   },
   "fc_repos": 50,
   "body_battery": {
    "max": 85,
    "min": 21,
    "reveil": 85
   },
   "stress_moy": 29,
   "pas": 10023,
   "readiness": {
    "score": 91,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-06-10",
   "sommeil": {
    "total_min": 348,
    "profond_min": 97,
    "leger_min": 213,
    "paradoxal_min": 38,
    "eveil_min": 0,
    "score": 71,
    "debut": 1781049187000,
    "fin": 1781070067000,
    "fc_repos_nuit": 50,
    "spo2_moy": 96.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 43,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 32,
    "haut": 46
   },
   "fc_repos": 50,
   "body_battery": {
    "max": 78,
    "min": 12,
    "reveil": 78
   },
   "stress_moy": 35,
   "pas": 13285,
   "readiness": {
    "score": 85,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-06-11",
   "sommeil": {
    "total_min": 483,
    "profond_min": 145,
    "leger_min": 226,
    "paradoxal_min": 112,
    "eveil_min": 1,
    "score": 90,
    "debut": 1781131219000,
    "fin": 1781160259000,
    "fc_repos_nuit": 47,
    "spo2_moy": 96.0,
    "respiration_moy": 14.0
   },
   "hrv_nuit": 39,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 32,
    "haut": 46
   },
   "fc_repos": 47,
   "body_battery": {
    "max": 92,
    "min": 20,
    "reveil": 92
   },
   "stress_moy": 33,
   "pas": 9748,
   "readiness": {
    "score": 99,
    "niveau": "PRIME"
   }
  },
  {
   "date": "2026-06-12",
   "sommeil": {
    "total_min": 385,
    "profond_min": 136,
    "leger_min": 135,
    "paradoxal_min": 114,
    "eveil_min": 0,
    "score": 79,
    "debut": 1781221169000,
    "fin": 1781244269000,
    "fc_repos_nuit": 48,
    "spo2_moy": 95.0,
    "respiration_moy": 14.0
   },
   "hrv_nuit": 39,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 32,
    "haut": 45
   },
   "fc_repos": 48,
   "body_battery": {
    "max": 80,
    "min": 15,
    "reveil": 80
   },
   "stress_moy": 35,
   "pas": 6544,
   "readiness": {
    "score": 88,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-06-13",
   "sommeil": {
    "total_min": 428,
    "profond_min": 140,
    "leger_min": 154,
    "paradoxal_min": 134,
    "eveil_min": 0,
    "score": 84,
    "debut": 1781305438000,
    "fin": 1781331118000,
    "fc_repos_nuit": 48,
    "spo2_moy": 96.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 41,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 32,
    "haut": 45
   },
   "fc_repos": 48,
   "body_battery": {
    "max": 84,
    "min": 5,
    "reveil": 84
   },
   "stress_moy": 44,
   "pas": 6874,
   "readiness": {
    "score": 91,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-06-14",
   "sommeil": {
    "total_min": 459,
    "profond_min": 114,
    "leger_min": 221,
    "paradoxal_min": 124,
    "eveil_min": 1,
    "score": 77,
    "debut": 1781392159000,
    "fin": 1781419759000,
    "fc_repos_nuit": 52,
    "spo2_moy": 96.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 33,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 32,
    "haut": 46
   },
   "fc_repos": 52,
   "body_battery": {
    "max": 51,
    "min": 5,
    "reveil": 51
   },
   "stress_moy": 47,
   "pas": 5903,
   "readiness": {
    "score": 75,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-06-15",
   "sommeil": {
    "total_min": 389,
    "profond_min": 83,
    "leger_min": 166,
    "paradoxal_min": 140,
    "eveil_min": 0,
    "score": 68,
    "debut": 1781479944000,
    "fin": 1781503284000,
    "fc_repos_nuit": 52,
    "spo2_moy": 95.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 35,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 32,
    "haut": 46
   },
   "fc_repos": 52,
   "body_battery": {
    "max": 45,
    "min": 5,
    "reveil": 45
   },
   "stress_moy": 45,
   "pas": 13808,
   "readiness": {
    "score": 78,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-06-16",
   "sommeil": {
    "total_min": 327,
    "profond_min": 88,
    "leger_min": 206,
    "paradoxal_min": 33,
    "eveil_min": 0,
    "score": 66,
    "debut": 1781570599000,
    "fin": 1781590219000,
    "fc_repos_nuit": 53,
    "spo2_moy": 97.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 38,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 32,
    "haut": 46
   },
   "fc_repos": 53,
   "body_battery": {
    "max": 46,
    "min": 5,
    "reveil": 46
   },
   "stress_moy": 42,
   "pas": 9474,
   "readiness": {
    "score": 64,
    "niveau": "MODERATE"
   }
  },
  {
   "date": "2026-06-17",
   "sommeil": {
    "total_min": 350,
    "profond_min": 69,
    "leger_min": 207,
    "paradoxal_min": 74,
    "eveil_min": 0,
    "score": 67,
    "debut": 1781655138000,
    "fin": 1781676138000,
    "fc_repos_nuit": 52,
    "spo2_moy": 96.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 36,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 32,
    "haut": 46
   },
   "fc_repos": 52,
   "body_battery": {
    "max": 42,
    "min": 5,
    "reveil": 42
   },
   "stress_moy": 41,
   "pas": 10910,
   "readiness": {
    "score": 61,
    "niveau": "MODERATE"
   }
  },
  {
   "date": "2026-06-18",
   "sommeil": {
    "total_min": 437,
    "profond_min": 72,
    "leger_min": 274,
    "paradoxal_min": 91,
    "eveil_min": 1,
    "score": 78,
    "debut": 1781736318000,
    "fin": 1781762598000,
    "fc_repos_nuit": 50,
    "spo2_moy": 97.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 38,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 32,
    "haut": 46
   },
   "fc_repos": 50,
   "body_battery": {
    "max": 56,
    "min": 5,
    "reveil": 56
   },
   "stress_moy": 29,
   "pas": 3608,
   "readiness": {
    "score": 74,
    "niveau": "MODERATE"
   }
  },
  {
   "date": "2026-06-19",
   "sommeil": {
    "total_min": 396,
    "profond_min": 83,
    "leger_min": 229,
    "paradoxal_min": 84,
    "eveil_min": 0,
    "score": 81,
    "debut": 1781825860000,
    "fin": 1781849620000,
    "fc_repos_nuit": 48,
    "spo2_moy": 96.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 40,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 33,
    "haut": 46
   },
   "fc_repos": 48,
   "body_battery": {
    "max": 83,
    "min": 18,
    "reveil": 83
   },
   "stress_moy": 27,
   "pas": 17307,
   "readiness": {
    "score": 63,
    "niveau": "MODERATE"
   }
  },
  {
   "date": "2026-06-20",
   "sommeil": {
    "total_min": 570,
    "profond_min": 130,
    "leger_min": 301,
    "paradoxal_min": 139,
    "eveil_min": 7,
    "score": 96,
    "debut": 1781909938000,
    "fin": 1781944558000,
    "fc_repos_nuit": 47,
    "spo2_moy": null,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 41,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 33,
    "haut": 46
   },
   "fc_repos": 47,
   "body_battery": {
    "max": 94,
    "min": 29,
    "reveil": 92
   },
   "stress_moy": 17,
   "pas": 1455,
   "readiness": {
    "score": 98,
    "niveau": "PRIME"
   }
  },
  {
   "date": "2026-06-21",
   "fc_repos": 54,
   "body_battery": {
    "max": 38,
    "min": 22,
    "reveil": null
   },
   "stress_moy": 41,
   "pas": 4548,
   "readiness": {
    "score": 94,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-06-22",
   "sommeil": {
    "total_min": 396,
    "profond_min": 85,
    "leger_min": 191,
    "paradoxal_min": 120,
    "eveil_min": 1,
    "score": 79,
    "debut": 1782085339000,
    "fin": 1782109159000,
    "fc_repos_nuit": 50,
    "spo2_moy": 96.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 37,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 33,
    "haut": 46
   },
   "fc_repos": 50,
   "body_battery": {
    "max": 69,
    "min": 14,
    "reveil": 69
   },
   "stress_moy": 39,
   "pas": 10787,
   "readiness": {
    "score": 100,
    "niveau": "PRIME"
   }
  },
  {
   "date": "2026-06-23",
   "fc_repos": 56,
   "body_battery": {
    "max": 83,
    "min": 11,
    "reveil": null
   },
   "stress_moy": 51,
   "pas": 11161,
   "readiness": {
    "score": 92,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-06-24",
   "sommeil": {
    "total_min": 257,
    "profond_min": 121,
    "leger_min": 105,
    "paradoxal_min": 31,
    "eveil_min": 0,
    "score": 57,
    "debut": 1782256519000,
    "fin": 1782271939000,
    "fc_repos_nuit": 50,
    "spo2_moy": 96.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 42,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 33,
    "haut": 46
   },
   "fc_repos": 50,
   "body_battery": {
    "max": 57,
    "min": 7,
    "reveil": 56
   },
   "stress_moy": 33,
   "pas": 10265,
   "readiness": {
    "score": 78,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-06-25",
   "sommeil": {
    "total_min": 397,
    "profond_min": 116,
    "leger_min": 173,
    "paradoxal_min": 108,
    "eveil_min": 4,
    "score": 80,
    "debut": 1782343285000,
    "fin": 1782367345000,
    "fc_repos_nuit": 51,
    "spo2_moy": 95.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 35,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 33,
    "haut": 46
   },
   "fc_repos": 51,
   "body_battery": {
    "max": 64,
    "min": 10,
    "reveil": 64
   },
   "stress_moy": 21,
   "pas": 6869,
   "readiness": {
    "score": 55,
    "niveau": "MODERATE"
   }
  },
  {
   "date": "2026-06-26",
   "fc_repos": 55,
   "body_battery": {
    "max": 50,
    "min": 5,
    "reveil": null
   },
   "stress_moy": 54,
   "pas": 9853,
   "readiness": {
    "score": 83,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-06-27",
   "sommeil": {
    "total_min": 372,
    "profond_min": 61,
    "leger_min": 291,
    "paradoxal_min": 20,
    "eveil_min": 2,
    "score": 62,
    "debut": 1782518485000,
    "fin": 1782540925000,
    "fc_repos_nuit": 54,
    "spo2_moy": 96.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 32,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 33,
    "haut": 45
   },
   "fc_repos": 54,
   "body_battery": {
    "max": 33,
    "min": 5,
    "reveil": 33
   },
   "stress_moy": 42,
   "pas": 11778,
   "readiness": {
    "score": 72,
    "niveau": "MODERATE"
   }
  },
  {
   "date": "2026-06-28",
   "sommeil": {
    "total_min": 506,
    "profond_min": 102,
    "leger_min": 301,
    "paradoxal_min": 103,
    "eveil_min": 1,
    "score": 88,
    "debut": 1782595869000,
    "fin": 1782626289000,
    "fc_repos_nuit": 51,
    "spo2_moy": 96.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 38,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 33,
    "haut": 46
   },
   "fc_repos": 51,
   "body_battery": {
    "max": 65,
    "min": 5,
    "reveil": 65
   },
   "stress_moy": 47,
   "pas": 30342,
   "readiness": {
    "score": 1,
    "niveau": "POOR"
   }
  },
  {
   "date": "2026-06-29",
   "sommeil": {
    "total_min": 379,
    "profond_min": 78,
    "leger_min": 245,
    "paradoxal_min": 56,
    "eveil_min": 0,
    "score": 73,
    "debut": 1782688143000,
    "fin": 1782710883000,
    "fc_repos_nuit": 56,
    "spo2_moy": 96.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 31,
   "hrv_statut": "UNBALANCED",
   "hrv_base": {
    "bas": 33,
    "haut": 45
   },
   "fc_repos": 56,
   "body_battery": {
    "max": 32,
    "min": 5,
    "reveil": 32
   },
   "stress_moy": 51,
   "pas": 14375,
   "readiness": {
    "score": 1,
    "niveau": "POOR"
   }
  },
  {
   "date": "2026-06-30",
   "sommeil": {
    "total_min": 409,
    "profond_min": 85,
    "leger_min": 226,
    "paradoxal_min": 98,
    "eveil_min": 3,
    "score": 77,
    "debut": 1782773267000,
    "fin": 1782797987000,
    "fc_repos_nuit": 55,
    "spo2_moy": 94.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 35,
   "hrv_statut": "UNBALANCED",
   "hrv_base": {
    "bas": 33,
    "haut": 45
   },
   "fc_repos": 55,
   "body_battery": {
    "max": 36,
    "min": 5,
    "reveil": 36
   },
   "stress_moy": 50,
   "pas": 11766,
   "readiness": {
    "score": 3,
    "niveau": "POOR"
   }
  },
  {
   "date": "2026-07-01",
   "sommeil": {
    "total_min": 193,
    "profond_min": 81,
    "leger_min": 112,
    "paradoxal_min": 0,
    "eveil_min": 1,
    "score": 32,
    "debut": 1782865914000,
    "fin": 1782877554000,
    "fc_repos_nuit": 54,
    "spo2_moy": 95.0,
    "respiration_moy": 17.0
   },
   "hrv_nuit": 29,
   "hrv_statut": "LOW",
   "hrv_base": {
    "bas": 33,
    "haut": 45
   },
   "fc_repos": 54,
   "body_battery": {
    "max": 19,
    "min": 5,
    "reveil": 17
   },
   "stress_moy": 34,
   "pas": 6401,
   "readiness": {
    "score": 4,
    "niveau": "POOR"
   }
  },
  {
   "date": "2026-07-02",
   "sommeil": {
    "total_min": 360,
    "profond_min": 102,
    "leger_min": 172,
    "paradoxal_min": 86,
    "eveil_min": 0,
    "score": 81,
    "debut": 1782954985000,
    "fin": 1782976585000,
    "fc_repos_nuit": 50,
    "spo2_moy": 95.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 37,
   "hrv_statut": "LOW",
   "hrv_base": {
    "bas": 33,
    "haut": 45
   },
   "fc_repos": 50,
   "body_battery": {
    "max": 58,
    "min": 5,
    "reveil": 58
   },
   "stress_moy": 30,
   "pas": 8614,
   "readiness": {
    "score": 27,
    "niveau": "LOW"
   }
  },
  {
   "date": "2026-07-03",
   "sommeil": {
    "total_min": 379,
    "profond_min": 84,
    "leger_min": 174,
    "paradoxal_min": 121,
    "eveil_min": 0,
    "score": 81,
    "debut": 1783036171000,
    "fin": 1783058911000,
    "fc_repos_nuit": 48,
    "spo2_moy": 94.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 39,
   "hrv_statut": "UNBALANCED",
   "hrv_base": {
    "bas": 33,
    "haut": 45
   },
   "fc_repos": 48,
   "body_battery": {
    "max": 73,
    "min": 18,
    "reveil": 73
   },
   "stress_moy": 22,
   "pas": 7818,
   "readiness": {
    "score": 54,
    "niveau": "MODERATE"
   }
  },
  {
   "date": "2026-07-04",
   "sommeil": {
    "total_min": 462,
    "profond_min": 102,
    "leger_min": 251,
    "paradoxal_min": 109,
    "eveil_min": 1,
    "score": 99,
    "debut": 1783119685000,
    "fin": 1783147465000,
    "fc_repos_nuit": 47,
    "spo2_moy": 95.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 48,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 33,
    "haut": 45
   },
   "fc_repos": 47,
   "body_battery": {
    "max": 100,
    "min": 30,
    "reveil": 100
   },
   "stress_moy": 26,
   "pas": 7407,
   "readiness": {
    "score": 89,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-07-05",
   "sommeil": {
    "total_min": 435,
    "profond_min": 90,
    "leger_min": 255,
    "paradoxal_min": 90,
    "eveil_min": 10,
    "score": 89,
    "debut": 1783208071000,
    "fin": 1783234771000,
    "fc_repos_nuit": 47,
    "spo2_moy": 95.0,
    "respiration_moy": 14.0
   },
   "hrv_nuit": 43,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 33,
    "haut": 45
   },
   "fc_repos": 47,
   "body_battery": {
    "max": 99,
    "min": 33,
    "reveil": 99
   },
   "stress_moy": 24,
   "pas": 12408,
   "readiness": {
    "score": 97,
    "niveau": "PRIME"
   }
  },
  {
   "date": "2026-07-06",
   "sommeil": {
    "total_min": 301,
    "profond_min": 113,
    "leger_min": 116,
    "paradoxal_min": 72,
    "eveil_min": 0,
    "score": 68,
    "debut": 1783298861000,
    "fin": 1783316921000,
    "fc_repos_nuit": 48,
    "spo2_moy": 96.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 43,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 33,
    "haut": 45
   },
   "fc_repos": 48,
   "body_battery": {
    "max": 84,
    "min": 21,
    "reveil": 84
   },
   "stress_moy": 27,
   "pas": 10538,
   "readiness": {
    "score": 100,
    "niveau": "PRIME"
   }
  },
  {
   "date": "2026-07-07",
   "sommeil": {
    "total_min": 385,
    "profond_min": 100,
    "leger_min": 244,
    "paradoxal_min": 41,
    "eveil_min": 9,
    "score": 77,
    "debut": 1783382633000,
    "fin": 1783406273000,
    "fc_repos_nuit": 48,
    "spo2_moy": 97.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 45,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 33,
    "haut": 45
   },
   "fc_repos": 48,
   "body_battery": {
    "max": 91,
    "min": 19,
    "reveil": 90
   },
   "stress_moy": 29,
   "pas": 10794,
   "readiness": {
    "score": 94,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-07-08",
   "sommeil": {
    "total_min": 425,
    "profond_min": 116,
    "leger_min": 196,
    "paradoxal_min": 113,
    "eveil_min": 0,
    "score": 98,
    "debut": 1783467252000,
    "fin": 1783492752000,
    "fc_repos_nuit": 47,
    "spo2_moy": 96.0,
    "respiration_moy": 14.0
   },
   "hrv_nuit": 45,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 33,
    "haut": 45
   },
   "fc_repos": 47,
   "body_battery": {
    "max": 92,
    "min": 19,
    "reveil": 91
   },
   "stress_moy": 30,
   "pas": 8591,
   "readiness": {
    "score": 99,
    "niveau": "PRIME"
   }
  },
  {
   "date": "2026-07-09",
   "sommeil": {
    "total_min": 447,
    "profond_min": 60,
    "leger_min": 292,
    "paradoxal_min": 95,
    "eveil_min": 12,
    "score": 82,
    "debut": 1783556640000,
    "fin": 1783584180000,
    "fc_repos_nuit": 48,
    "spo2_moy": 96.0,
    "respiration_moy": 14.0
   },
   "hrv_nuit": 38,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 33,
    "haut": 45
   },
   "fc_repos": 48,
   "body_battery": {
    "max": 78,
    "min": 14,
    "reveil": 78
   },
   "stress_moy": 36,
   "pas": 9240,
   "readiness": {
    "score": 81,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-07-10",
   "sommeil": {
    "total_min": 407,
    "profond_min": 89,
    "leger_min": 233,
    "paradoxal_min": 85,
    "eveil_min": 2,
    "score": 81,
    "debut": 1783643091000,
    "fin": 1783667631000,
    "fc_repos_nuit": 50,
    "spo2_moy": 94.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 39,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 33,
    "haut": 45
   },
   "fc_repos": 50,
   "body_battery": {
    "max": 69,
    "min": 13,
    "reveil": 69
   },
   "stress_moy": 33,
   "pas": 9501,
   "readiness": {
    "score": 89,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-07-11",
   "sommeil": {
    "total_min": 469,
    "profond_min": 78,
    "leger_min": 288,
    "paradoxal_min": 103,
    "eveil_min": 19,
    "score": 84,
    "debut": 1783729165000,
    "fin": 1783758445000,
    "fc_repos_nuit": 51,
    "spo2_moy": 96.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 41,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 33,
    "haut": 45
   },
   "fc_repos": 51,
   "body_battery": {
    "max": 74,
    "min": 15,
    "reveil": 74
   },
   "stress_moy": 39,
   "pas": 10810,
   "readiness": {
    "score": 92,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-07-12",
   "sommeil": {
    "total_min": 448,
    "profond_min": 99,
    "leger_min": 245,
    "paradoxal_min": 104,
    "eveil_min": 10,
    "score": 88,
    "debut": 1783814059000,
    "fin": 1783841539000,
    "fc_repos_nuit": 51,
    "spo2_moy": 95.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 40,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 33,
    "haut": 45
   },
   "fc_repos": 51,
   "body_battery": {
    "max": 70,
    "min": 11,
    "reveil": 70
   },
   "stress_moy": 38,
   "pas": 17884,
   "readiness": {
    "score": 64,
    "niveau": "MODERATE"
   }
  },
  {
   "date": "2026-07-13",
   "sommeil": {
    "total_min": 507,
    "profond_min": 103,
    "leger_min": 260,
    "paradoxal_min": 144,
    "eveil_min": 0,
    "score": 88,
    "debut": 1783902854000,
    "fin": 1783933274000,
    "fc_repos_nuit": 53,
    "spo2_moy": 97.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 37,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 33,
    "haut": 46
   },
   "fc_repos": 53,
   "body_battery": {
    "max": 58,
    "min": 10,
    "reveil": 58
   },
   "stress_moy": 37,
   "pas": 7629,
   "readiness": {
    "score": 78,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-07-14",
   "sommeil": {
    "total_min": 298,
    "profond_min": 128,
    "leger_min": 108,
    "paradoxal_min": 62,
    "eveil_min": 0,
    "score": 65,
    "debut": 1783997582000,
    "fin": 1784015462000,
    "fc_repos_nuit": 51,
    "spo2_moy": 95.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 39,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 33,
    "haut": 46
   },
   "fc_repos": 51,
   "body_battery": {
    "max": 52,
    "min": 15,
    "reveil": 52
   },
   "stress_moy": 31,
   "pas": 6360,
   "readiness": {
    "score": 79,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-07-15",
   "sommeil": {
    "total_min": 344,
    "profond_min": 110,
    "leger_min": 178,
    "paradoxal_min": 56,
    "eveil_min": 0,
    "score": 74,
    "debut": 1784080750000,
    "fin": 1784101390000,
    "fc_repos_nuit": 50,
    "spo2_moy": 95.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 40,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 46
   },
   "fc_repos": 50,
   "body_battery": {
    "max": 72,
    "min": 7,
    "reveil": 72
   },
   "stress_moy": 40,
   "pas": 16439,
   "readiness": {
    "score": 72,
    "niveau": "MODERATE"
   }
  },
  {
   "date": "2026-07-16",
   "sommeil": {
    "total_min": 329,
    "profond_min": 94,
    "leger_min": 210,
    "paradoxal_min": 25,
    "eveil_min": 0,
    "score": 70,
    "debut": 1784160726000,
    "fin": 1784180466000,
    "fc_repos_nuit": 50,
    "spo2_moy": 93.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 44,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 46
   },
   "fc_repos": 50,
   "body_battery": {
    "max": 72,
    "min": 7,
    "reveil": 66
   },
   "stress_moy": 35,
   "pas": 9670,
   "readiness": {
    "score": 75,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-07-17",
   "sommeil": {
    "total_min": 466,
    "profond_min": 114,
    "leger_min": 241,
    "paradoxal_min": 111,
    "eveil_min": 1,
    "score": 89,
    "debut": 1784243784000,
    "fin": 1784271804000,
    "fc_repos_nuit": 52,
    "spo2_moy": 95.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 37,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 46
   },
   "fc_repos": 52,
   "body_battery": {
    "max": 65,
    "min": 9,
    "reveil": 65
   },
   "stress_moy": 44,
   "pas": 5484,
   "readiness": {
    "score": 89,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-07-18",
   "fc_repos": 55,
   "body_battery": {
    "max": 66,
    "min": 5,
    "reveil": null
   },
   "stress_moy": 64,
   "pas": 5293,
   "readiness": {
    "score": 90,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-07-19",
   "sommeil": {
    "total_min": 502,
    "profond_min": 63,
    "leger_min": 321,
    "paradoxal_min": 118,
    "eveil_min": 2,
    "score": 83,
    "debut": 1784421504000,
    "fin": 1784451744000,
    "fc_repos_nuit": 55,
    "spo2_moy": 96.0,
    "respiration_moy": 17.0
   },
   "hrv_nuit": 35,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 46
   },
   "fc_repos": 55,
   "body_battery": {
    "max": 50,
    "min": 5,
    "reveil": 50
   },
   "stress_moy": 39,
   "pas": 10904,
   "readiness": {
    "score": 38,
    "niveau": "LOW"
   }
  },
  {
   "date": "2026-07-20",
   "sommeil": {
    "total_min": 304,
    "profond_min": 102,
    "leger_min": 184,
    "paradoxal_min": 18,
    "eveil_min": 0,
    "score": 57,
    "debut": 1784509119000,
    "fin": 1784527359000,
    "fc_repos_nuit": 55,
    "spo2_moy": 95.0,
    "respiration_moy": 17.0
   },
   "hrv_nuit": 32,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 46
   },
   "fc_repos": 55,
   "body_battery": {
    "max": 45,
    "min": 5,
    "reveil": 45
   },
   "stress_moy": 49,
   "pas": 6567,
   "readiness": {
    "score": 25,
    "niveau": "LOW"
   }
  },
  {
   "date": "2026-07-21",
   "sommeil": {
    "total_min": 458,
    "profond_min": 62,
    "leger_min": 302,
    "paradoxal_min": 94,
    "eveil_min": 0,
    "score": 76,
    "debut": 1784586299000,
    "fin": 1784613779000,
    "fc_repos_nuit": 51,
    "spo2_moy": 97.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 36,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 46
   },
   "fc_repos": 51,
   "body_battery": {
    "max": 49,
    "min": 5,
    "reveil": 49
   },
   "stress_moy": 44,
   "pas": 7110,
   "readiness": {
    "score": 50,
    "niveau": "MODERATE"
   }
  },
  {
   "date": "2026-07-22",
   "sommeil": {
    "total_min": 424,
    "profond_min": 149,
    "leger_min": 166,
    "paradoxal_min": 109,
    "eveil_min": 0,
    "score": 79,
    "debut": 1784674630000,
    "fin": 1784700070000,
    "fc_repos_nuit": 50,
    "spo2_moy": 97.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 39,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 46
   },
   "fc_repos": 50,
   "body_battery": {
    "max": 61,
    "min": 5,
    "reveil": 61
   },
   "stress_moy": 44,
   "pas": 9427,
   "readiness": {
    "score": 68,
    "niveau": "MODERATE"
   }
  },
  {
   "date": "2026-07-23",
   "sommeil": {
    "total_min": 416,
    "profond_min": 94,
    "leger_min": 232,
    "paradoxal_min": 90,
    "eveil_min": 4,
    "score": 81,
    "debut": 1784761368000,
    "fin": 1784786568000,
    "fc_repos_nuit": 49,
    "spo2_moy": 94.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 37,
   "hrv_statut": "UNBALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 46
   },
   "fc_repos": 49,
   "body_battery": {
    "max": 57,
    "min": 5,
    "reveil": 57
   },
   "stress_moy": 34,
   "pas": 8964,
   "readiness": {
    "score": 75,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-07-24",
   "sommeil": {
    "total_min": 479,
    "profond_min": 118,
    "leger_min": 236,
    "paradoxal_min": 125,
    "eveil_min": 0,
    "score": 97,
    "debut": 1784844122000,
    "fin": 1784872862000,
    "fc_repos_nuit": 47,
    "spo2_moy": 95.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 41,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 46
   },
   "fc_repos": 47,
   "body_battery": {
    "max": 87,
    "min": 25,
    "reveil": 87
   },
   "stress_moy": 26,
   "pas": 9221,
   "readiness": {
    "score": 95,
    "niveau": "PRIME"
   }
  },
  {
   "date": "2026-07-25",
   "sommeil": {
    "total_min": 465,
    "profond_min": 58,
    "leger_min": 287,
    "paradoxal_min": 120,
    "eveil_min": 20,
    "score": 84,
    "debut": 1784938704000,
    "fin": 1784967804000,
    "fc_repos_nuit": 51,
    "spo2_moy": 97.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 39,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 46
   },
   "fc_repos": 51,
   "body_battery": {
    "max": 82,
    "min": 15,
    "reveil": 82
   },
   "stress_moy": 39,
   "pas": 5418,
   "readiness": {
    "score": 92,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-07-26",
   "sommeil": {
    "total_min": 344,
    "profond_min": 105,
    "leger_min": 163,
    "paradoxal_min": 76,
    "eveil_min": 0,
    "score": 81,
    "debut": 1785023664000,
    "fin": 1785044304000,
    "fc_repos_nuit": 49,
    "spo2_moy": null,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 43,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 46
   },
   "fc_repos": 49,
   "body_battery": {
    "max": 51,
    "min": 14,
    "reveil": null
   },
   "stress_moy": 42,
   "pas": 13925,
   "readiness": {
    "score": 75,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-07-27",
   "sommeil": {
    "total_min": 324,
    "profond_min": 89,
    "leger_min": 159,
    "paradoxal_min": 76,
    "eveil_min": 0,
    "score": 75,
    "debut": 1785112546000,
    "fin": 1785131986000,
    "fc_repos_nuit": 50,
    "spo2_moy": 95.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 37,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 46
   },
   "fc_repos": 50,
   "body_battery": {
    "max": 60,
    "min": 5,
    "reveil": 60
   },
   "stress_moy": 38,
   "pas": 16674,
   "readiness": {
    "score": 75,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-07-28",
   "sommeil": {
    "total_min": 376,
    "profond_min": 110,
    "leger_min": 174,
    "paradoxal_min": 92,
    "eveil_min": 0,
    "score": 89,
    "debut": 1785195844000,
    "fin": 1785218404000,
    "fc_repos_nuit": 49,
    "spo2_moy": 96.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 41,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 49,
   "body_battery": {
    "max": 68,
    "min": 5,
    "reveil": 68
   },
   "stress_moy": 38,
   "pas": 9761,
   "readiness": {
    "score": 94,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-07-29",
   "sommeil": {
    "total_min": 395,
    "profond_min": 94,
    "leger_min": 221,
    "paradoxal_min": 80,
    "eveil_min": 8,
    "score": 79,
    "debut": 1785278842000,
    "fin": 1785303022000,
    "fc_repos_nuit": 50,
    "spo2_moy": 96.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 40,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 50,
   "body_battery": {
    "max": 65,
    "min": 5,
    "reveil": 64
   },
   "stress_moy": 40,
   "pas": 13097,
   "readiness": {
    "score": 89,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-07-30",
   "sommeil": {
    "total_min": 248,
    "profond_min": 165,
    "leger_min": 65,
    "paradoxal_min": 18,
    "eveil_min": 0,
    "score": 54,
    "debut": 1785371299000,
    "fin": 1785386179000,
    "fc_repos_nuit": 49,
    "spo2_moy": 96.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 33,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 49,
   "body_battery": {
    "max": 39,
    "min": 5,
    "reveil": 39
   },
   "stress_moy": 41,
   "pas": 12963,
   "readiness": {
    "score": 55,
    "niveau": "MODERATE"
   }
  },
  {
   "date": "2026-07-31",
   "sommeil": {
    "total_min": 293,
    "profond_min": 126,
    "leger_min": 126,
    "paradoxal_min": 41,
    "eveil_min": 0,
    "score": 67,
    "debut": 1785466435000,
    "fin": 1785484015000,
    "fc_repos_nuit": 48,
    "spo2_moy": 94.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 38,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 48,
   "body_battery": {
    "max": 49,
    "min": 5,
    "reveil": 48
   },
   "stress_moy": 27,
   "pas": 13296,
   "readiness": {
    "score": 52,
    "niveau": "MODERATE"
   }
  },
  {
   "date": "2026-08-01",
   "sommeil": {
    "total_min": 488,
    "profond_min": 87,
    "leger_min": 299,
    "paradoxal_min": 102,
    "eveil_min": 1,
    "score": 95,
    "debut": 1785540555000,
    "fin": 1785569895000,
    "fc_repos_nuit": 46,
    "spo2_moy": 94.0,
    "respiration_moy": 14.0
   },
   "hrv_nuit": 46,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 46,
   "body_battery": {
    "max": 98,
    "min": 17,
    "reveil": 98
   },
   "stress_moy": 23,
   "pas": 14529,
   "readiness": {
    "score": 93,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-08-02",
   "sommeil": {
    "total_min": 474,
    "profond_min": 67,
    "leger_min": 300,
    "paradoxal_min": 107,
    "eveil_min": 4,
    "score": 91,
    "debut": 1785625574000,
    "fin": 1785654254000,
    "fc_repos_nuit": 49,
    "spo2_moy": 96.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 44,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 49,
   "body_battery": {
    "max": 92,
    "min": 28,
    "reveil": 92
   },
   "stress_moy": 27,
   "pas": 16331,
   "readiness": {
    "score": 100,
    "niveau": "PRIME"
   }
  },
  {
   "date": "2026-08-03",
   "sommeil": {
    "total_min": 441,
    "profond_min": 109,
    "leger_min": 236,
    "paradoxal_min": 96,
    "eveil_min": 1,
    "score": 92,
    "debut": 1785713774000,
    "fin": 1785740294000,
    "fc_repos_nuit": 47,
    "spo2_moy": 96.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 45,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 47,
   "body_battery": {
    "max": 96,
    "min": 21,
    "reveil": 96
   },
   "stress_moy": 31,
   "pas": 14285,
   "readiness": {
    "score": 100,
    "niveau": "PRIME"
   }
  },
  {
   "date": "2026-08-04",
   "sommeil": {
    "total_min": 467,
    "profond_min": 140,
    "leger_min": 225,
    "paradoxal_min": 102,
    "eveil_min": 119,
    "score": 70,
    "debut": 1785795187000,
    "fin": 1785830347000,
    "fc_repos_nuit": 51,
    "spo2_moy": 96.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 38,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 51,
   "body_battery": {
    "max": 77,
    "min": 18,
    "reveil": 77
   },
   "stress_moy": 25,
   "pas": 1216,
   "readiness": {
    "score": 97,
    "niveau": "PRIME"
   }
  },
  {
   "date": "2026-08-05",
   "sommeil": {
    "total_min": 308,
    "profond_min": 122,
    "leger_min": 110,
    "paradoxal_min": 76,
    "eveil_min": 0,
    "score": 74,
    "debut": 1785891141000,
    "fin": 1785909621000,
    "fc_repos_nuit": 50,
    "spo2_moy": 97.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 38,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 50,
   "body_battery": {
    "max": 62,
    "min": 5,
    "reveil": 62
   },
   "stress_moy": 40,
   "pas": 18261,
   "readiness": {
    "score": 65,
    "niveau": "MODERATE"
   }
  },
  {
   "date": "2026-08-06",
   "sommeil": {
    "total_min": 490,
    "profond_min": 109,
    "leger_min": 217,
    "paradoxal_min": 164,
    "eveil_min": 0,
    "score": 87,
    "debut": 1785970920000,
    "fin": 1786000320000,
    "fc_repos_nuit": 50,
    "spo2_moy": 93.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 39,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 50,
   "body_battery": {
    "max": 79,
    "min": 7,
    "reveil": 79
   },
   "stress_moy": 31,
   "pas": 14082,
   "readiness": {
    "score": 27,
    "niveau": "LOW"
   }
  },
  {
   "date": "2026-08-07",
   "sommeil": {
    "total_min": 442,
    "profond_min": 118,
    "leger_min": 235,
    "paradoxal_min": 89,
    "eveil_min": 0,
    "score": 85,
    "debut": 1786058033000,
    "fin": 1786084553000,
    "fc_repos_nuit": 50,
    "spo2_moy": 97.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 39,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 50,
   "body_battery": {
    "max": 75,
    "min": 18,
    "reveil": 75
   },
   "stress_moy": 31,
   "pas": 10859,
   "readiness": {
    "score": 59,
    "niveau": "MODERATE"
   }
  },
  {
   "date": "2026-08-08",
   "sommeil": {
    "total_min": 503,
    "profond_min": 86,
    "leger_min": 313,
    "paradoxal_min": 104,
    "eveil_min": 6,
    "score": 87,
    "debut": 1786140195000,
    "fin": 1786170735000,
    "fc_repos_nuit": 47,
    "spo2_moy": 95.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 39,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 47,
   "body_battery": {
    "max": 91,
    "min": 26,
    "reveil": 91
   },
   "stress_moy": 30,
   "pas": 13352,
   "readiness": {
    "score": 82,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-08-09",
   "sommeil": {
    "total_min": 601,
    "profond_min": 103,
    "leger_min": 376,
    "paradoxal_min": 122,
    "eveil_min": 14,
    "score": 87,
    "debut": 1786228755000,
    "fin": 1786265655000,
    "fc_repos_nuit": 51,
    "spo2_moy": 96.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 46,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 51,
   "body_battery": {
    "max": 93,
    "min": 27,
    "reveil": 93
   },
   "stress_moy": 32,
   "pas": 14959,
   "readiness": {
    "score": 85,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-08-10",
   "sommeil": {
    "total_min": 517,
    "profond_min": 86,
    "leger_min": 311,
    "paradoxal_min": 120,
    "eveil_min": 13,
    "score": 87,
    "debut": 1786316415000,
    "fin": 1786348215000,
    "fc_repos_nuit": 51,
    "spo2_moy": 96.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 37,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 35,
    "haut": 46
   },
   "fc_repos": 51,
   "body_battery": {
    "max": 77,
    "min": 20,
    "reveil": 77
   },
   "stress_moy": 37,
   "pas": 14545,
   "readiness": {
    "score": 84,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-08-11",
   "sommeil": {
    "total_min": 569,
    "profond_min": 101,
    "leger_min": 333,
    "paradoxal_min": 135,
    "eveil_min": 12,
    "score": 87,
    "debut": 1786399995000,
    "fin": 1786434855000,
    "fc_repos_nuit": 52,
    "spo2_moy": 95.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 39,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 35,
    "haut": 46
   },
   "fc_repos": 52,
   "body_battery": {
    "max": 78,
    "min": 19,
    "reveil": 77
   },
   "stress_moy": 38,
   "pas": 11370,
   "readiness": {
    "score": 86,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-08-12",
   "sommeil": {
    "total_min": 531,
    "profond_min": 109,
    "leger_min": 294,
    "paradoxal_min": 128,
    "eveil_min": 1,
    "score": 89,
    "debut": 1786490334000,
    "fin": 1786522254000,
    "fc_repos_nuit": 51,
    "spo2_moy": 96.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 34,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 35,
    "haut": 45
   },
   "fc_repos": 51,
   "body_battery": {
    "max": 68,
    "min": 16,
    "reveil": 68
   },
   "stress_moy": 40,
   "pas": 16987,
   "readiness": {
    "score": 90,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-08-13",
   "sommeil": {
    "total_min": 480,
    "profond_min": 56,
    "leger_min": 322,
    "paradoxal_min": 102,
    "eveil_min": 3,
    "score": 83,
    "debut": 1786579035000,
    "fin": 1786608015000,
    "fc_repos_nuit": 52,
    "spo2_moy": 95.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 35,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 35,
    "haut": 45
   },
   "fc_repos": 52,
   "body_battery": {
    "max": 61,
    "min": 10,
    "reveil": 61
   },
   "stress_moy": 43,
   "pas": 15607,
   "readiness": {
    "score": 89,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-08-14",
   "sommeil": {
    "total_min": 568,
    "profond_min": 94,
    "leger_min": 364,
    "paradoxal_min": 110,
    "eveil_min": 51,
    "score": 68,
    "debut": 1786661055000,
    "fin": 1786698195000,
    "fc_repos_nuit": 52,
    "spo2_moy": 95.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 36,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 35,
    "haut": 45
   },
   "fc_repos": 52,
   "body_battery": {
    "max": 54,
    "min": 13,
    "reveil": 54
   },
   "stress_moy": 41,
   "pas": 12503,
   "readiness": {
    "score": 73,
    "niveau": "MODERATE"
   }
  },
  {
   "date": "2026-08-15",
   "sommeil": {
    "total_min": 560,
    "profond_min": 65,
    "leger_min": 376,
    "paradoxal_min": 119,
    "eveil_min": 15,
    "score": 73,
    "debut": 1786746281000,
    "fin": 1786780781000,
    "fc_repos_nuit": 53,
    "spo2_moy": 95.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 35,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 35,
    "haut": 45
   },
   "fc_repos": 53,
   "body_battery": {
    "max": 59,
    "min": 9,
    "reveil": 59
   },
   "stress_moy": 46,
   "pas": 13054,
   "readiness": {
    "score": 73,
    "niveau": "MODERATE"
   }
  },
  {
   "date": "2026-08-16",
   "sommeil": {
    "total_min": 376,
    "profond_min": 101,
    "leger_min": 259,
    "paradoxal_min": 16,
    "eveil_min": 36,
    "score": 54,
    "debut": 1786834090000,
    "fin": 1786858810000,
    "fc_repos_nuit": 55,
    "spo2_moy": 95.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 34,
   "hrv_statut": "UNBALANCED",
   "hrv_base": {
    "bas": 35,
    "haut": 46
   },
   "fc_repos": 55,
   "body_battery": {
    "max": 36,
    "min": 5,
    "reveil": 36
   },
   "stress_moy": 51,
   "pas": 12170,
   "readiness": {
    "score": 46,
    "niveau": "LOW"
   }
  },
  {
   "date": "2026-08-17",
   "sommeil": {
    "total_min": 445,
    "profond_min": 66,
    "leger_min": 271,
    "paradoxal_min": 108,
    "eveil_min": 0,
    "score": 64,
    "debut": 1786919650000,
    "fin": 1786946350000,
    "fc_repos_nuit": 56,
    "spo2_moy": 96.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 34,
   "hrv_statut": "UNBALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 56,
   "body_battery": {
    "max": 36,
    "min": 5,
    "reveil": 36
   },
   "stress_moy": 48,
   "pas": 12270,
   "readiness": {
    "score": 11,
    "niveau": "POOR"
   }
  },
  {
   "date": "2026-08-18",
   "sommeil": {
    "total_min": 551,
    "profond_min": 102,
    "leger_min": 322,
    "paradoxal_min": 127,
    "eveil_min": 0,
    "score": 77,
    "debut": 1787003476000,
    "fin": 1787036536000,
    "fc_repos_nuit": 56,
    "spo2_moy": 97.0,
    "respiration_moy": 17.0
   },
   "hrv_nuit": 28,
   "hrv_statut": "LOW",
   "hrv_base": {
    "bas": 35,
    "haut": 45
   },
   "fc_repos": 56,
   "body_battery": {
    "max": 34,
    "min": 5,
    "reveil": 34
   },
   "stress_moy": 53,
   "pas": 6927,
   "readiness": {
    "score": 31,
    "niveau": "LOW"
   }
  },
  {
   "date": "2026-08-19",
   "sommeil": {
    "total_min": 520,
    "profond_min": 96,
    "leger_min": 307,
    "paradoxal_min": 117,
    "eveil_min": 0,
    "score": 87,
    "debut": 1787089247000,
    "fin": 1787120438000,
    "fc_repos_nuit": 51,
    "spo2_moy": 94.0,
    "respiration_moy": 17.0
   },
   "hrv_nuit": 32,
   "hrv_statut": "LOW",
   "hrv_base": {
    "bas": 35,
    "haut": 45
   },
   "fc_repos": 51,
   "body_battery": {
    "max": 51,
    "min": 5,
    "reveil": 51
   },
   "stress_moy": 48,
   "pas": 8957,
   "readiness": {
    "score": 65,
    "niveau": "MODERATE"
   }
  },
  {
   "date": "2026-08-20",
   "sommeil": {
    "total_min": 386,
    "profond_min": 41,
    "leger_min": 314,
    "paradoxal_min": 31,
    "eveil_min": 5,
    "score": 71,
    "debut": 1787182598000,
    "fin": 1787206058000,
    "fc_repos_nuit": 53,
    "spo2_moy": 96.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 38,
   "hrv_statut": "LOW",
   "hrv_base": {
    "bas": 35,
    "haut": 45
   },
   "fc_repos": 53,
   "body_battery": {
    "max": 44,
    "min": 5,
    "reveil": 44
   },
   "stress_moy": 44,
   "pas": 19023,
   "readiness": {
    "score": 12,
    "niveau": "POOR"
   }
  },
  {
   "date": "2026-08-21",
   "sommeil": {
    "total_min": 518,
    "profond_min": 62,
    "leger_min": 341,
    "paradoxal_min": 115,
    "eveil_min": 1,
    "score": 86,
    "debut": 1787268555000,
    "fin": 1787299695000,
    "fc_repos_nuit": 52,
    "spo2_moy": 94.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 40,
   "hrv_statut": "LOW",
   "hrv_base": {
    "bas": 35,
    "haut": 45
   },
   "fc_repos": 52,
   "body_battery": {
    "max": 70,
    "min": 6,
    "reveil": 70
   },
   "stress_moy": 34,
   "pas": 9160,
   "readiness": {
    "score": 1,
    "niveau": "POOR"
   }
  },
  {
   "date": "2026-08-22",
   "sommeil": {
    "total_min": 497,
    "profond_min": 94,
    "leger_min": 294,
    "paradoxal_min": 109,
    "eveil_min": 6,
    "score": 90,
    "debut": 1787353269000,
    "fin": 1787383449000,
    "fc_repos_nuit": 50,
    "spo2_moy": 96.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 37,
   "hrv_statut": "LOW",
   "hrv_base": {
    "bas": 35,
    "haut": 45
   },
   "fc_repos": 50,
   "body_battery": {
    "max": 75,
    "min": 16,
    "reveil": 75
   },
   "stress_moy": 34,
   "pas": 7910,
   "readiness": {
    "score": 25,
    "niveau": "LOW"
   }
  },
  {
   "date": "2026-08-23",
   "sommeil": {
    "total_min": 507,
    "profond_min": 105,
    "leger_min": 282,
    "paradoxal_min": 120,
    "eveil_min": 0,
    "score": 96,
    "debut": 1787436198000,
    "fin": 1787466618000,
    "fc_repos_nuit": 47,
    "spo2_moy": 97.0,
    "respiration_moy": 14.0
   },
   "hrv_nuit": 42,
   "hrv_statut": "UNBALANCED",
   "hrv_base": {
    "bas": 35,
    "haut": 45
   },
   "fc_repos": 47,
   "body_battery": {
    "max": 92,
    "min": 7,
    "reveil": 92
   },
   "stress_moy": 37,
   "pas": 17577,
   "readiness": {
    "score": 11,
    "niveau": "POOR"
   }
  },
  {
   "date": "2026-08-24",
   "sommeil": {
    "total_min": 455,
    "profond_min": 108,
    "leger_min": 248,
    "paradoxal_min": 99,
    "eveil_min": 1,
    "score": 84,
    "debut": 1787527256000,
    "fin": 1787554616000,
    "fc_repos_nuit": 52,
    "spo2_moy": 96.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 32,
   "hrv_statut": "UNBALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 52,
   "body_battery": {
    "max": 50,
    "min": 7,
    "reveil": 50
   },
   "stress_moy": 41,
   "pas": 9663,
   "readiness": {
    "score": 41,
    "niveau": "LOW"
   }
  },
  {
   "date": "2026-08-25",
   "sommeil": {
    "total_min": 555,
    "profond_min": 144,
    "leger_min": 289,
    "paradoxal_min": 122,
    "eveil_min": 0,
    "score": 92,
    "debut": 1787608197000,
    "fin": 1787641497000,
    "fc_repos_nuit": 50,
    "spo2_moy": 95.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 39,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 50,
   "body_battery": {
    "max": 80,
    "min": 12,
    "reveil": 80
   },
   "stress_moy": 37,
   "pas": 18242,
   "readiness": {
    "score": 1,
    "niveau": "POOR"
   }
  },
  {
   "date": "2026-08-26",
   "fc_repos": 55,
   "body_battery": {
    "max": 71,
    "min": 6,
    "reveil": null
   },
   "stress_moy": 50,
   "pas": 26474,
   "readiness": {
    "score": 1,
    "niveau": "POOR"
   }
  },
  {
   "date": "2026-08-27",
   "sommeil": {
    "total_min": 522,
    "profond_min": 53,
    "leger_min": 345,
    "paradoxal_min": 124,
    "eveil_min": 2,
    "score": 90,
    "debut": 1787782111000,
    "fin": 1787813551000,
    "fc_repos_nuit": 47,
    "spo2_moy": 97.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 49,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 47,
   "body_battery": {
    "max": 89,
    "min": 19,
    "reveil": 89
   },
   "stress_moy": 29,
   "pas": 15642,
   "readiness": {
    "score": 10,
    "niveau": "POOR"
   }
  },
  {
   "date": "2026-08-28",
   "sommeil": {
    "total_min": 389,
    "profond_min": 129,
    "leger_min": 201,
    "paradoxal_min": 59,
    "eveil_min": 13,
    "score": 77,
    "debut": 1787872860000,
    "fin": 1787896980000,
    "fc_repos_nuit": 49,
    "spo2_moy": 96.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 35,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 49,
   "body_battery": {
    "max": 66,
    "min": 11,
    "reveil": 66
   },
   "stress_moy": 34,
   "pas": 24407,
   "readiness": {
    "score": 1,
    "niveau": "POOR"
   }
  },
  {
   "date": "2026-08-29",
   "sommeil": {
    "total_min": 504,
    "profond_min": 117,
    "leger_min": 263,
    "paradoxal_min": 124,
    "eveil_min": 2,
    "score": 90,
    "debut": 1787953340000,
    "fin": 1787983700000,
    "fc_repos_nuit": 49,
    "spo2_moy": 96.0,
    "respiration_moy": 16.0
   },
   "hrv_nuit": 32,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 49,
   "body_battery": {
    "max": 71,
    "min": 5,
    "reveil": 71
   },
   "stress_moy": 36,
   "pas": 23043,
   "readiness": {
    "score": 18,
    "niveau": "POOR"
   }
  },
  {
   "date": "2026-08-30",
   "sommeil": {
    "total_min": 214,
    "profond_min": 45,
    "leger_min": 164,
    "paradoxal_min": 5,
    "eveil_min": 50,
    "score": 36,
    "debut": 1788057781000,
    "fin": 1788073621000,
    "fc_repos_nuit": 54,
    "spo2_moy": 97.0,
    "respiration_moy": 17.0
   },
   "hrv_nuit": 25,
   "hrv_statut": "UNBALANCED",
   "hrv_base": {
    "bas": 33,
    "haut": 45
   },
   "fc_repos": 54,
   "body_battery": {
    "max": 20,
    "min": 5,
    "reveil": 20
   },
   "stress_moy": 38,
   "pas": 7938,
   "readiness": {
    "score": 1,
    "niveau": "POOR"
   }
  },
  {
   "date": "2026-08-31",
   "sommeil": {
    "total_min": 545,
    "profond_min": 104,
    "leger_min": 315,
    "paradoxal_min": 126,
    "eveil_min": 0,
    "score": 91,
    "debut": 1788127661000,
    "fin": 1788160361000,
    "fc_repos_nuit": 49,
    "spo2_moy": 96.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 39,
   "hrv_statut": "UNBALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 49,
   "body_battery": {
    "max": 76,
    "min": 9,
    "reveil": 76
   },
   "stress_moy": 27,
   "pas": 14860,
   "readiness": {
    "score": 40,
    "niveau": "LOW"
   }
  },
  {
   "date": "2026-09-01",
   "sommeil": {
    "total_min": 483,
    "profond_min": 151,
    "leger_min": 223,
    "paradoxal_min": 109,
    "eveil_min": 3,
    "score": 96,
    "debut": 1788212915000,
    "fin": 1788242075000,
    "fc_repos_nuit": 48,
    "spo2_moy": 96.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 43,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 48,
   "body_battery": {
    "max": 95,
    "min": 18,
    "reveil": 95
   },
   "stress_moy": 32,
   "pas": 16548,
   "readiness": {
    "score": 66,
    "niveau": "MODERATE"
   }
  },
  {
   "date": "2026-09-02",
   "sommeil": {
    "total_min": 522,
    "profond_min": 88,
    "leger_min": 323,
    "paradoxal_min": 111,
    "eveil_min": 0,
    "score": 90,
    "debut": 1788299181000,
    "fin": 1788330501000,
    "fc_repos_nuit": 48,
    "spo2_moy": 95.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 46,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 48,
   "body_battery": {
    "max": 99,
    "min": 24,
    "reveil": 99
   },
   "stress_moy": 31,
   "pas": 8503,
   "readiness": {
    "score": 93,
    "niveau": "HIGH"
   }
  },
  {
   "date": "2026-09-03",
   "sommeil": {
    "total_min": 450,
    "profond_min": 128,
    "leger_min": 228,
    "paradoxal_min": 94,
    "eveil_min": 0,
    "score": 96,
    "debut": 1788385800000,
    "fin": 1788412800000,
    "fc_repos_nuit": 47,
    "spo2_moy": 96.0,
    "respiration_moy": 15.0
   },
   "hrv_nuit": 45,
   "hrv_statut": "BALANCED",
   "hrv_base": {
    "bas": 34,
    "haut": 45
   },
   "fc_repos": 47,
   "body_battery": {
    "max": 97,
    "min": 44,
    "reveil": 97
   },
   "stress_moy": 11,
   "pas": 88,
   "readiness": {
    "score": 93,
    "niveau": "HIGH"
   }
  }
 ]
};
