// scripts/wods-index.js — indexe la base CrossFit (scripts/.wod-base.json) pour l'application :
// traduction FR, mouvements détectés, format, durée estimée, matériel nécessaire.
// Sortie : js/wods-data.js (window.WODS)

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { traduireWod, mouvementsDe } from "./mouvements.js";
import { BENCHMARKS } from "./benchmarks.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BASE = path.join(__dirname, ".wod-base.json");
const OUT = path.join(__dirname, "../js/wods-data.js");

const MATERIEL = {
  barre: ["barre"], haltère: ["haltère"], kettlebell: ["kettlebell"],
  box: [/box/i], corde: [/corde/i], anneaux: [/anneaux/i], mur: [/mur|wall ball/i],
  rameur: [/rameur/i], vélo: [/vélo/i], ski: [/ski/i], "barre de traction": [/traction|pointes de pieds|muscle-up/i],
};

function format(lignes) {
  const t = lignes.join(" ").toLowerCase();
  if (/rest day/.test(t)) return "repos";
  if (/as many rounds|amrap/.test(t)) return "AMRAP";
  if (/every minute|emom/.test(t)) return "EMOM";
  if (/for time/.test(t)) return "For time";
  if (/for load|find a heavy|\d+-\d+-\d+-\d+-\d+/.test(t)) return "Force";
  if (/max reps/.test(t)) return "Max reps";
  return "Autre";
}

function dureeEstimee(lignes) {
  const t = lignes.join(" ");
  const cap = t.match(/in (\d+)\s*minutes?|(\d+)-minute/i);          // AMRAP / EMOM / time cap = durée exacte
  if (cap) return parseInt(cap[1] || cap[2], 10);
  const rounds = parseInt((t.match(/(\d+)\s*rounds?/i) || [])[1] || 1, 10);
  // distances (par tour)
  let minDist = 0;
  for (const m of t.matchAll(/(\d[\d,]*)\s*(?:-)?\s*(?:meter|metre|m)\b/gi)) minDist += parseInt(m[1].replace(/,/g, ""), 10) / 210;
  for (const m of t.matchAll(/(\d+)\s*(?:-)?\s*mile/gi)) minDist += parseInt(m[1], 10) * 8;
  for (const m of t.matchAll(/(\d+)\s*(?:-)?\s*calorie/gi)) minDist += parseInt(m[1], 10) / 14;
  // répétitions : uniquement les nombres < 100 qui ne sont ni des charges ni des distances
  let reps = 0;
  for (const m of t.matchAll(/\b(\d{1,3})\s+(?![\d,]*\s*(?:kg|lb|m\b|meter|mile|calorie|inch|cm|minute|second))([A-Za-z][A-Za-z-]+)/g)) {
    const n = parseInt(m[1], 10);
    if (n <= 100) reps += n;
  }
  const serie = t.match(/(\d+)-(\d+)-(\d+)(-(\d+))*\s*reps?/i);       // 21-15-9 : reps déjà toutes comptées
  const est = minDist * rounds + (reps * (serie ? 1 : rounds)) / 20;
  return Math.max(3, Math.min(75, Math.round(est) || 12));
}

function materielDe(fr) {
  const t = fr.join(" ");
  return Object.entries(MATERIEL).filter(([, pats]) => pats.some(p => typeof p === "string" ? t.includes(p) : p.test(t))).map(([k]) => k);
}

const db = JSON.parse(fs.readFileSync(BASE, "utf8"));
const entrees = [];

for (const [date, w] of Object.entries(db.daily || {})) {
  if (w.repos) continue;
  const fr = traduireWod(w.wod);
  entrees.push({
    id: "cf" + w.code, source: "CrossFit.com", date,
    en: w.wod, fr,
    format: format(w.wod), duree: dureeEstimee(w.wod),
    mouvements: mouvementsDe(w.wod).map(m => ({ en: m.en, fr: m.fr, schema: m.schema || null })),
    materiel: materielDe(fr),
    stimulusFr: w.stimulus ? traduireWod([w.stimulus.slice(0, 400)])[0] : "",
    scaling: { int: traduireWod(w.intermediate), deb: traduireWod(w.beginner) },
  });
}
for (const b of BENCHMARKS) {
  const fr = traduireWod(b.wod);
  entrees.push({
    id: "bench-" + b.nom.toLowerCase().replace(/[^a-z]/g, ""), source: "Benchmark", nom: b.nom,
    en: b.wod, fr, format: format(b.wod), duree: dureeEstimee(b.wod),
    mouvements: mouvementsDe(b.wod).map(m => ({ en: m.en, fr: m.fr, schema: m.schema || null })),
    materiel: materielDe(fr), stimulusFr: "Repère de test : à refaire toutes les 8 à 12 semaines pour mesurer la progression.", scaling: { int: [], deb: [] },
  });
}
for (const h of db.heroes || []) {
  const fr = traduireWod(h.wod);
  entrees.push({
    id: "hero-" + h.nom.toLowerCase().replace(/[^a-z]/g, ""), source: "Hero WOD", nom: h.nom,
    en: h.wod, fr, format: format(h.wod), duree: dureeEstimee(h.wod),
    mouvements: mouvementsDe(h.wod).map(m => ({ en: m.en, fr: m.fr, schema: m.schema || null })),
    materiel: materielDe(fr), stimulusFr: "", scaling: { int: [], deb: [] },
  });
}

entrees.sort((a, b) => (b.date || "").localeCompare(a.date || "") || (a.nom || "").localeCompare(b.nom || ""));
fs.writeFileSync(OUT, `// AUTO-GENERATED by scripts/wods-index.js — ne pas éditer.\nwindow.WODS = ${JSON.stringify(entrees)};\n`);
console.log(`📚 ${entrees.length} séances indexées → js/wods-data.js (${Math.round(fs.statSync(OUT).size / 1024)} ko)`);
console.log(`   ${entrees.filter(e => e.source === "Hero WOD").length} hero · ${entrees.filter(e => e.source === "CrossFit.com").length} quotidiens`);
